### ISSUE TITLE
clang: error: no such file or directory: 'libpython3.8.a'

### ISSUE THREAD

**Issue by alvarezlsq** [pyenv/pyenv#2340] opened 2022-04-26 20:03 UTC
Too many issues will kill our team's development velocity, drastically.
Make sure you have checked all steps below.

### Prerequisite
* [ ] Make sure your problem is not listed in [the common build problems](https://github.com/pyenv/pyenv/wiki/Common-build-problems).
* [ ] Make sure no duplicated issue has already been reported in [the pyenv issues](https://github.com/pyenv/pyenv/issues). You should look for closed issues, too.
* [ ] Make sure you are not asking us to help solving your specific issue.
  * GitHub issues is opened mainly for development purposes. If you want to ask someone to help solving your problem, go to some community site like [Gitter](https://gitter.im/yyuu/pyenv), [StackOverflow](https://stackoverflow.com/questions/tagged/pyenv), etc.
* [ ] Make sure your problem is not derived from packaging (e.g. [Homebrew](https://brew.sh)).
  * Please refer to the package documentation for the installation issues, etc.
* [ ] Make sure your problem is not derived from plugins.
  * This repository is maintaining `pyenv` and the default `python-build` plugin only. Please refrain from reporting issues of other plugins here.

### Description
- [ ] Platform information (e.g. Ubuntu Linux 16.04): Mac OS X Monterey 12.2.1
- [ ] OS architecture (e.g. amd64): Intel
- [ ] pyenv version: 2.2.5
- [ ] Python version: 3.8.12
- [ ] C Compiler information (e.g. gcc 7.3): -
- [ ] Please attach the debug trace of the failing command as a gist:
  * Run `env PYENV_DEBUG=1 <faulty command> 2>&1 | tee trace.log` and attach `trace.log`. E.g. if you have a problem with installing Python, run `env PYENV_DEBUG=1 pyenv install -v <version> 2>&1 | tee trace.log` (note the `-v` option to `pyenv install`).

[trace.log](https://github.com/pyenv/pyenv/files/8566512/trace.log)

**Comment by native-api** [comment] 2022-04-26 20:13
Looks like an antivirus' handiwork. There's an `ar rcs` command that builds `libpython3.8.a` without any error -- and immediately after that, it's somehow missing.

**Comment by native-api** [comment] 2022-04-26 20:46
Other users also report build errors if Homebrew `binutils` are on PATH: https://github.com/pyenv/pyenv/issues/2283#issuecomment-1075923205
Binutils are keg-only because they break Apple's toolchain.

**Comment by alvarezlsq** [comment] 2022-04-27 17:35
I updated my os version to Monterey 12.3.1, but now I think I lost clang++. Any insight?
[trace.log](https://github.com/pyenv/pyenv/files/8575116/trace.log)

**Comment by native-api** [comment] 2022-04-29 05:26
Now it's a duplicate of #2143

**Closed** 2022-04-29 05:54 UTC
