### ISSUE TITLE
Can't build 3.12.0rc2 on macOS Ventura 13.5.1

### ISSUE THREAD

**Issue by georgevreilly** [pyenv/pyenv#2780] opened 2023-09-07 18:41 UTC
Too many issues will kill our team's development velocity, drastically.
Make sure you have checked all steps below.

### Prerequisite
* [ ] Make sure your problem is not listed in [the common build problems](https://github.com/pyenv/pyenv/wiki/Common-build-problems).
* [ ] Make sure no duplicated issue has already been reported in [the pyenv issues](https://github.com/pyenv/pyenv/issues). You should look for closed issues, too.
* [ ] Make sure you are not asking us to help solving your specific issue.
  * GitHub issues is opened mainly for development purposes. If you want to ask someone to help solving your problem, go to some community site like [Gitter](https://gitter.im/yyuu/pyenv), [StackOverflow](https://stackoverflow.com/questions/tagged/pyenv), etc.
* [ ] Make sure your problem is not derived from packaging (e.g. [Homebrew](https://brew.sh)).
  * Please refer to the package documentation for the installation issues, etc.
* [ ] Make sure your problem is not derived from plugins.
  * This repository is maintaining `pyenv` and the default `python-build` plugin only. Please refrain from reporting issues of other plugins here.

Problem seems to be `ld: warning: directory not found for option '-L/Users/georgevreilly/.pyenv/versions/3.12.0rc2/lib'`

### Description
- [ ] Platform information (e.g. Ubuntu Linux 16.04): macOS Ventura 13.5.1
- [ ] OS architecture (e.g. amd64): arm64
- [ ] pyenv version: pyenv 2.3.26
- [ ] Python version: 3.12.0rc2
- [ ] C Compiler information (e.g. gcc 7.3): Apple clang version 14.0.0 (clang-1400.0.29.202)
- [ ] Please attach the debug trace of the failing command as a gist:
  * Run `env PYENV_DEBUG=1 <faulty command> 2>&1 | tee trace.log` and attach `trace.log`. E.g. if you have a problem with installing Python, run `env PYENV_DEBUG=1 pyenv install -v <version> 2>&1 | tee trace.log` (note the `-v` option to `pyenv install`).
- [ ] If you have a problem with installing Python, please also attach `config.log` from the build directory
  * The build directory is reported after the "BUILD FAILED" message and is usually under `/tmp`.
- [ ] If the build succeeds but the problem is still with the build process (e.g. the resulting Python is missing a feature), please attach
  * the debug trace from reinstalling the faulty version with `env PYENV_DEBUG=1 pyenv install -f -k -v <version> 2>&1 | tee trace.log`
  * `config.log` from the build directory. When using `pyenv install` with `-k` as per above, the build directory will be under `$PYENV_ROOT/sources`.

* [trace.log](https://github.com/pyenv/pyenv/files/12552440/trace.log)
* [config.log](https://github.com/pyenv/pyenv/files/12552464/config.log)

**Comment by native-api** [comment] 2023-09-07 18:47
```
[ERROR] _hashlib failed to import: dlopen(/private/var/folders/wy/bmvnkqnd68577nmdg7fgmm6h0000gn/T/python-build.20230907113435.37198/Python-3.12.0rc2/build/lib.macosx-13.5-arm64-3.12/_hashlib.cpython-312-darwin.so, 0x0002): symbol not found in flat namespace '_EVP_MD_block_size'
[ERROR] _ssl failed to import: dlopen(/private/var/folders/wy/bmvnkqnd68577nmdg7fgmm6h0000gn/T/python-build.20230907113435.37198/Python-3.12.0rc2/build/lib.macosx-13.5-arm64-3.12/_ssl.cpython-312-darwin.so, 0x0002): symbol not found in flat namespace '_SSL_get_peer_certificate'
```

**Comment by native-api** [comment] 2023-09-07 18:47
Duplicate of https://github.com/pyenv/pyenv/issues/2746

**Closed** 2023-09-07 19:09 UTC

**Comment by georgevreilly** [comment] 2023-09-07 19:37
Thanks. I got it to work, based on https://github.com/pyenv/pyenv/issues/2746

```
$ env CONFIGURE_OPTS="--with-openssl=/opt/Homebrew/Cellar/openssl@3/3.1.2/" pyenv install 3.12.0rc2
python-build: use openssl@1.1 from homebrew
python-build: use readline from homebrew
Installing Python-3.12.0rc2...
python-build: use readline from homebrew
python-build: use zlib from xcode sdk
Installed Python-3.12.0rc2 to /Users/georgevreilly/.pyenv/versions/3.12.0rc2

$ PYENV_VERSION=3.12.0rc2 python --version
Python 3.12.0rc2

$ PYENV_VERSION=3.12.0rc2 python -c 'import ssl; print(ssl.OPENSSL_VERSION)'
OpenSSL 3.1.2 1 Aug 2023
```
