### ISSUE TITLE
pyenv should use version-specific `get-pip.py` when installing 2.6 and 3.2

### ISSUE THREAD

**Issue by di** [pyenv/pyenv#1127] opened 2018-03-21 18:28 UTC
The recent release of `pip` 9.0.2 unintentionally broke support for Python 2.6, and the related update to https://bootstrap.pypa.io/get-pip.py to use this version broke attempts to `pyenv install 2.6.x` due to this incompatibility.

Instead of using https://bootstrap.pypa.io/get-pip.py, `pyenv` should be using the version-specific installers at https://bootstrap.pypa.io/2.6/get-pip.py and https://bootstrap.pypa.io/3.2/get-pip.py

These won't actually fix the issue until a `pip` 9.0.3 release is made to fix Python 2.6 compatibility, but they should continue to work into the future, especially when `pip` 10.0.0 is released, at which point https://bootstrap.pypa.io/get-pip.py will definitely no longer support Python 2.6.

Happy to make a PR for this if it's deemed valid.

**Comment by joshfriend** [comment] 2018-03-21 19:47
Now that pypa/get-pip#17 seems to be resolved I think someone could actually start working on fixing this.

**Comment by di** [comment] 2018-03-21 19:53
The 2.6 version is not actually compatible with 2.6 and won't be until a 9.0.3 release of pip is made, see https://github.com/pypa/pip/issues/5093

**Comment by yyuu** [comment] 2018-03-22 01:52
As a quick workaround , declaring `GET_PIP_URL` on calling `pyenv install` will let `python-build` to use `get-pip.py` at the given URL. As long as the URL is returning correct response, it should work.

https://github.com/pyenv/pyenv/blob/v1.2.2/plugins/python-build/bin/python-build#L1807

For intrinsic fix, for non-CPython distributions, it's actually not easy to know if the Python compatibility version is 2.6/3.2 or not, prior to the build/install. I think it's nearly safe to assume to regard most of those non-CPython distributions as kind of edge cases, though.

Anyway I think that changing `get-pip` URL for older Pythons is a kind of tentative workaround and will not live longer. I think that pinning `pip` version within the build definition of 2.6/3.2 must be the right way to deal with the situation. We're doing similar for some ancient versions like 2.5.x.

https://github.com/pyenv/pyenv/blob/v1.2.2/plugins/python-build/share/python-build/2.5.6#L4-L5

**Comment by hokuto-k** [comment] 2018-03-22 03:31
@di 
Thank you for the submitting the issue.
just a hour ago pip 9.0.3 was released.

**Comment by hokuto-k** [comment] 2018-03-22 04:36
@yyuu 
>  I think that pinning pip version within the build definition of 2.6/3.2 must be the right way to deal with the situation. 
Can I work for it? I think in the near future pip 10 could be released so I think it's better to pin pip version to `9.0.3` so far so now.

---

BTW, the following part won't work if version is bigger than `8.0.0`:
https://github.com/pyenv/pyenv/blob/master/plugins/python-build/bin/python-build#L2120-L2123
because get-pip.py has been moved to its own repos.

**Comment by yyuu** [comment] 2018-03-22 05:03
@hokuto-k sure, thanks for your help!

> BTW, the following part won't work if version is bigger than 8.0.0:
https://github.com/pyenv/pyenv/blob/master/plugins/python-build/bin/python-build#L2120-L2123
> because get-pip.py has been moved to its own repos.

Correct. I also confirmed it doesn't work with 8.0.1+. Allowing users to override `GET_PIP_URL` would still make some sense, but at least the `PIP_VERSION` part isn't worth anymore. Maybe I'm going to tweak the code around there later.

**Comment by joshfriend** [comment] 2018-03-22 12:25
> For intrinsic fix, for non-CPython distributions, it's actually not easy to know if the Python compatibility version is 2.6/3.2 or not, prior to the installation of the version.

@yyuu in the probably rare case that this becomes an issue, isnt it possible to just set `GET_PIP_URL` in the build definition, or even better, `PIP_COMPATIBILITY_VERSION=2.6` or something similar? Since the ensurepip step happens after compiling python, perhaps python-build could inspect `sys.version_info` to determine this.

**Comment by yyuu** [comment] 2018-03-29 01:08
@joshfriend sorry for delay. I've finally made some changes on custom `GET_PIP_URL` for 2.6.x as #1131. Please have a look when you get some chance for it~

**Comment by joshfriend** [comment] 2018-03-29 02:41
Don't worry about it, I'm not a 2.6.x user ;)

**Comment by yyuu** [comment] 2018-03-29 03:24
I've merged #1131 as some tentative workaround for CPython 2.6, 3.2 and 3.3. As some intrinsic fix for the problem, pinning pip version for these Pythons must be still better idea to deal with the situation.

**Closed** 2021-05-07 21:32 UTC
Labels: type: enhancement
