### ISSUE TITLE
using wrong python-version file

### ISSUE THREAD

**Issue by lee218llnl** [pyenv/pyenv#1379] opened 2019-08-06 19:14 UTC
I'm not sure if you would consider this a bug, but there is a quirk with how pyenv is searching for the application-specific .python-version file. This is because the .pyenv/bin/python script searches for the first argument with a "/" to determine what it thinks is the application directory. However, if I execute a python script from my current working directory, and I don't specify the directory path (i.e., the full path or by using "./"), then it will actually use the path of an argument that I pass to my application/python script. If the path to the argument contains a .python-version file, then pyenv incorrectly picks that one up. Here's a simple reproducer to demonstrate:

bash-4.2$ pwd
/usr/workspace/testnewm/pyenv_test

bash-4.2$ cat test.py 
import sys
print (sys.version)

bash-4.2$ cat .python-version 
3.7.2

bash-4.2$ python ./test.py /p/lustre1/testnewm/dir/file
3.7.2 (default, Aug  6 2019, 10:49:54) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]

bash-4.2$ cat /p/lustre1/testnewm/dir/.python-version 
system

bash-4.2$ python test.py /p/lustre1/testnewm/dir/file
2.7.16 (default, Mar  4 2019, 06:38:09) 
[GCC 4.9.3]

I see there are some other issues w.r.t. choosing the .python-version, but I don't know if any of them describe this exact situation, so apologies if this is a duplicate.

**Comment by adrienrenaud** [comment] 2020-03-25 16:06
I do have the same issue. It makes pyenv unusable for me.

As soon as you give to your python script an argument with a "/" in it your are in great danger with pyenv!

**Comment by native-api** [comment] 2021-05-17 22:53
Duplicate of https://github.com/pyenv/pyenv/issues/1807

**Closed by native-api** 2021-05-17 22:53 UTC
