### ISSUE TITLE
Wrong .python-version file is used

### ISSUE THREAD

**Issue by pcoccoli** [pyenv/pyenv#1850] opened 2021-03-15 18:23 UTC
pyenv seems to choosing a .python-version file based on an argument to my script instead of the current working directory or the directory of the script itself.

### Prerequisite
* [x] Make sure your problem is not listed in [the common build problems](https://github.com/pyenv/pyenv/wiki/Common-build-problems).
* [ ] Make sure no duplicated issue has already been reported in [the pyenv issues](https://github.com/pyenv/pyenv/issues). You should look for closed issues, too.
* [x] Make sure you are not asking us to help solving your specific issue.
  * GitHub issues is opened mainly for development purposes. If you want to ask someone to help solving your problem, go to some community site like [Gitter](https://gitter.im/yyuu/pyenv), [StackOverflow](https://stackoverflow.com/questions/tagged/pyenv), etc.
* [x] Make sure your problem is not derived from packaging (e.g. [Homebrew](https://brew.sh)).
  * Please refer to the package documentation for the installation issues, etc.
* [ ] Make sure your problem is not derived from plugins.
  * This repository is maintaining `pyenv` and the default `python-build` plugin only. Please refrain from reporting issues of other plugins here.

It's possible this is the same issue as #1208 but I'm not certain.  The solution provided there doesn't work for me.

I'm also not certain if the pyenv-virtualenv plugin plays any role here.

### Description
- [x] Platform information (e.g. Ubuntu Linux 16.04): RHEL 8.3
- [x] OS architecture (e.g. amd64): amd64
- [x] pyenv version: v1.2.23
- [x] Python version: 3.6.8
- [x] C Compiler information (e.g. gcc 7.3): gcc 8
- [ ] Please attach verbose build log as gist
  * You can turn on verbose debug logging using by setting `PYENV_DEBUG=1`, e.g. `env PYENV_DEBUG=1 pyenv install -v 3.6.4`

Here's the output of a shell script that demonstrates the problem. It creates 2 virtualenvs, and puts a CSV file in one and python script in the other. The it goes into the second virtualenv and tries to run that script, passing in the relative path to the data file in the other virtualenv. For reasons I do not understand, pyenv is using the directory of the data file argument to choose which .python-version file it reads. This results in the the wrong virtualenv, and a ModuleNotFoundError (in this case, tabulate).

Link to gist with the script: https://gist.github.com/pcoccoli/6f13219d48bec9394aaf38003d94e78c

Output of sh -x pyenv_wrong_version.sh:

```
+ version=3.6.8
+ mkdir ve_1
+ cd ve_1
+ pyenv virtualenv 3.6.8 ve_1
Looking in links: /tmp/tmpxkrnjee8
Requirement already satisfied: setuptools in /home/pcoccoli/.pyenv/versions/3.6.8/envs/ve_1/lib/python3.6/site-packages (40.6.2)
Requirement already satisfied: pip in /home/pcoccoli/.pyenv/versions/3.6.8/envs/ve_1/lib/python3.6/site-packages (18.1)
+ pyenv local ve_1
+ pyenv version
ve_1 (set by /home/pcoccoli/tmp/test/ve_1/.python-version)
+ cd ..
+ mkdir ve_2
+ cd ve_2
+ pyenv virtualenv 3.6.8 ve_2
Looking in links: /tmp/tmp8jp_zdha
Requirement already satisfied: setuptools in /home/pcoccoli/.pyenv/versions/3.6.8/envs/ve_2/lib/python3.6/site-packages (40.6.2)
Requirement already satisfied: pip in /home/pcoccoli/.pyenv/versions/3.6.8/envs/ve_2/lib/python3.6/site-packages (18.1)
+ pyenv local ve_2
+ pyenv version
ve_2 (set by /home/pcoccoli/tmp/test/ve_2/.python-version)
+ pip install tabulate
Collecting tabulate
  Using cached https://files.pythonhosted.org/packages/ca/80/7c0cad11bd99985cfe7c09427ee0b4f9bd6b048bd13d4ffb32c6db237dfb/tabulate-0.8.9-py3-none-any.whl
Installing collected packages: tabulate
Successfully installed tabulate-0.8.9
You are using pip version 18.1, however version 21.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
+ cd ..
+ cat
+ cat
+ cd ve_2
+ tabulate ../ve_1/test.csv
----------
name,value
"a",1.0
"b",0.1
"a",0.2
----------
+ pyenv which python
/home/pcoccoli/.pyenv/versions/ve_2/bin/python
+ pyenv which pip
/home/pcoccoli/.pyenv/versions/ve_2/bin/pip
+ pip show tabulate
Name: tabulate
Version: 0.8.9
Summary: Pretty-print tabular data
Home-page: https://github.com/astanin/python-tabulate
Author: Sergey Astanin
Author-email: s.astanin@gmail.com
License: MIT
Location: /home/pcoccoli/.pyenv/versions/3.6.8/envs/ve_2/lib/python3.6/site-packages
Requires: 
Required-by: 
+ python tab.py ../ve_1/test.csv
Traceback (most recent call last):
  File "tab.py", line 4, in <module>
    from tabulate import tabulate
ModuleNotFoundError: No module named 'tabulate'
```

**Comment by native-api** [comment] 2021-05-06 16:11
No diagnostic info provided for the failing Pyenv invocation as required by the template issue.

**Comment by native-api** [comment] 2021-05-06 16:15
From what little I can see, you cannot `pyenv local` virtualenvs, you rather need to activate them, unless you have enabled the auto activation feature.

**Comment by native-api** [comment] 2021-05-17 06:43
Duplicate of https://github.com/pyenv/pyenv/issues/1807

**Closed by native-api** 2021-05-17 06:43 UTC
