### ISSUE TITLE
pyenv fails to find system gcc when install 3.6.0 (possible anaconda problem?)

### ISSUE THREAD

**Issue by natfarleydev** [pyenv/pyenv#843] opened 2017-02-27 17:30 UTC
I believe pyenv may be interfering with it's own access to `gcc`, and consequently not finding it when it needs it. E.g.

I run
```bash
$ pyenv install 3.6.0
```
and I get
```
Installing Python-3.6.0...

BUILD FAILED (Fedora 24 using python-build 1.0.8)

Inspect or clean up the working tree at /tmp/python-build.20170227172216.590403
Results logged to /tmp/python-build.20170227172216.590403.log

Last 10 log lines:
checking for --enable-universalsdk... no
checking for --with-universal-archs... no
checking MACHDEP... linux
checking for --without-gcc... no
checking for --with-icc... no
checking for gcc... gcc
checking whether the C compiler works... no
configure: error: in `/tmp/python-build.20170227172216.590403/Python-3.6.0':
configure: error: C compiler cannot create executables
See `config.log' for more details
```

The full config log can be seen here: https://gist.github.com/nasfarley88/0b558279182ec9e54ef2704e2bfb1be1

**Comment by Samureus** [comment] 2017-03-26 05:24
Sorry for the delay, I just merged #876 and ran

```
$ pyenv which gcc
pyenv: gcc: command not found
```
after installing both anaconda2-4.3.1 and anaconda3-4.3.1, then tried installing 3.6.0 and was able to finish the compilation without issues. I believe it might be related to that particular version of anaconda (anaconda3-4.1.1). Could you please try running

`$ pyenv whence gcc
` 
and let me know the output? Or you could check if there is a `gcc` executable inside

`$ ls `pyenv root`/versions/anaconda3-4.3.1/bin`

Another option, if you can:

1. Uninstall anaconda3-4.1.1
2. Install anaconda3-4.3.0
3. Try installing 3.6.0 again.

Checking the changelog at https://docs.continuum.io/anaconda/changelog, conda-build is no longer included with 4.3.0, maybe that might fix it.

**Comment by yyuu** [comment] 2017-03-27 02:49
I suspect some of dependency of Anaconda installed `gcc` and its toolchain into Anaconda's prefix. And, `gcc` shim script generated by pyenv is causing the problem.

Because `conda` may install some system executables in their prefix, we're provisioning this hook script to skip creating shim scripts for them. Adding `gcc`, `ld`, etc. to the following script may help.

https://github.com/pyenv/pyenv/blob/fe1bd3144326979451e9c7a1ec94130106722c5c/pyenv.d/rehash/conda.bash
https://github.com/pyenv/pyenv/blob/fe1bd3144326979451e9c7a1ec94130106722c5c/pyenv.d/rehash/conda.txt

**Comment by nasfarley88** [comment] 2017-03-29 07:20
@yyuu i think this is quite likely. I use anaconda to use the python version of ROOT (the main CERN analysis framework). ROOT needs a specific gcc in this case, would adding gcc to this list mean that the conda environment uses its own gcc or the system gcc?

**Comment by chaitanya11** [comment] 2018-05-04 02:10
I am also having the same problem with debian 9.4  (stretch). 
My log out put is
`Downloading Python-3.6.2.tar.xz...
-> https://www.python.org/ftp/python/3.6.2/Python-3.6.2.tar.xz
Installing Python-3.6.2...

BUILD FAILED (Debian 9.4 using python-build 1.2.4)

Inspect or clean up the working tree at /tmp/python-build.20180504073814.18538
Results logged to /tmp/python-build.20180504073814.18538.log

Last 10 log lines:
checking for --enable-universalsdk... no
checking for --with-universal-archs... no
checking MACHDEP... linux
checking for --without-gcc... no
checking for --with-icc... no
checking for gcc... gcc
checking whether the C compiler works... no
configure: error: in `/tmp/python-build.20180504073814.18538/Python-3.6.2':
configure: error: C compiler cannot create executables
See `config.log' for more details
`

config.log file data is 
`This file contains any messages produced by compilers while
running configure, to aid debugging if configure makes a mistake.

It was created by python configure 3.6, which was
generated by GNU Autoconf 2.69.  Invocation command line was

  $ ./configure --prefix=/home/river/.pyenv/versions/3.6.2 --libdir=/home/river/.pyenv/versions/3.6.2/lib

## --------- ##
## Platform. ##
## --------- ##

hostname = pandora
uname -m = x86_64
uname -r = 4.9.0-6-amd64
uname -s = Linux
uname -v = #1 SMP Debian 4.9.82-1+deb9u3 (2018-03-02)

/usr/bin/uname -p = unknown
/bin/uname -X     = unknown

/bin/arch              = unknown
/usr/bin/arch -k       = unknown
/usr/convex/getsysinfo = unknown
/usr/bin/hostinfo      = unknown
/bin/machine           = unknown
/usr/bin/oslevel       = unknown
/bin/universe          = unknown

PATH: /home/river/.pyenv/libexec
PATH: /home/river/.pyenv/plugins/python-build/bin
PATH: /home/river/.pyenv/shims
PATH: /home/river/.pyenv/bin
PATH: /home/river/.pyenv/shims
PATH: /home/river/.pyenv/bin
PATH: /home/river/.pyenv/shims
PATH: /home/river/.pyenv/bin
PATH: /usr/local/bin
PATH: /usr/bin
PATH: /bin
PATH: /usr/local/games
PATH: /usr/games


## ----------- ##
## Core tests. ##
## ----------- ##

configure:2794: checking build system type
configure:2808: result: x86_64-pc-linux-gnu
configure:2828: checking host system type
configure:2841: result: x86_64-pc-linux-gnu
configure:2871: checking for python3.6
configure:2901: result: no
configure:2871: checking for python3
configure:2887: found /usr/bin/python3
configure:2898: result: python3
configure:2998: checking for --enable-universalsdk
configure:3045: result: no
configure:3068: checking for --with-universal-archs
configure:3083: result: no
configure:3233: checking MACHDEP
configure:3442: result: linux
configure:3463: checking for --without-gcc
configure:3486: result: no
configure:3489: checking for --with-icc
configure:3509: result: no
configure:3633: checking for gcc
configure:3649: found /usr/bin/gcc
configure:3660: result: gcc
configure:3889: checking for C compiler version
configure:3898: gcc --version >&5
gcc (Debian 6.3.0-18+deb9u1) 6.3.0 20170516
Copyright (C) 2016 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

configure:3909: $? = 0
configure:3898: gcc -v >&5
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/6/lto-wrapper
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Debian 6.3.0-18+deb9u1' --with-bugurl=file:///usr/share/doc/gcc-6/README.Bugs --enable-languages=c,ada,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-6 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin --enable-default-pie --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-6-amd64/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-6-amd64 --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-6-amd64 --with-arch-directory=amd64 --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --with-target-system-zlib --enable-objc-gc=auto --enable-multiarch --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 6.3.0 20170516 (Debian 6.3.0-18+deb9u1) 
configure:3909: $? = 0
configure:3898: gcc -V >&5
gcc: error: unrecognized command line option '-V'
gcc: fatal error: no input files
compilation terminated.
configure:3909: $? = 1
configure:3898: gcc -qversion >&5
gcc: error: unrecognized command line option '-qversion'; did you mean '--version'?
gcc: fatal error: no input files
compilation terminated.
configure:3909: $? = 1
configure:3929: checking whether the C compiler works
configure:3951: gcc -m32  -I/home/river/.pyenv/versions/3.6.2/include  -L/home/river/.pyenv/versions/3.6.2/lib -m32 conftest.c  >&5
/usr/bin/ld: cannot find Scrt1.o: No such file or directory
/usr/bin/ld: cannot find crti.o: No such file or directory
/usr/bin/ld: skipping incompatible /usr/lib/gcc/x86_64-linux-gnu/6/libgcc.a when searching for -lgcc
/usr/bin/ld: cannot find -lgcc
/usr/bin/ld: skipping incompatible /usr/lib/gcc/x86_64-linux-gnu/6/libgcc_s.so.1 when searching for libgcc_s.so.1
/usr/bin/ld: cannot find libgcc_s.so.1
/usr/bin/ld: skipping incompatible /usr/lib/gcc/x86_64-linux-gnu/6/libgcc.a when searching for -lgcc
/usr/bin/ld: cannot find -lgcc
collect2: error: ld returned 1 exit status
configure:3955: $? = 1
configure:3993: result: no
configure: failed program was:
| /* confdefs.h */
| #define _GNU_SOURCE 1
| #define _NETBSD_SOURCE 1
| #define __BSD_VISIBLE 1
| #define _BSD_TYPES 1
| #define _DARWIN_C_SOURCE 1
| #define _XOPEN_SOURCE 700
| #define _XOPEN_SOURCE_EXTENDED 1
| #define _POSIX_C_SOURCE 200809L
| /* end confdefs.h.  */
| 
| int
| main ()
| {
| 
|   ;
|   return 0;
| }
configure:3998: error: in `/tmp/python-build.20180504073814.18538/Python-3.6.2':
configure:4000: error: C compiler cannot create executables
See `config.log' for more details

## ---------------- ##
## Cache variables. ##
## ---------------- ##

ac_cv_build=x86_64-pc-linux-gnu
ac_cv_env_CC_set=
ac_cv_env_CC_value=
ac_cv_env_CFLAGS_set=set
ac_cv_env_CFLAGS_value='-m32 '
ac_cv_env_CPPFLAGS_set=set
ac_cv_env_CPPFLAGS_value='-I/home/river/.pyenv/versions/3.6.2/include '
ac_cv_env_CPP_set=
ac_cv_env_CPP_value=
ac_cv_env_LDFLAGS_set=set
ac_cv_env_LDFLAGS_value='-L/home/river/.pyenv/versions/3.6.2/lib -m32'
ac_cv_env_LIBS_set=
ac_cv_env_LIBS_value=
ac_cv_env_MACHDEP_set=
ac_cv_env_MACHDEP_value=
ac_cv_env_PKG_CONFIG_LIBDIR_set=
ac_cv_env_PKG_CONFIG_LIBDIR_value=
ac_cv_env_PKG_CONFIG_PATH_set=
ac_cv_env_PKG_CONFIG_PATH_value=
ac_cv_env_PKG_CONFIG_set=
ac_cv_env_PKG_CONFIG_value=
ac_cv_env_build_alias_set=
ac_cv_env_build_alias_value=
ac_cv_env_host_alias_set=
ac_cv_env_host_alias_value=
ac_cv_env_target_alias_set=
ac_cv_env_target_alias_value=
ac_cv_host=x86_64-pc-linux-gnu
ac_cv_prog_PYTHON_FOR_REGEN=python3
ac_cv_prog_ac_ct_CC=gcc

## ----------------- ##
## Output variables. ##
## ----------------- ##

ABIFLAGS=''
AR=''
ARCH_RUN_32BIT=''
ARFLAGS=''
BASECFLAGS=''
BASECPPFLAGS=''
BLDLIBRARY=''
BLDSHARED=''
BUILDEXEEXT=''
CC='gcc'
CCSHARED=''
CFLAGS='-m32 '
CFLAGSFORSHARED=''
CFLAGS_ALIASING=''
CFLAGS_NODIST=''
CONFIGURE_MACOSX_DEPLOYMENT_TARGET=''
CONFIG_ARGS=' '\''--prefix=/home/river/.pyenv/versions/3.6.2'\'' '\''--libdir=/home/river/.pyenv/versions/3.6.2/lib'\'' '\''CFLAGS=-m32 '\'' '\''LDFLAGS=-L/home/river/.pyenv/versions/3.6.2/lib -m32'\'' '\''CPPFLAGS=-I/home/river/.pyenv/versions/3.6.2/include '\'''
CPP=''
CPPFLAGS='-I/home/river/.pyenv/versions/3.6.2/include '
CXX=''
DEFS=''
DEF_MAKE_ALL_RULE=''
DEF_MAKE_RULE=''
DFLAGS=''
DLINCLDIR=''
DLLLIBRARY=''
DTRACE=''
DTRACE_HEADERS=''
DTRACE_OBJS=''
DYNLOADFILE=''
ECHO_C=''
ECHO_N='-n'
ECHO_T=''
EGREP=''
ENSUREPIP=''
EXEEXT=''
EXPORT_MACOSX_DEPLOYMENT_TARGET='#'
EXT_SUFFIX=''
FRAMEWORKALTINSTALLFIRST=''
FRAMEWORKALTINSTALLLAST=''
FRAMEWORKINSTALLAPPSPREFIX=''
FRAMEWORKINSTALLFIRST=''
FRAMEWORKINSTALLLAST=''
FRAMEWORKPYTHONW=''
FRAMEWORKUNIXTOOLSPREFIX='/home/river/.pyenv/versions/3.6.2'
GITBRANCH=''
GITTAG=''
GITVERSION=''
GNULD=''
GREP=''
HAS_GIT='no-repository'
HAVE_GETHOSTBYNAME=''
HAVE_GETHOSTBYNAME_R=''
HAVE_GETHOSTBYNAME_R_3_ARG=''
HAVE_GETHOSTBYNAME_R_5_ARG=''
HAVE_GETHOSTBYNAME_R_6_ARG=''
INSTALL_DATA=''
INSTALL_PROGRAM=''
INSTALL_SCRIPT=''
INSTSONAME=''
LDCXXSHARED=''
LDFLAGS='-L/home/river/.pyenv/versions/3.6.2/lib -m32'
LDLAST=''
LDLIBRARY=''
LDLIBRARYDIR=''
LDSHARED=''
LDVERSION=''
LIBC=''
LIBFFI_INCLUDEDIR=''
LIBM=''
LIBOBJS=''
LIBPL=''
LIBRARY=''
LIBS=''
LIBTOOL_CRUFT=''
LINKCC=''
LINKFORSHARED=''
LIPO_32BIT_FLAGS=''
LLVM_PROFDATA=''
LLVM_PROF_ERR=''
LLVM_PROF_FILE=''
LLVM_PROF_FOUND=''
LLVM_PROF_MERGER=''
LN=''
LTLIBOBJS=''
LTOFLAGS=''
MACHDEP='linux'
MACHDEP_OBJS=''
MAINCC=''
MKDIR_P=''
MULTIARCH=''
MULTIARCH_CPPFLAGS=''
NO_AS_NEEDED=''
OBJEXT=''
OPT=''
OTHER_LIBTOOL_OPT=''
PACKAGE_BUGREPORT='https://bugs.python.org/'
PACKAGE_NAME='python'
PACKAGE_STRING='python 3.6'
PACKAGE_TARNAME='python'
PACKAGE_URL=''
PACKAGE_VERSION='3.6'
PATH_SEPARATOR=':'
PGO_PROF_GEN_FLAG=''
PGO_PROF_USE_FLAG=''
PKG_CONFIG=''
PKG_CONFIG_LIBDIR=''
PKG_CONFIG_PATH=''
PLATFORM_TRIPLET=''
PY3LIBRARY=''
PYTHONFRAMEWORK=''
PYTHONFRAMEWORKDIR='no-framework'
PYTHONFRAMEWORKIDENTIFIER='org.python.python'
PYTHONFRAMEWORKINSTALLDIR=''
PYTHONFRAMEWORKPREFIX=''
PYTHON_FOR_BUILD='./$(BUILDPYTHON) -E'
PYTHON_FOR_REGEN='python3'
PY_ENABLE_SHARED=''
RANLIB=''
READELF=''
RUNSHARED=''
SED=''
SGI_ABI=''
SHELL='/bin/bash'
SHLIBS=''
SHLIB_SUFFIX=''
SOABI=''
SOVERSION='1.0'
SRCDIRS=''
TCLTK_INCLUDES=''
TCLTK_LIBS=''
THREADHEADERS=''
THREADOBJ=''
TRUE=''
UNIVERSALSDK=''
UNIVERSAL_ARCH_FLAGS=''
USE_INLINE=''
USE_THREAD_MODULE=''
VERSION='3.6'
_PYTHON_HOST_PLATFORM=''
ac_ct_AR=''
ac_ct_CC='gcc'
ac_ct_CXX=''
ac_ct_READELF=''
bindir='${exec_prefix}/bin'
build='x86_64-pc-linux-gnu'
build_alias=''
build_cpu='x86_64'
build_os='linux-gnu'
build_vendor='pc'
datadir='${datarootdir}'
datarootdir='${prefix}/share'
docdir='${datarootdir}/doc/${PACKAGE_TARNAME}'
dvidir='${docdir}'
exec_prefix='NONE'
host='x86_64-pc-linux-gnu'
host_alias=''
host_cpu='x86_64'
host_os='linux-gnu'
host_vendor='pc'
htmldir='${docdir}'
includedir='${prefix}/include'
infodir='${datarootdir}/info'
libdir='/home/river/.pyenv/versions/3.6.2/lib'
libexecdir='${exec_prefix}/libexec'
localedir='${datarootdir}/locale'
localstatedir='${prefix}/var'
mandir='${datarootdir}/man'
oldincludedir='/usr/include'
pdfdir='${docdir}'
prefix='/home/river/.pyenv/versions/3.6.2'
program_transform_name='s,x,x,'
psdir='${docdir}'
sbindir='${exec_prefix}/sbin'
sharedstatedir='${prefix}/com'
sysconfdir='${prefix}/etc'
target=''
target_alias=''
target_cpu=''
target_os=''
target_vendor=''

## ----------- ##
## confdefs.h. ##
## ----------- ##

/* confdefs.h */
#define _GNU_SOURCE 1
#define _NETBSD_SOURCE 1
#define __BSD_VISIBLE 1
#define _BSD_TYPES 1
#define _DARWIN_C_SOURCE 1
#define _XOPEN_SOURCE 700
#define _XOPEN_SOURCE_EXTENDED 1
#define _POSIX_C_SOURCE 200809L

configure: exit 77
`

Thanks in advance

**Comment by zplizzi** [comment] 2019-12-21 22:14
This is still an issue - after installing a miniconda environment, I get the following in every other environment (although I have a system gcc installed):

```
% gcc
pyenv: gcc: command not found
```

**Comment by autoferrit** [comment] 2020-06-08 17:28
I had this same issue on Manjaro (arch) on a recently installed machine, also making sure to install required dependencies.
```bash
$ uname -a
Linux ferritprime 5.6.15-1-MANJARO #1 SMP PREEMPT Wed May 27 20:38:56 UTC 2020 x86_64 GNU/Linux
```
I got this fixed by disabling, the CFLAG that I thought might speed up python that is recommended in the wiki. So I removed this
```bash
export CFLAGS="-02"
```
and just blanked it to test and i was able to install just fine.

**Comment by native-api** [comment] 2021-05-18 01:46
Duplicate of https://github.com/pyenv/pyenv/issues/1568

**Closed by native-api** 2021-05-18 01:46 UTC
Labels: impl: anaconda
