### ISSUE TITLE
Certain versions of Python will not be installed.

### ISSUE THREAD

**Issue by NakhyunKim1987** [pyenv/pyenv#2363] opened 2022-05-10 09:47 UTC
Too many issues will kill our team's development velocity, drastically.
Make sure you have checked all steps below.

### Prerequisite
[check] Make sure your problem is not listed in [the common build problems](https://github.com/pyenv/pyenv/wiki/Common-build-problems).
* [x] Make sure no duplicated issue has already been reported in [the pyenv issues](https://github.com/pyenv/pyenv/issues). You should look for closed issues, too.
* [x] Make sure you are not asking us to help solving your specific issue.
  * GitHub issues is opened mainly for development purposes. If you want to ask someone to help solving your problem, go to some community site like [Gitter](https://gitter.im/yyuu/pyenv), [StackOverflow](https://stackoverflow.com/questions/tagged/pyenv), etc.
* [x] Make sure your problem is not derived from packaging (e.g. [Homebrew](https://brew.sh)).
  * Please refer to the package documentation for the installation issues, etc.
* [x] Make sure your problem is not derived from plugins.
  * This repository is maintaining `pyenv` and the default `python-build` plugin only. Please refrain from reporting issues of other plugins here.

### Description
- [x]  Platform information (e.g. Ubuntu Linux 16.04): MacOS 12.3.1
- [ ] OS architecture (e.g. amd64):
- [x] pyenv version: 2.2.5
- [x] Python version: 3.10.2 
- [x] C Compiler information (e.g. gcc 7.3):  gcc 13.1.6
- [x] Please attach the debug trace of the failing command as a gist:

Hello.
3.10 units are installed well.
3.8.12 Installation is required.

  pyenv install 3.8.12
result : 
![스크린샷 2022-05-10 오후 6 42 34](https://user-images.githubusercontent.com/76515557/167599745-d511425c-4df5-485b-992e-7e3faa818b6f.png)

CC=`which gcc-11` pyenv install 3.8.12
result : 
![스크린샷 2022-05-10 오후 6 44 57](https://user-images.githubusercontent.com/76515557/167600214-1f8c614e-56a7-425c-8424-d0e213171639.png)

**Comment by native-api** [comment] 2022-05-10 10:48
Duplicate of #2143

**Comment by native-api** [comment] 2022-05-10 10:49
Upgrade to 2.3.0

**Closed by native-api** 2022-05-10 10:49 UTC
