### ISSUE TITLE
installing 3.6.7, pyenv, Bigsur 11.6

### ISSUE THREAD

**Issue by aondkar** [pyenv/pyenv#2080] opened 2021-09-29 18:06 UTC
BUILD FAILED (OS X 11.6 using python-build 20180424)

Inspect or clean up the working tree at /var/folders/6c/9cy_z3810xn171nys_rp88ww0000gn/T/python-build.20210929232804.620
Results logged to /var/folders/6c/9cy_z3810xn171nys_rp88ww0000gn/T/python-build.20210929232804.620.log

Last 10 log lines:
        ret = sendfile(in, out, offset, &sbytes, &sf, flags);
              ^
./Modules/posixmodule.c:10433:5: warning: code will never be executed [-Wunreachable-code]
    Py_FatalError("abort() called from Python code didn't abort!");
    ^~~~~~~~~~~~~
clang -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include   -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include   -std=c99 -Wextra -Wno-unused-result -Wno-unused-parameter -Wno-missing-field-initializers -Wstrict-prototypes   -I. -I./Include -I/usr/local/opt/readline/include -I/usr/local/opt/readline/include -I/usr/local/opt/openssl@1.1/include -I/Users/arjunondkar/.pyenv/versions/3.6.7/include  -I/usr/local/opt/readline/include -I/usr/local/opt/readline/include -I/usr/local/opt/openssl@1.1/include -I/Users/arjunondkar/.pyenv/versions/3.6.7/include   -DPy_BUILD_CORE  -c ./Modules/_codecsmodule.c -o Modules/_codecsmodule.o
1 warning and 1 error generated.
make: *** [Modules/posixmodule.o] Error 1
make: *** Waiting for unfinished jobs....
1 warning generated.
arjunondkar@Arjuns-MacBook-Pro ~ %

**Comment by native-api** [comment] 2021-09-29 18:09
Duplicate of 1737

**Closed by native-api** 2021-09-29 18:09 UTC
Labels: need-feedback
