### ISSUE TITLE
BUILD FAILED (EndeavourOS rolling using python-build 20180424)

### ISSUE THREAD

**Issue by OracleToes** [pyenv/pyenv#2244] opened 2022-02-05 08:15 UTC
Too many issues will kill our team's development velocity, drastically.
Make sure you have checked all steps below.

### Prerequisite
* [X] Make sure your problem is not listed in [the common build problems](https://github.com/pyenv/pyenv/wiki/Common-build-problems).
* [X] Make sure no duplicated issue has already been reported in [the pyenv issues](https://github.com/pyenv/pyenv/issues). You should look for closed issues, too.
* [X] Make sure you are not asking us to help solving your specific issue.
  * GitHub issues is opened mainly for development purposes. If you want to ask someone to help solving your problem, go to some community site like [Gitter](https://gitter.im/yyuu/pyenv), [StackOverflow](https://stackoverflow.com/questions/tagged/pyenv), etc.
* [X] Make sure your problem is not derived from packaging (e.g. [Homebrew](https://brew.sh)).
  * Please refer to the package documentation for the installation issues, etc.
* [X] Make sure your problem is not derived from plugins.
  * This repository is maintaining `pyenv` and the default `python-build` plugin only. Please refrain from reporting issues of other plugins here.

### Description
- [X] Platform information (e.g. Ubuntu Linux 16.04): EndeavourOS (rolling release) (BUILD_ID=2021.08.27) (Arch)
- [X OS architecture (e.g. amd64): x86_64
- [X] pyenv version: 2.2.4
- [X] Python version: 3.10.2
- [X] C Compiler information (e.g. gcc 7.3): gcc (GCC) 11.1.0
- [X] Please attach the debug trace of the failing command as a gist:
  * Run `env PYENV_DEBUG=1 <faulty command> 2>&1 | tee trace.log` and attach `trace.log`. E.g. if you have a problem with installing Python, run `env PYENV_DEBUG=1 pyenv install -v <version> 2>&1 | tee trace.log` (note the `-v` option to `pyenv install`).
[trace.log](https://github.com/pyenv/pyenv/files/8007623/trace.log)
[trace.log](https://github.com/pyenv/pyenv/files/8015956/trace.log) with -v

I am attempting to install Python 3.7.12 with the command `pyenv install 3.7.12`
I get the build error: BUILD FAILED (EndeavourOS rolling using python-build 20180424)
I have attached the trace log, if I can provide any more information to help solve the issue, please let me know.
This is the same as issue #1206 which is closed, but no fix was mentioned.

**Comment by cpallapolu** [comment] 2022-02-05 19:46
I am also having similar issue. 

Platform information (e.g. Ubuntu Linux 16.04): macOS Monterey v12.2 Intel Processor
pyenv v2.2.4
Python version: 3.9.1 (trying to upgrade to v3.10.2 installed 3.9.1 using pyenv)
C Compiler information (e.g. gcc 7.3): Apple clang version 13.0.0 (clang-1300.0.29.3) Target: x86_64-apple-darwin21.3.0

[trace.log](https://github.com/pyenv/pyenv/files/8008782/trace.log)

**Comment by native-api** [comment] 2022-02-07 12:46
@OracleToes Looks like you didn't supply `-v` as instructed so I can't see the build part.

**Comment by native-api** [comment] 2022-02-07 12:46
@cpallapolu
```
configure: error: cannot compute sizeof (size_t)
See `config.log' for more details
```

**Comment by cpallapolu** [comment] 2022-02-07 13:01
@native-api 

Here is the [config.log](https://github.com/pyenv/pyenv/files/8015369/config.log).

These are the steps I followed:
- `softwareupdate --all --install --force`
- `xcode-select --install`
- `pyenv install 3.10.2`

Are there any options I need to pass for the install command?

**Comment by OracleToes** [comment] 2022-02-07 14:23
Oops, here it is, I will update the original post, too  
[trace.log](https://github.com/pyenv/pyenv/files/8015953/trace.log)

**Comment by native-api** [comment] 2022-02-07 20:10
@cpallapolu From the log, I see that a number of innocent-looking Configure's test programs are being killed by the system. I've no idea why that happens. All I can say this has nothing to do with Pyenv's logic.

```
configure:7764: ./conftest
./configure: line 1967: 89699 Killed: 9               ./conftest$ac_exeext
configure:7764: $? = 137
configure: program exited with status 137
```

**Comment by native-api** [comment] 2022-02-07 20:12
@OracleToes Duplicate of https://github.com/pyenv/pyenv/issues/2236

**Closed by native-api** 2022-02-07 20:12 UTC

**Comment by native-api** [comment] 2022-02-07 20:52
@cpallapolu I've got an idea -- killing random programs is something that an antivirus would do.
