### ISSUE TITLE
Build failure for python 3.9.5-3.9.7

### ISSUE THREAD

**Issue by justinreddick** [pyenv/pyenv#2338] opened 2022-04-24 20:01 UTC
```
BUILD FAILED (OS X 12.3.1 using python-build 20180424)

Inspect or clean up the working tree at /var/folders/3y/8s5581qn36qdhjnc8pkf3jj80000gn/T/python-build.20220424135930.65914
Results logged to /var/folders/3y/8s5581qn36qdhjnc8pkf3jj80000gn/T/python-build.20220424135930.65914.log

Last 10 log lines:
checking for --with-cxx-main=<compiler>... no
checking for clang++... no
configure:

  By default, distutils will build C++ extension modules with "clang++".
  If this is not intended, then set CXX on the configure command line.
  
checking for the platform triplet based on compiler characteristics... darwin
configure: error: internal configure error for the platform triplet, please file a bug report
make: *** No targets specified and no makefile found.  Stop.
```

**Comment by native-api** [comment] 2022-04-26 00:54
Duplicate of #2143

**Closed** 2022-04-29 05:54 UTC
