### ISSUE TITLE
python2.6: error: failed to install pip via get-pip.py

### ISSUE THREAD

**Issue by ssbarnea** [pyenv/pyenv#1299] opened 2019-03-08 12:11 UTC
### Description
- MacOS 10.13
- pyenv version: 1.2.9
- [ ] Python version:
- [ ] C Compiler information (e.g. gcc 7.3): 
- [ ] Please attach verbose build log as gist
  * You can turn on verbose debug logging using by setting `PYENV_DEBUG=1`, e.g. `env PYENV_DEBUG=1 pyenv install -v 3.6.4`

It seems that is no longer possible to install python2.6.x on MacOS because get-pip.py fails to install and I suspect this happens on any machine that has IPv6 enabled.

If someone wonders why python2.6 may be needed by someone in 2019, remember that there are few tools that do need to to test compatibility with ancient python versions which may be runnign on enbedded devices, such example ansible.

```
changing mode of /Users/ssbarnea/.pyenv/versions/2.6.9/lib/python2.6/lib-dynload/_IBCarbon.so to 755
Installing pip from https://bootstrap.pypa.io/2.6/get-pip.py...
changing mode of /Users/ssbarnea/.pyenv/versions/2.6.9/lib/python2.6/lib-dynload/_App.so to 755
changing mode of /Users/ssbarnea/.pyenv/versions/2.6.9/lib/python2.6/lib-dynload/resource.so to 755
changing mode of /Users/ssbarnea/.pyenv/versions/2.6.9/lib/python2.6/lib-dynload/_csv.so to 755
changing mode of /Users/ssbarnea/.pyenv/versions/2.6.9/lib/python2.6/lib-dynload/_Launch.so to 755
changing mode of /Users/ssbarnea/.pyenv/versions/2.6.9/lib/python2.6/lib-dynload/operator.so to 755
changing mode of /Users/ssbarnea/.pyenv/versions/2.6.9/lib/python2.6/lib-dynload/_functools.so to 755
changing mode of /Users/ssbarnea/.pyenv/versions/2.6.9/lib/python2.6/lib-dynload/_Menu.so to 755
changing mode of /Users/ssbarnea/.pyenv/versions/2.6.9/lib/python2.6/lib-dynload/_Dlg.so to 755
changing mode of /Users/ssbarnea/.pyenv/versions/2.6.9/lib/python2.6/lib-dynload/ to 755
running install_scripts
copying build/scripts-2.6/idle -> /Users/ssbarnea/.pyenv/versions/2.6.9/bin
copying build/scripts-2.6/2to3 -> /Users/ssbarnea/.pyenv/versions/2.6.9/bin
copying build/scripts-2.6/pydoc -> /Users/ssbarnea/.pyenv/versions/2.6.9/bin
copying build/scripts-2.6/smtpd.py -> /Users/ssbarnea/.pyenv/versions/2.6.9/bin
changing mode of /Users/ssbarnea/.pyenv/versions/2.6.9/bin/idle to 755
changing mode of /Users/ssbarnea/.pyenv/versions/2.6.9/bin/2to3 to 755
changing mode of /Users/ssbarnea/.pyenv/versions/2.6.9/bin/pydoc to 755
changing mode of /Users/ssbarnea/.pyenv/versions/2.6.9/bin/smtpd.py to 755
running install_egg_info
Writing /Users/ssbarnea/.pyenv/versions/2.6.9/lib/python2.6/lib-dynload/Python-2.6.9-py2.6.egg-info
if test -f /Users/ssbarnea/.pyenv/versions/2.6.9/bin/python -o -h /Users/ssbarnea/.pyenv/versions/2.6.9/bin/python; \
	then rm -f /Users/ssbarnea/.pyenv/versions/2.6.9/bin/python; \
	else true; \
	fi
(cd /Users/ssbarnea/.pyenv/versions/2.6.9/bin; ln python2.6 python)
rm -f /Users/ssbarnea/.pyenv/versions/2.6.9/bin/python-config
(cd /Users/ssbarnea/.pyenv/versions/2.6.9/bin; ln -s python2.6-config python-config)
Creating directory /Users/ssbarnea/.pyenv/versions/2.6.9/share/man
Creating directory /Users/ssbarnea/.pyenv/versions/2.6.9/share/man/man1
/usr/local/bin/ginstall -c -m 644 ./Misc/python.man \
		/Users/ssbarnea/.pyenv/versions/2.6.9/share/man/man1/python.1
Traceback (most recent call last):
  File "get-pip.py", line 22123, in <module>
    main()
  File "get-pip.py", line 194, in main
    bootstrap(tmpdir=tmpdir)
  File "get-pip.py", line 82, in bootstrap
    import pip
  File "/var/folders/3q/pc1jcyjj3qqbj6_x7n4kbtqw0000gn/T/tmp8FAs3X/pip.zip/pip/__init__.py", line 43, in <module>
  File "/var/folders/3q/pc1jcyjj3qqbj6_x7n4kbtqw0000gn/T/tmp8FAs3X/pip.zip/pip/utils/__init__.py", line 22, in <module>
  File "/var/folders/3q/pc1jcyjj3qqbj6_x7n4kbtqw0000gn/T/tmp8FAs3X/pip.zip/pip/compat/__init__.py", line 24, in <module>
  File "/var/folders/3q/pc1jcyjj3qqbj6_x7n4kbtqw0000gn/T/tmp8FAs3X/pip.zip/pip/_vendor/ipaddress.py", line 2392, in <module>
  File "/var/folders/3q/pc1jcyjj3qqbj6_x7n4kbtqw0000gn/T/tmp8FAs3X/pip.zip/pip/_vendor/ipaddress.py", line 2394, in _IPv6Constants
  File "/var/folders/3q/pc1jcyjj3qqbj6_x7n4kbtqw0000gn/T/tmp8FAs3X/pip.zip/pip/_vendor/ipaddress.py", line 2346, in __init__
  File "/var/folders/3q/pc1jcyjj3qqbj6_x7n4kbtqw0000gn/T/tmp8FAs3X/pip.zip/pip/_vendor/ipaddress.py", line 2028, in __init__
  File "/var/folders/3q/pc1jcyjj3qqbj6_x7n4kbtqw0000gn/T/tmp8FAs3X/pip.zip/pip/_vendor/ipaddress.py", line 542, in _check_int_address
pip._vendor.ipaddress.AddressValueError: 338288524927261089654018896841347694592 (>= 2**128) is not permitted as an IPv6 address
error: failed to install pip via get-pip.py

BUILD FAILED (OS X 10.14.3 using python-build 20180424)
```

**Comment by chrahunt** [comment] 2019-03-17 19:07
Is there a corresponding upstream bug in get-pip or pip that corresponds to this issue?

**Comment by aaugustin** [comment] 2019-06-14 08:22
I believe this is a duplicate of #1127.

**Closed** 2021-05-07 17:07 UTC
Labels: area: build, impl: cpython, os: macOS
