### ISSUE TITLE
Long README does not contain anything about how to get started using this

### ISSUE THREAD

**Issue by alper** [pyenv/pyenv#1677] opened 2020-08-13 08:20 UTC
I've been recommended to use `pyenv` but skimming the README does not give any guidelines how to do this. There is a lot of other stuff on there which makes me think this is not the tool for me.

**Comment by alper** [comment] 2020-08-13 10:52
I'm reading this: https://realpython.com/intro-to-pyenv/#working-with-multiple-environments

Which is better but still not great.

**Comment by sjvrijn** [comment] 2020-08-25 21:10
I found the same article today too. It's too long for a 'quick start guide', but the section(s) you reference definitely seem to be the most complete guide out there. #1470 also complains about this, and I was about to open a similar issue.

Simplest solution: refer to the realpython intro as an introduction/getting started guide

Better solution: include some actual 'getting started' information, either in the wiki or separately on e.g. readthedocs.io.

Do any of the project devs have a clear preference?

**Comment by alper** [comment] 2020-08-27 11:16
Yeah, let's do something here to make this better.

**Comment by sjvrijn** [comment] 2020-09-11 21:23
I've started a `Quickstart.md` in my fork, my plan is to write a short comprehensive intro with the topics/layout below. If anyone has any remarks or wants to help, let me know!

## Installing Python Versions

- how to find what can be installed
- how to install
- how to see what is installed
- how to uninstall


## Managing the global Python: `pyenv global`

- how to see which python version is active
- how to set a global python


## Managing a 'local' Python: `pyenv local`

- how to set a local python version
  - pyenv local
  - .pyenv-version file
- re-using the same local python in different places


## Virtual environments: `pyenv virtualenv`

- how to create a pyenv virtualenv
- how to directly (de)activate a virtualenv
- how to combine pyenv global/local with virtual environments

**Comment by alper** [comment] 2020-09-13 09:19
I created a beginning Quickstart with what I consider to be a quickstart. The outline you have here is a lot more than that.

**Comment by sjvrijn** [comment] 2020-09-14 09:02
I guess it _is_ a bit much... but my goal is to introduce `pyenv local`, preferably logically by opposing it to `pyenv global`, and ideally in combination with virtual environments. That has been the most powerful feature of pyenv to me at least.

**Comment by native-api** [comment] 2020-09-14 15:31
Huh? [Choosing the Python version](https://github.com/pyenv/pyenv#choosing-the-python-version) introduces all the ways to switch between versions, including `local` and `global`.

**Comment by alper** [comment] 2020-09-14 15:46
@sjvrijn I'm fine if you want to add a section about virtual environments but since that requires a plugin… for me it's too much. For me pyenv does the job of providing a python version. For the job of virtualenv management we use Pipenv but I can imagine tons of other tools that do that as well.

**Comment by alper** [comment] 2020-09-14 15:47
@native-api That is written in such a way as to be mostly useless for beginners.

I'm proposing something along these lines: https://github.com/sjvrijn/pyenv/blob/master/Quickstart.md

**Comment by native-api** [comment] 2020-09-14 15:56
@alper I understood it just fine when I first learned Pyenv in order to answer https://stackoverflow.com/questions/40718770/pytest-running-with-another-version-of-python/40720333#40720333.

Since then, I've seen so many people making a mess of pyenv+virtualenv+system Python and complaining about weird errors I'd say it's imperative to read about Pyenv's workings to understand what you are doing -- there are just too many ways in which think can break if you don't.

**Comment by sjvrijn** [comment] 2020-09-14 21:35
My experience as a new user looking for an environment manager on Linux seems to be different then:
- @alper I installed using https://github.com/pyenv/pyenv-installer which automatically installs that too, so I didn't really realize that the virtualenv requires a plugin. The installer also recommends 3 lines to add to your `.bashrc` file to initialize and enable pyenv. You're right that the virtualenv stuff should probably be left out then, although I would recommend the installer as very user-friendly.
- @native-api I completely agree that there can be a lot of issues, but when I was looking for simple instructions of using `pyenv`, the "how does it work in the background" section wasn't the place I looked. You're right that the information is there, but it's a bit hidden among the text. The [realpython article](https://realpython.com/intro-to-pyenv/#working-with-multiple-environments) was much more what I was looking for.

**Comment by native-api** [comment] 2020-09-14 23:23
@sjvrijn The problem is, whatever instructions are added, they must be formulated in a way that doesn't duplicate other sections -- or they will be prone to getting out of sync with them.

I can imagine a "Quick Start" section with text like:

_"After installing Pyenv and adding an alternative Python installation as per the "Installing" section above, you can now switch to that installation in one of the ways described in the "Choosing the Python version" section. After that, Python-related commands without a path (`python`, `pip` etc as well as appropriate `pythonX`, `pythonX.Y` etc) will now be invoking executables from the selected installation.

See the "How it Works" chapter to learn how exactly that is achieved to predict the outcome of other possible actions and well as understand how this magic would interact with other environment customizations (like virtual environments)."_

**Comment by sjvrijn** [comment] 2020-09-15 13:43
@native-api I would not expect the most basic/fundamental commands (install/global/local) to change so frequently for that to be a bigger issue than the currently opaque instructions. I do agree that it is another argument to make any kind of quickstart as short and minimal as possible, so definitely smaller than what I proposed earlier.

I'm unsure about your proposed "Quick Start" section: I still feel that the "Choosing the Python version" is more focused on how it works than on instructing new users. Each point listed there describes where each version is found, but not how that is intended to be used. Additionally, to find out the command syntax, you're referred to the generic reference documentation in [COMMANDS.md](https://github.com/pyenv/pyenv/blob/master/COMMANDS.md) which does not have such an explanation as a goal either.

That kind of explanation: "**how and when** would you use each (main) available command?" is what I'm trying to say is missing atm. I hope that makes a bit more sense now.

**Comment by native-api** [comment] 2020-09-15 19:17
I have _no_ idea "how and when I would use each (main) command". I just pick whatever best fits my current task.

However, ther must be use cases that every option was created for. So if you feel adventurous, go ahead, there must be traces in the commit and/or ticket/PR history. That would be a great addition to the "Choosing..." section in particular.

**Comment by alper** [comment] 2020-09-16 08:50
I don't understand how this is a subject of debate. I'm a pretty expert python user and if I have this problem, I can be sure that lots of other people also have it.

**Comment by sjvrijn** [comment] 2020-09-16 09:31
> [...] I just pick whatever best fits my current task.

@native-api That's exactly what I meant by "how and when you would use a command" 🙂 Glad to hear you too see the use of linking commands with typical/intended use cases.

**Comment by native-api** [comment] 2021-05-06 22:01
I can envision a "quick start" section at the start of the README. But to avoid duplication, it'll have to heavily delegate to other sections. I.e.:
* Install Pyenv as per Install section
* Install an additional Python version as per Installing Python versions (which should probably be a separate section -- currentlym it's under "basic Git checkout")
* Switch to it as per Choosing the Python Version
* Enjoy!

**Comment by matta** [comment] 2022-01-10 23:57
FWIW I landed here because I couldn't figure pyenv out, after having successfully used rbenv.

The incantation I was missing was `pyenv install -l`.  I think the rbenv install instructions covers this well -> https://github.com/rbenv/rbenv#installing-ruby-versions.  @sjvrijn's proposed https://github.com/sjvrijn/pyenv/blob/master/Quickstart.md does too.

The current pyenv `README.md` says

> Install Python versions into `$(pyenv root)/versions`. For example, to download and install Python 2.7.8, run `pyenv install 2.7.8`

But nowhere does it explain how to get a list of available versions.

**Comment by native-api** [comment] 2022-10-30 02:29
The README has been restructured for clarity some time ago. Now I believe a separate quick start section is not needed because there are clear "Installation" and "Usage" sections with subsections for typical tasks.

`pyenv install -l` has been mentioned in the Usage section.

Is there anything else that needs to be clarified in the README?

**Comment by sjvrijn** [comment] 2022-11-06 00:05
I've taken a look, and the current README seems to solve most, if not all, of the issues I had

**Closed** 2023-02-02 13:08 UTC
Labels: type: enhancement, type: documentation, discussion
