### ISSUE TITLE
Cannot build python with PYTHON_CONFIGURE_OPTS="--enable-framework" on arm64 macOS 12.4 (Killed: 9 The Python ssl extension was not compiled)

### ISSUE THREAD

**Issue by burnpanck** [pyenv/pyenv#2392] opened 2022-06-10 11:03 UTC
### Description
- [x] Platform information (e.g. Ubuntu Linux 16.04): macOS 12.4
- [x] OS architecture (e.g. amd64): arm64
- [x] pyenv version: 2.3.1 (latest homebrew)
- [x] Python version: 3.10.5 (also tested earlier 3.10.x as well as 3.9.9 - same effect)
- [x] C Compiler information (e.g. gcc 7.3): Apple clang version 13.1.6 (latest release - remove and reinstall was done)
- [x] Please attach the debug trace of the failing command as a gist: [trace.log](https://gist.github.com/burnpanck/78f827ffe12d8f7462975b3d7f94bec1#file-trace-log)

### macOS specific information
 - This is a mac with M1 processor, latest macOS, latest homebrew, latest pyenv, latest xcode, latest dependencies (as available from the standard sources)
 - All suggested dependencies installed via homebrew.
 - There is just a single homebrew in the standard location (`/opt/homebrew`), which is arm64 / not rosetta.
 - There is a homebrew install of `binutils`, so `AR=/usr/bin/ar` seems to be needed.
 - There are also homebrew installs of `gcc` and `llvm`, which shouldn't infer with the build (no CC/CXX set).

The build fails with the well-known "ssl extension was not compiled", see below.
The correct SSL (v 1.1) was installed however, adding suitable `CPPFLAGS` etc. doesn't seem to help
(also, python-build explicitly states that it found that homebrew openssl).
Interestingly, building without `PYTHON_CONFIGURE_OPTS="--enable-framework"` succeeds.
Furthermore, in the build-tree, I do find a `build/lib.macosx-12.4-arm64-3.10/_ssl.cpython-310-darwin.so`.

```
~ AR=/usr/bin/ar PYTHON_CONFIGURE_OPTS="--enable-framework" pyenv install 3.10.5
python-build: use openssl@1.1 from homebrew
python-build: use readline from homebrew
Installing Python-3.10.5...
python-build: use tcl-tk from homebrew
python-build: use readline from homebrew
python-build: use zlib from xcode sdk
/opt/homebrew/Cellar/pyenv/HEAD-9b91641/plugins/python-build/bin/python-build: line 1710: 28167 Killed: 9               "$PYTHON_BIN" -c "import $1" > /dev/null 2>&1
WARNING: The Python bz2 extension was not compiled. Missing the bzip2 lib?
/opt/homebrew/Cellar/pyenv/HEAD-9b91641/plugins/python-build/bin/python-build: line 1710: 28168 Killed: 9               "$PYTHON_BIN" -c "import $1" > /dev/null 2>&1
WARNING: The Python curses extension was not compiled. Missing the ncurses lib?
/opt/homebrew/Cellar/pyenv/HEAD-9b91641/plugins/python-build/bin/python-build: line 1710: 28172 Killed: 9               "$PYTHON_BIN" -c "import $1" > /dev/null 2>&1
WARNING: The Python ctypes extension was not compiled. Missing the libffi lib?
/opt/homebrew/Cellar/pyenv/HEAD-9b91641/plugins/python-build/bin/python-build: line 1710: 28173 Killed: 9               "$PYTHON_BIN" -c "import $1" > /dev/null 2>&1
WARNING: The Python readline extension was not compiled. Missing the GNU readline lib?
/opt/homebrew/Cellar/pyenv/HEAD-9b91641/plugins/python-build/bin/python-build: line 1719: 28174 Killed: 9               "$PYTHON_BIN" -c "import $1" > /dev/null 2>&1
ERROR: The Python ssl extension was not compiled. Missing the OpenSSL lib?

Please consult to the Wiki page to fix the problem.
https://github.com/pyenv/pyenv/wiki/Common-build-problems


BUILD FAILED (OS X 12.4 using python-build 20180424)

Inspect or clean up the working tree at /var/folders/rj/r7m1dyh939v4ghqj4s1v7kjh0000gn/T/python-build.20220610122151.13693
Results logged to /var/folders/rj/r7m1dyh939v4ghqj4s1v7kjh0000gn/T/python-build.20220610122151.13693.log

Last 10 log lines:
		DYLD_FRAMEWORK_PATH=/var/folders/rj/r7m1dyh939v4ghqj4s1v7kjh0000gn/T/python-build.20220610122151.13693/Python-3.10.5 ./python.exe -E -m ensurepip \
			$ensurepip --root=/ ; \
	fi
Looking in links: /var/folders/rj/r7m1dyh939v4ghqj4s1v7kjh0000gn/T/tmpl7ml5297
Processing /private/var/folders/rj/r7m1dyh939v4ghqj4s1v7kjh0000gn/T/tmpl7ml5297/setuptools-58.1.0-py3-none-any.whl
Processing /private/var/folders/rj/r7m1dyh939v4ghqj4s1v7kjh0000gn/T/tmpl7ml5297/pip-22.0.4-py3-none-any.whl
Installing collected packages: setuptools, pip
  WARNING: The scripts pip3 and pip3.10 are installed in '/Users/yves/.pyenv/versions/3.10.5/Library/Frameworks/Python.framework/Versions/3.10/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
Successfully installed pip-22.0.4 setuptools-58.1.0
```

**Comment by native-api** [comment] 2022-06-10 11:08
Looks like a duplicate of https://github.com/pyenv/pyenv/issues/2248

**Comment by burnpanck** [comment] 2022-06-10 11:12
Huh, never found that. I do not have an anti-virus system though... Any clues how to investigate that?

**Comment by native-api** [comment] 2022-06-10 11:20
MacOS has a bult-in one called XProtect.

This appears to have info how to view its logs:

https://apple.stackexchange.com/questions/437837/xprotect-apple-claims-they-do-signature-based-antivirus-but-how-do-we-know

**Comment by burnpanck** [comment] 2022-06-10 11:44
Not sure what to make of this: `log show --predicate 'subsystem == "com.apple.xprotect"'` does indeed show something definitely related to the pyenv build:
```
2022-06-10 12:22:32.762638+0200 0x1511d3   Error       0x0                  701    0    XprotectService: [com.apple.xprotect:xprotect] File /var/folders/rj/r7m1dyh939v4ghqj4s1v7kjh0000gn/T/python-build.20220610122151.13693/Python-3.10.5/python.exe failed on loadCmd /Users/yves/.pyenv/versions/3.10.5/Library/Frameworks/Python.framework/Versions/3.10/Python (loadCmd resolved to: (path not found), bundleURL: (null))
2022-06-10 12:48:01.286704+0200 0x15b880   Error       0x0                  701    0    XprotectService: [com.apple.xprotect:xprotect] File /var/folders/rj/r7m1dyh939v4ghqj4s1v7kjh0000gn/T/python-build.20220610124719.29306/Python-3.9.9/python.exe failed on loadCmd /Users/yves/.pyenv/versions/3.9.9/Library/Frameworks/Python.framework/Versions/3.9/Python (loadCmd resolved to: (path not found), bundleURL: (null))
2022-06-10 12:50:36.178817+0200 0x162048   Error       0x0                  701    0    XprotectService: [com.apple.xprotect:xprotect] File /var/folders/rj/r7m1dyh939v4ghqj4s1v7kjh0000gn/T/python-build.20220610124958.44061/Python-3.10.5/python.exe failed on loadCmd /Users/yves/.pyenv/versions/3.10.5/Library/Frameworks/Python.framework/Versions/3.10/Python (loadCmd resolved to: (path not found), bundleURL: (null))
```
I am not too sure though that this is relevant. Taking a log trace with `Console.app` while re-running the build, I found essentially the same logs by a `XprotectService` process, as well as a number of logs by `syspolicyd` which seem related:
```
GK evaluateScanResult: 2, PST: (vuid: 5E6194A8-FE8E-4E00-A46B-F9F31DC981D4), (objid: 53816328), (team: (null)), (id: _ssl.cpython-310-darwin.so), (bundle_id: NOT_A_BUNDLE), 0, 0, 1, 0, 0, 0, 0
```
`GK` might well be short for "Gatekeeper". Now if we just would know what an `evaluateScanResult` of 2 means...

Unfortunately, I actually know very little about those protection and notarisation features within macOS. In the end, I may reluctantly give a complete re-install of homebrew a try, as suggested by the linked issues, though not today.

**Comment by native-api** [comment] 2022-06-10 11:53
https://github.com/rust-lang/cargo/issues/10060 looks like a similar issue. It suggests viewing the entire log around the appropriate moment and that the issue is the kernel/antivirus has trouble dealing with the program somehow.

Looks like it accumulates some kind of heuristic metadata on installed executables and deduces stuff on it, so reinstalling Homebrew cleans that metadata -- that's why it helps.

Anyway, you probably have Apple's support. That looks like something for them to look into to sort their antivirus out.

**Comment by burnpanck** [comment] 2022-06-11 12:16
I'm not too optimistic about getting the attention of Apple's support - I'm not even currently in the developer program.

Removing and reinstalling homebrew completely did solve the issue for me, but is hardly an acceptable solution. Though it seems there is little that can be done from the pyenv side given that it's hard to even find deduce what exactly is happening. So I fear we just have to keep our fingers crossed that it doesn't pop up too often or Apple fixes the issue (judging from the linked cargo issue it really is a bug on their side).

**Closed** 2022-06-11 12:17 UTC
