### ISSUE TITLE
Can't install python 3.6 on Mac M1 Big Sur 11.2.2

### ISSUE THREAD

**Issue by m-ketan** [pyenv/pyenv#1900] opened 2021-05-05 12:14 UTC
Running into the following issue while installing python 3.6 using pyenv on my M1 Mac Big Sur 11.2.2.

```
➜  ~ arch -x86_64 pyenv install 3.6.0
python-build: use openssl from homebrew
python-build: use readline from homebrew
Downloading Python-3.6.0.tar.xz...
-> https://www.python.org/ftp/python/3.6.0/Python-3.6.0.tar.xz
Installing Python-3.6.0...
python-build: use readline from homebrew
python-build: use zlib from xcode sdk

BUILD FAILED (OS X 11.2.2 using python-build 20180424)

Inspect or clean up the working tree at /var/folders/qm/kp4ls0ds5q7gh4rtfqy4xxrr0000gn/T/python-build.20210505174006.1506
Results logged to /var/folders/qm/kp4ls0ds5q7gh4rtfqy4xxrr0000gn/T/python-build.20210505174006.1506.log

Last 10 log lines:
./Modules/posixmodule.c:8146:15: error: implicit declaration of function 'sendfile' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
        ret = sendfile(in, out, offset, &sbytes, &sf, flags);
              ^
./Modules/posixmodule.c:10340:5: warning: code will never be executed [-Wunreachable-code]
    Py_FatalError("abort() called from Python code didn't abort!");
    ^~~~~~~~~~~~~
clang -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include   -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include   -std=c99 -Wextra -Wno-unused-result -Wno-unused-parameter -Wno-missing-field-initializers   -I. -I./Include -I/opt/homebrew/opt/readline/include -I/opt/homebrew/opt/readline/include -I/opt/homebrew/opt/openssl@1.1/include -I/Users/b0223621/.pyenv/versions/3.6.0/include -I/opt/homebrew/opt/zlib/include -I/opt/homebrew/opt/bzip2/include -I/opt/homebrew/opt/readline/include -I/opt/homebrew/opt/readline/include -I/opt/homebrew/opt/openssl@1.1/include -I/Users/b0223621/.pyenv/versions/3.6.0/include -I/opt/homebrew/opt/zlib/include -I/opt/homebrew/opt/bzip2/include  -DPy_BUILD_CORE  -c ./Modules/_weakref.c -o Modules/_weakref.o
1 warning and 1 error generated.
make: *** [Modules/posixmodule.o] Error 1
make: *** Waiting for unfinished jobs....
```

**Comment by mkturner** [comment] 2021-05-05 23:10
I'm having the same issue with 3.8.9 though i did not use `arch  -x86_64`. Python 3.7.10 did compile and install successfully.

**Comment by mkturner** [comment] 2021-05-05 23:11
I'm having a similar issue with 3.8.9 though i did not use `arch -x86_64`. Python 3.7.10 did compile and install successfully.

**Comment by native-api** [comment] 2021-05-06 04:20
Duplicate of https://github.com/pyenv/pyenv/issues/1737

**Closed by native-api** 2021-05-06 04:20 UTC
