### ISSUE TITLE
pyenv badly configured message when opening windows terminal

### ISSUE THREAD

**Issue by phaberman** [pyenv/pyenv#2160] opened 2021-11-15 14:00 UTC
I have been using this pyenv for a few months now. I just started getting this message. It doesn't seem to be effecting much, but I'm not quite sure what the problem is.

```
Found pyenv, but it is badly configured. pyenv might not work for
non-interactive shells (for example, when run from a script).

To fix this message, add these lines to the '.profile' and '.zprofile' files
in your home directory:

export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init --path)"

You'll need to restart your user session for the changes to take effect.
For more info go to https://github.com/pyenv/pyenv/#installation.

```

In my home directory I do not have the '.zprofile' file it says to add the line to. I read it might be the '.zshrc' file instead, but when I open it in VSCode I get the following error:

`Unable to open '.zshrc': Unable to read file '\\wsl$\Ubuntu\home\pjhaberman\.zshrc' (Unknown (FileSystemError): Error: ELOOP: too many symbolic links encountered, open '\\wsl$\Ubuntu\home\pjhaberman\.zshrc').`

I am also not sure in which part of the file(s) I need to add these lines? At the beginning / end / does it matter?

I updated OMZ and still get the same messages upon starting the windows terminal.

My setup is nearly the same as this one on this post where they are having the same problem:[https://github.com/pyenv/pyenv/issues/2041](url)

OS: Windows 10
Ubuntu: 2004 
Python Version: 3.8.12
Pyenv Version: 2.2.0

**Comment by native-api** [comment] 2021-11-15 16:52
Duplicate of https://github.com/pyenv/pyenv/issues/2041

**Closed by native-api** 2021-11-15 16:52 UTC

**Comment by phaberman** [comment] 2021-11-16 00:11
No it's not a duplicate. Please explain why. DPOS

**Comment by phaberman** [comment] 2021-11-16 00:12
Please explain or don't close it.

**Comment by native-api** [comment] 2021-11-16 00:15
The message comes from OhMyZsh so Pyenv has nothing to do with it. The linked ticket has advice on possible action.
