### ISSUE TITLE
non-global version taken for "pipenv --three"

### ISSUE THREAD

**Issue by ezeeyahoo** [pyenv/pyenv#1106] opened 2018-02-24 19:53 UTC
Non-global version of python used to create virtual environment
```
eshant@EMacBookPro:~/Dev/test|⇒  pyenv which python
/Users/eshant/.pyenv/versions/3.6.4/bin/python

eshant@EMacBookPro:~/Dev/test|⇒  pipenv --three
Creating a virtualenv for this project…
Using /Users/eshant/.pyenv/versions/anaconda3-5.0.1/bin/python3 to create virtualenv…
⠋^Environment creation aborted.

eshant@EMacBookPro:~/Dev/test|⇒  pipenv --python 3
Creating a virtualenv for this project…
Using /Users/eshant/.pyenv/versions/anaconda3-5.0.1/bin/python3 to create virtualenv…
⠋^Environment creation aborted.

```

##### Describe your environment

1. OS Type: macOS 10.13
1. Python version: `$ python -V`: Python 3.6.4
1. Pipenv version: `$ pipenv --version`: pipenv, version 10.1.0

##### Expected result

pipenv should have used `/Users/eshant/.pyenv/versions/3.6.4/bin/python` for creating venv

##### Actual result

using anaconda's python

##### Steps to replicate

```
brew install pyenv
pyenv install anaconda3-5.0.1
pyenv install 3.6.4
pyenv global 3.6.4
pyenv rehash
eval "$(pyenv init -)"
pip/pipsi install pipenv
mkdir test && cd test
pipenv --three
```

**Comment by joshfriend** [comment] 2018-02-25 02:29
duplicate of https://github.com/pypa/pipenv/issues/1489

**Closed by joshfriend** 2018-02-25 02:29 UTC
