### ISSUE TITLE
pyenv install failes on macOS 13.4 

### ISSUE THREAD

**Issue by netgitdom** [pyenv/pyenv#2727] opened 2023-06-18 13:59 UTC
### Description
- [x] Platform information: Apple MacBook Air M1 13.4 (22F66)
- [x] OS architecture: Apple Silicon (M1)
- [x] pyenv version: 2.3.20 (installed via brew)
- [x] Python version: 3.11.4

I tried installing another Python Version on my Apple Silicon M1 besides the system wide 3.11.4. This failed through the building process. If I read the error message correct, is peen trying to run the windows version python.exe file ?

```pyenv install 3.8
python-build: use openssl@1.1 from homebrew
python-build: use readline from homebrew
Downloading Python-3.8.17.tar.xz...
-> https://www.python.org/ftp/python/3.8.17/Python-3.8.17.tar.xz
Installing Python-3.8.17...
python-build: use tcl-tk from homebrew
python-build: use readline from homebrew
python-build: use zlib from xcode sdk

BUILD FAILED (OS X 13.4 using python-build 20180424)

Inspect or clean up the working tree at /var/folders/wg/5cqx4vtx7g94klgqsdt3bdt40000gn/T/python-build.20230618152925.3022
Results logged to /var/folders/wg/5cqx4vtx7g94klgqsdt3bdt40000gn/T/python-build.20230618152925.3022.log

Last 10 log lines:
  File "/private/var/folders/wg/5cqx4vtx7g94klgqsdt3bdt40000gn/T/python-build.20230618152925.3022/Python-3.8.17/Lib/ensurepip/__init__.py", line 209, in _main
    return _bootstrap(
  File "/private/var/folders/wg/5cqx4vtx7g94klgqsdt3bdt40000gn/T/python-build.20230618152925.3022/Python-3.8.17/Lib/ensurepip/__init__.py", line 128, in _bootstrap
    return _run_pip(args + [p[0] for p in _PROJECTS], additional_paths)
  File "/private/var/folders/wg/5cqx4vtx7g94klgqsdt3bdt40000gn/T/python-build.20230618152925.3022/Python-3.8.17/Lib/ensurepip/__init__.py", line 37, in _run_pip
    return subprocess.run(cmd, check=True).returncode
  File "/private/var/folders/wg/5cqx4vtx7g94klgqsdt3bdt40000gn/T/python-build.20230618152925.3022/Python-3.8.17/Lib/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/private/var/folders/wg/5cqx4vtx7g94klgqsdt3bdt40000gn/T/python-build.20230618152925.3022/Python-3.8.17/python.exe', '-c', '\nimport runpy\nimport sys\nsys.path = [\'/var/folders/wg/5cqx4vtx7g94klgqsdt3bdt40000gn/T/tmpaza4ulkl/setuptools-56.0.0-py3-none-any.whl\', \'/var/folders/wg/5cqx4vtx7g94klgqsdt3bdt40000gn/T/tmpaza4ulkl/pip-23.0.1-py3-none-any.whl\'] + sys.path\nsys.argv[1:] = [\'install\', \'--no-cache-dir\', \'--no-index\', \'--find-links\', \'/var/folders/wg/5cqx4vtx7g94klgqsdt3bdt40000gn/T/tmpaza4ulkl\', \'--root\', \'/\', \'--upgrade\', \'setuptools\', \'pip\']\nrunpy.run_module("pip", run_name="__main__", alter_sys=True)\n']' died with <Signals.SIGABRT: 6>.
make: *** [install] Error 1
```

Is there something I can do or misconfigured on my side ?

I attached also the trace.log and config.log files. 
[trace.log](https://github.com/pyenv/pyenv/files/11781705/trace.log)
[config.log](https://github.com/pyenv/pyenv/files/11781706/config.log)

**Comment by native-api** [comment] 2023-06-19 22:39
Duplicate of https://github.com/pyenv/pyenv/issues/2707

**Closed by native-api** 2023-06-19 22:39 UTC

**Comment by franciscojavierarceo** [comment] 2024-01-18 15:04
for others searching for a solution, here's what worked for me:

```
arch -x86_64 pyenv install 3.x.x
```
3.x.x. is just whatever pythong version you need.

[Based on this stackoverflow comment](https://stackoverflow.com/a/76547649).

**Comment by patnir411** [comment] 2024-03-06 03:01
> for others searching for a solution, here's what worked for me:
> 
> ```
> arch -x86_64 pyenv install 3.x.x
> ```
> 
> 3.x.x. is just whatever python version you need.
> 
> [Based on this stackoverflow comment](https://stackoverflow.com/a/76547649).

Thank you for this! Seconding
