### ISSUE TITLE
Issues installing python 3.8.12 on MacOS Monterey with Apple M1 Max

### ISSUE THREAD

**Issue by eddytrang** [pyenv/pyenv#2290] opened 2022-03-23 15:50 UTC
Too many issues will kill our team's development velocity, drastically.
Make sure you have checked all steps below.

### Prerequisite
* [X ] Make sure your problem is not listed in [the common build problems](https://github.com/pyenv/pyenv/wiki/Common-build-problems).
* [X] Make sure no duplicated issue has already been reported in [the pyenv issues](https://github.com/pyenv/pyenv/issues). You should look for closed issues, too.
* [ X] Make sure you are not asking us to help solving your specific issue.
  * GitHub issues is opened mainly for development purposes. If you want to ask someone to help solving your problem, go to some community site like [Gitter](https://gitter.im/yyuu/pyenv), [StackOverflow](https://stackoverflow.com/questions/tagged/pyenv), etc.
* [X ] Make sure your problem is not derived from packaging (e.g. [Homebrew](https://brew.sh)).
  * Please refer to the package documentation for the installation issues, etc.
* [X ] Make sure your problem is not derived from plugins.
  * This repository is maintaining `pyenv` and the default `python-build` plugin only. Please refrain from reporting issues of other plugins here.

### Description
- [X ] Platform information (e.g. Ubuntu Linux 16.04): MacOS Monterey 12.2.1
- [X] OS architecture (e.g. amd64): arm64
- [X] pyenv version: 3.8.12
- [X] Python version: 2.2.5
- [X] C Compiler information (e.g. gcc 7.3): Apple clang version 13.1.6 (clang-1316.0.21.2)
Target: arm64-apple-darwin21.3.0
- [X] Please attach the debug trace of the failing command as a gist:
  * Run `env PYENV_DEBUG=1 <faulty command> 2>&1 | tee trace.log` and attach `trace.log`. E.g. if you have a problem with installing Python, run `env PYENV_DEBUG=1 pyenv install -v <version> 2>&1 | tee trace.log` (note the `-v` option to `pyenv install`).

`pyenv install 3.8.12
`

```Installing Python-3.8.12...
python-build: use readline from homebrew
python-build: use zlib from xcode sdk

BUILD FAILED (OS X 12.2.1 using python-build 20180424)

Inspect or clean up the working tree at /var/folders/ys/s6rmn6c177n8dqc2x9rl0605dh2vdy/T/python-build.20220323234324.88096
Results logged to /var/folders/ys/s6rmn6c177n8dqc2x9rl0605dh2vdy/T/python-build.20220323234324.88096.log

Last 10 log lines:
checking for --with-cxx-main=<compiler>... no
checking for clang++... no
configure:

  By default, distutils will build C++ extension modules with "clang++".
  If this is not intended, then set CXX on the configure command line.
  
checking for the platform triplet based on compiler characteristics... darwin
configure: error: internal configure error for the platform triplet, please file a bug report
make: *** No targets specified and no makefile found.  Stop.
```

[Terminal Saved Output.txt](https://github.com/pyenv/pyenv/files/8334470/Terminal.Saved.Output.txt)

**Comment by native-api** [comment] 2022-03-23 17:22
Duplicate of https://github.com/pyenv/pyenv/issues/2284

**Comment by native-api** [comment] 2022-03-23 17:23
Upgrade to 3.8.13 or backport the patch mentioned in that issue to the versions you're interesed in.

**Closed by native-api** 2022-03-23 17:23 UTC

**Comment by eddytrang** [comment] 2022-03-24 09:45
@native-api can you clarify what it means to "backport the upstream path"? Sorry, but I don't understand how to do this. Apologies in advance if the question is a simple one.

I was able to install 3.8.13, but unfortunately, I need 3.8.12.
