### ISSUE TITLE
Ignoring ensurepip failure: pip 1.5.6 requires SSL/TLS

### ISSUE THREAD

**Issue by psamim** [pyenv/pyenv#929] opened 2017-06-07 05:12 UTC
Hi,

I am on Archlinux, on installing Python 3.4.2 I get:

```
Ignoring ensurepip failure: pip 1.5.6 requires SSL/TLS
```

Thanks

**Comment by blueyed** [comment] 2017-06-07 20:09
Duplicate of https://github.com/pyenv/pyenv/issues/916?!

**Closed by blueyed** 2017-06-07 20:09 UTC

**Comment by psamim** [comment] 2017-06-08 05:56
Yes, thanks.
