### ISSUE TITLE
How can I install an x86 (Intel) version of python alongside other native ARM interpreters using pyenv?

### ISSUE THREAD

**Issue by John15321** [pyenv/pyenv#2324] opened 2022-04-13 19:43 UTC
Im on a Macbook Pro 14" with an M1 Max thus on an ARM platform. Im using native pyenv and its python interpreters. For certain reasons, I would like to install an x86/Intel version of python alongside all of my other (native ARM interpreters). Is there a way in which I can do that? Or maybe install it by itself but connect it under pyenv? Anything?

### Prerequisite
* [x] Make sure your problem is not listed in [the common build problems](https://github.com/pyenv/pyenv/wiki/Common-build-problems).
* [x] Make sure no duplicated issue has already been reported in [the pyenv issues](https://github.com/pyenv/pyenv/issues). You should look for closed issues, too.
* [x] Make sure your problem is not derived from packaging (e.g. [Homebrew](https://brew.sh)).
  * Please refer to the package documentation for the installation issues, etc.
* [x] Make sure your problem is not derived from plugins.
  * This repository is maintaining `pyenv` and the default `python-build` plugin only. Please refrain from reporting issues of other plugins here.

### Description
- [x] Platform information (e.g. Ubuntu Linux 16.04): macOS 12.3
- [x] OS architecture (e.g. amd64): arm64 (M1 Max)
- [x] pyenv version: `2.2.5`
- [x] Python version: any
- [x] C Compiler information (e.g. gcc 7.3): Apple clang version 13.1.6 (clang-1316.0.21.2)

**Comment by native-api** [comment] 2022-04-14 07:09
Pyenv itself does nothing to affect the architecture, it uses whatever there is on PATH.
The easiest way is to install two instance of Homebrew, use one by default and make a custom terminal shortcut or alias to use the other one. See e.g. https://stackoverflow.com/questions/64951024/how-can-i-run-two-isolated-installations-of-homebrew

**Comment by native-api** [comment] 2022-04-14 07:13
Duplicate of https://github.com/pyenv/pyenv/issues/1853

**Closed by native-api** 2022-04-14 07:13 UTC
