### ISSUE TITLE
pyenv shims always change PATH

### ISSUE THREAD

**Issue by AlJohri** [pyenv/pyenv#985] opened 2017-09-20 14:09 UTC
The pyenv shims for any executable change the PATH for the current process and child processes. This affects usage of any python program that starts child processes like `envdir`, `pew` and can be demonstrated using `python` itself.

The shim will prepend the `bin` of the current activated python and also the pyenv `libexec` folder. For example: `/Users/johria/.pyenv/versions/3.6.2/bin:/usr/local/Cellar/pyenv/1.1.3/libexec` will get prepended to the `PATH`.

This can most easily be demonstrated via the shim for `python` itself:

checking the current PATH:
```
$ echo "$PATH"
bin:/Users/johria/.nodenv/shims:/Users/johria/.rbenv/shims:/Users/johria/.pyenv/shims:/usr/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
```

checking the PATH modified by the pyenv shim:
```
$ python -c "import os; print(os.environ['PATH'])"
/Users/johria/.pyenv/versions/3.6.2/bin:/usr/local/Cellar/pyenv/1.1.3/libexec:bin:/Users/johria/.nodenv/shims:/Users/johria/.rbenv/shims:/Users/johria/.pyenv/shims:/usr/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
```

as you can see pyenv has changed the PATH

is there any way to allow shims to work without changing the PATH? I realize this is the root of my issues. 

cc @blueyed @yyuu

**Comment by AlJohri** [comment] 2017-09-20 14:43
FWIW, I just tried out [`asdf`](https://github.com/asdf-vm/asdf) with [`asdf-python`](https://github.com/tuvistavie/asdf-python) and for some reason their shims to do not change the PATH.

**Comment by blueyed** [comment] 2017-09-20 23:36
So it adds `/Users/johria/.pyenv/versions/3.6.2/bin` and `/usr/local/Cellar/pyenv/1.1.3/libexec`.
Do you use 2 Python versions?

I agree somehow that this would be nice to avoid.

Try looking at the output after `export PYENV_DEBUG=1` to see where it is coming from.

Maybe this?!
https://github.com/pyenv/pyenv/blob/2ebab025f7c5dcb1de07c6fc38ea13592c7df6e4/libexec/pyenv-exec#L44-L47

**Comment by AlJohri** [comment] 2017-09-20 23:52
linking relevant issues:
- https://github.com/pyenv/pyenv/issues/98
- https://github.com/pyenv/pyenv/issues/789

**Comment by blueyed** [comment] 2018-06-04 21:17
See https://github.com/pyenv/pyenv/pull/1169.

**Comment by blueyed** [comment] 2019-09-23 17:26
Duplicate of https://github.com/pyenv/pyenv/issues/789.

**Closed by blueyed** 2019-09-23 17:26 UTC
Labels: area: shims
