### ISSUE TITLE
False-positive shim error

### ISSUE THREAD

**Issue by brbsix** [pyenv/pyenv#588] opened 2016-05-03 01:36 UTC
I've got a Python [script](https://github.com/brbsix/pygmentize-addons/blob/master/pygshit) that's basically `less` and `cat` plus syntax highlighting. I was using it to view python's bash-completion script _/usr/share/bash-completion/completions/python2_ and encountered the following error:

```
/home/user/.pyenv/libexec/pyenv: line 43: cd: python: Not a directory
```

The bug is reproducible with the following command:

```
python - '/usr/share/bash-completion/completions/python2' <<EOF
pass
EOF
```

For some reason `pyenv` seems to think the file is something that it's not. The error message seems to come from the following function:

```
abs_dirname() {
  local cwd="$PWD"
  local path="$1"

  while [ -n "$path" ]; do
    cd "${path%/*}"
    local name="${path##*/}"
    path="$(resolve_link "$name" || true)"
  done

  pwd
  cd "$cwd"
}
```

Which was called by:

```
# Transfer PYENV_FILE_ARG (from shims) into PYENV_DIR.
if [ -z "${PYENV_DIR}" ]; then
  if [ -n "${PYENV_FILE_ARG}" ]; then
    if [ -L "${PYENV_FILE_ARG}" ]; then
      PYENV_DIR="$(abs_dirname "${PYENV_FILE_ARG}")"
    else
      PYENV_DIR="${PYENV_FILE_ARG%/*}"
    fi
    export PYENV_DIR
    unset PYENV_FILE_ARG
  fi
fi
```

I'm also able to reproduce the error by creating a link named `python` (or anything matching `python*` , the pattern found in `pyenv-rehash`'s `create_prototype_shim` function) and calling it. e.g.

```
touch somefile
ln -s somefile python
python /absolute/path/to/somefile
```

I realize this is not a particular common scenario, but is there any way to fix this?
##

**Comment by yyuu** [comment] 2016-05-06 00:33
I guess this the message was printed due to wrongly configured `$PATH`, as same reason as #580. Please ensure `$(pyenv root)/shims` is located before some system path (e.g. `/usr/bin`) in your `$PATH`.

**Comment by brbsix** [comment] 2016-05-06 01:08
I just installed pyenv in a clean Ubuntu 16.04 Vagrant box and am experiencing the error there as well.

This is the tail of *~/.bashrc*:

    PATH="$HOME/.pyenv/bin:$PATH"

    eval "$(pyenv init -)"
    eval "$(pyenv virtualenv-init -)"

This is `$PATH`:

    /home/vagrant/.pyenv/plugins/pyenv-virtualenv/shims:/home/vagrant/.pyenv/shims:/home/vagrant/.pyenv/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games

Issue:

    vagrant@xenial:~$ python - /usr/share/bash-completion/completions/python2 <<<pass
    /home/vagrant/.pyenv/libexec/pyenv: line 43: cd: python: Not a directory

Everything appears to be properly configured.

**Comment by lexelby** [comment] 2016-12-14 20:57
I ran into this with a script in my ~/bin directory (which is in my path).  I had something like this:

```
~/bin/thing1 -> thing2
~/bin/thing2 -> ../repos/thing2/thing2.py
```

`thing2.py` has a shebang:

`#!/usr/bin/env python`

I was getting this error (extracted from PYENV_DEBUG=1 output):

```
++ [pyenv:42] '[' -n /home/lex/bin/thing1 ']'
++ [pyenv:43] cd /home/lex/bin
++ [pyenv:44] local name=thing1
+++ [pyenv:45] resolve_link thing1
+++ [pyenv:35] /bin/readlink thing1
++ [pyenv:45] path=thing2
++ [pyenv:42] '[' -n thing2 ']'
++ [pyenv:43] cd thing2
/home/lex/.pyenv/libexec/pyenv: line 43: cd: thing2: Not a directory
```

The script ran properly though.

Making `thing1` point directly to `../repos/thing2/thing2.py` removed the spurious warning.  I guess I'm a weirdo for having multi-level symlinks for my executable?

**Comment by blueyed** [comment] 2018-09-19 08:15
Closing as duplicate of #580.

**Closed by blueyed** 2018-09-19 08:15 UTC
Labels: question
