### ISSUE TITLE
BUILD FAILED (OS X 12.0.1 using python-build 20180424)

### ISSUE THREAD

**Issue by Adeel-AA** [pyenv/pyenv#2154] opened 2021-11-08 16:41 UTC
Hey there, I'm trying to do a `pyenv install 3.7.6` and I am getting the following error:

### Description
- [x] Platform information (e.g. Ubuntu Linux 16.04): macOS Monterey 12.0.1
- [x] pyenv version: 2.2.0
- [x] Python version: 3.10.0
- [x] C Compiler information (e.g. gcc 7.3): Apple clang version 13.0.0 (clang-1300.0.29.3)

Output of: `env PYENV_DEBUG=1 pyenv install -v 3.6.4` [here](https://gist.github.com/Adeel-AA/57c19153ea46d09075ce66aba2d1cd33).

Appreciate any help, thank you in advance.

**Comment by native-api** [comment] 2021-11-08 16:45
Duplicate of https://github.com/pyenv/pyenv/issues/1737

**Closed by native-api** 2021-11-08 16:45 UTC

**Comment by boscorona** [comment] 2022-03-31 00:23
@Adeel-AA Were you able to find a solution?

**Comment by Adeel-AA** [comment] 2022-03-31 12:15
> @Adeel-AA Were you able to find a solution?

Hey, yes if I can remember correctly it was an issue with xcode. I did updated my xcode to the latest version through the app store and then did, `xcode-select --install` and it worked. Sorry I can't give you exact solution as it was a while ago and I've forgotten. I will check my config though and it might jog my memory a bit, I will get back to you. Thanks

**Comment by PatrickWestermann** [comment] 2022-04-09 21:07
> Would be great, I have the same issue.

**Comment by Misha-O** [comment] 2022-04-29 10:05
@Adeel-AA any updates ?

**Comment by Adeel-AA** [comment] 2022-04-29 13:04
So I removed xcode command line tools, installed them again and I was able to install the latest version of pyenv. For me, that's how I got it working. Sorry I can't help any further.

**Comment by vcardozob** [comment] 2022-07-24 18:06
Hi, I'm a beginner & I'm experiencing the same issue. I read somewhere that we need to install xcode app as well and not only xcode command tools for this to work. is this true?

**Comment by chadnewbry** [comment] 2023-03-08 14:27
FWIW I had this same issue when trying to install 3.8.2 and 3.6.0.

When I installed the latest version of Python (3.8.16) I didn't have a problem. 

Not really a fix per se, but might help.

**Comment by vl-kp** [comment] 2023-05-03 08:37
3.8.1-3.8.5, 3.8.9 all don't work
3.8.16 works

**Comment by franciscojavierarceo** [comment] 2024-01-23 02:51
for others searching for a solution, here's what worked for me:

```
arch -x86_64 pyenv install 3.x.x
```
3.x.x. is just whatever python version you need.

[Based on this stackoverflow comment](https://stackoverflow.com/a/76547649).
