### ISSUE TITLE
Unable to override system python on OSX

### ISSUE THREAD

**Issue by danielabar** [pyenv/pyenv#660] opened 2016-07-18 00:10 UTC
On OSX 10.11.5, that came with Python 2.7.10.

I installed pyenv with homebrew, then added the two lines recommended to .zshrc

``` shell
export PYENV_ROOT=/usr/local/var/pyenv
if which pyenv > /dev/null; then eval "$(pyenv init -)"; fi
```

Then ran `source ~/.zshrc`. Then tried to install Python 3 and use it as the global:

```
pyenv install 3.5.2
pyenv global 3.5.2
```

Then confirmed the version `pyenv which python` returns `/usr/local/var/pyenv/versions/3.5.2/bin/python`.

However, running `python -V` still shows 2.7.10. Same problem with `pyenv local 3.5.2`
##

**Comment by brbsix** [comment] 2016-07-18 01:16
Have you tried it without placing `eval` in an if-block? Also, what does your `$PATH` look like after all this?

**Comment by dropofwill** [comment] 2016-07-18 18:01
I'm actually having the same issue on OSX 10.11.15 as well (installed with Homebrew, using zshell).

```
pyenv versions
  system
* 2.7.10 (set by /Users/wpaul/.python-version)
```

and

```
pyenv which python
/usr/local/var/pyenv/versions/2.7.10/bin/python
```


Yet in the same shell:
```
python -V
Python 2.7.12
```

My `$PATH` has been polluted by RVM, but it has `pyenv` at the beginning:

`/usr/local/var/pyenv/shims:/Users/wpaul/.rvm/gems/ruby-1.9.3-p551/bin:/Users/wpaul/.rvm/gems/ruby-1.9.3-p551@global/bin:/Users/wpaul/.rvm/rubies/ruby-1.9.3-p551/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/sbin:/Users/wpaul/.rvm/bin`

**Comment by danielabar** [comment] 2016-07-18 20:26
My $PATH:

```shell
/Users/dbaron/.pyenv/shims:/Users/dbaron/.nvm/versions/node/v5.9.1/bin:/usr/local/bin:/usr/local/mysql/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/Applications/eclipse:/usr/local/heroku/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/opt/X11/bin:/Library/Ruby/Gems/2.0.0/gems/travis-1.8.0/bin
```

I'm also using zsh with oh-my-zsh, could there be some different configuration required to make this work with zsh?

**Comment by danielabar** [comment] 2016-07-18 21:55
I added `setopt shwordsplit` to .zshrc and then it started working, based on [this zsh doc](http://zsh.sourceforge.net/FAQ/zshfaq03.html).

But now even if I remove the shwordsplit option, its still working, so not entirely sure what made it start working. My .zshrc last few lines:

```shell
# added for pyenv
#To use Homebrew's directories rather than ~/.pyenv
export PYENV_ROOT="/usr/local/var/pyenv"
#To enable shims and autocompletion
if which pyenv > /dev/null; then eval "$(pyenv init -)"; fi
```

**Comment by dropofwill** [comment] 2016-07-18 22:15
Hmm, exact same result for me as well...

**Comment by danielabar** [comment] 2016-07-18 22:48
Just set it up on another machine (osx, zsh), and this  time, even without `setopt shwordsplit` it's working. The only other thing I can think of is after installing via homebrew, the instructions said to add:

```shell
export PYENV_ROOT=/usr/local/var/pyenv
```

But then changing it to use quotes may have fixed it:

```shell
export PYENV_ROOT="/usr/local/var/pyenv"
```

**Comment by d10p** [comment] 2016-08-17 20:02
First time user of pyenv & I just encountered this issue. 
On latest version of OS X (10.11.6 as of this post). pyenv 20160726. zsh

**Comment by d10p** [comment] 2016-08-17 20:10
First time user of pyenv & I just encountered this issue. 
On latest version of OS X (10.11.6 as of this post). pyenv 20160726. zsh 5.2 from homebrew.

I noticed that after opening up a terminal, my path wasn't reflecting what I set it to be in my `.zshenv` file:

`/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/d10p/.cargo/bin:~/.nvm:/usr/local/var/pyenv/shims`

But if I did an `echo $PATH` at the end of my `.zshenv`, it was giving me a different value - the one I was expecting:

`/Users/d10p/.cargo/bin:~/.nvm:/usr/local/var/pyenv/shims:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin`

I figured it must've been another file zsh was sourcing on startup that was changing my PATH. Using the [ArchLinux wiki's page on Zsh](https://wiki.archlinux.org/index.php/Zsh), I discovered a few more files that zsh will source on startup.

For me, it ended up being `/etc/zprofile` that was causing the PATH mismatch. I commented out the files contents and after that, I was getting the correct version of Python from pyenv instead of MacOS's internal version.

I'm not sure if this is the same cause affecting some of you - some of the PATHs posted here look like they should work, while the result of my `echo $PATH` when opening a terminal already showed there was an issue there.

**Comment by swils** [comment] 2016-09-22 13:20
As with d10p, with me it was caused by the `path_helper` call in `/etc/zprofile`. I solved it a little bit differenty, just by putting pyenv initialization in my local `.zshrc`.

**Comment by alex-marmot** [comment] 2016-11-11 04:34
Same issue as d10p.  I solved it by  add `eval "$(pyenv init -)"` in `.zshrc`

**Comment by IllyaMoskvin** [comment] 2017-11-21 16:30
I had a different problem, with the same symptom. For some reason, pyenv was creating `~` (tilde) directories in my home directory, and within the `versions` and `shims` folders. I fixed it by specifying the following in my `~/.bashrc`:

    # Declaring PYENV_SHELL might be unnecessary
    export PYENV_ROOT="$HOME/.pyenv"
    export PYENV_SHELL="bash"

    # To enable shims and autocompletion
    if which pyenv > /dev/null; then eval "$(pyenv init -)"; fi

Notably, don't do this, use `$HOME` instead:

    export PYENV_ROOT="~/.pyenv"

I don't know why, but macOS hates it. I'm using macOS Sierra 10.12.6, and I've run into similar problems with other version managers that required `.bashrc` changes.

**Comment by sehmaschine** [comment] 2018-03-26 06:40
I solved it with adding the pyenv paths and pyenv init within `~/.zshrc` instead of `~/.zshenv`, because `path_helper` is loaded with `etc/zprofile`. This should maybe be part of the docs (e.g. a note about `path_helper`).

**Comment by alexsabau86** [comment] 2018-04-04 12:02
Having the same issue, anyone has a fix for this? thanks!

```
Macbook-Pro-3:~ user$ pyenv versions
  system
* 2.7.6 (set by /Users/user/.python-version)
Macbook-Pro-3:~ user$ python --version
Python 2.7.10
Macbook-Pro-3:~ user$
```

**Comment by 0xdevalias** [comment] 2018-05-22 01:10
Looks like @obsoke found my problem too (https://github.com/pyenv/pyenv/issues/660#issuecomment-240532278). For reference, this was my `zprofile`:

```
⇒  cat /etc/zprofile
# system-wide environment settings for zsh(1)
if [ -x /usr/libexec/path_helper ]; then
	eval `/usr/libexec/path_helper -s`
fi
```

Based on [this StackOverflow](https://stackoverflow.com/questions/12409270/os-x-mountain-lion-how-does-path-helper-work/14101578#14101578):

> The man page for path_helper opens with:
>
>  The path_helper utility reads the contents of the files in the directories /etc/paths.d and /etc/manpaths.d and appends their contents to the PATH and MANPATH environment variables respectively.
>
> The crucial point here is that the path_helper utility is intended to add contents to an existing PATH setting, not replace them. **(And in actuality, what it really does is prepend contents**, not append them, which matters for PATH variables...)

While there wasn't much of interest in `/etc/manpaths.d`, it ALSO seems to be prepending the common system paths before all of my existing paths, which obviously messes with things:

```
/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:MYOTHERSTUFFHERE
```

The zsh startup order for sourced files is here:

* https://wiki.archlinux.org/index.php/Zsh#Startup.2FShutdown_files

This blog gives similar advice:

* http://richa.avasthi.name/blog/2015/10/fixing-your-zsh-path-after-upgrading-to-el-capitan/

The weird part though is that `zshrc` SHOULD be getting sourced after `zprofile`, so this shouldn't be an issue.. but for whatever reason, for me it is.

**Comment by bodikqlar** [comment] 2018-05-29 12:44
@IllyaMoskvin thanks buddy, you saved my day

**Comment by vaichidrewar** [comment] 2018-06-14 21:27
Adding the following command in .bashrc resolved the issue for me.
`eval "$(pyenv init -)"`

**Comment by gloryVine** [comment] 2018-11-11 21:09
@vaichidrewar 

> Adding the following command in .bashrc resolved the issue for me.
> `eval "$(pyenv init -)"`

While this results in the correct local version of Python, it messes up the system python on mac:
`$python3 -V` gives the correct version but
`$python -V` results in 'no such file or directory', whereas it should normally link to Mac's system python 2.7. Why is that?

**Comment by jonw-cogapp** [comment] 2019-01-02 13:00
I seemed to be having this issue when setting up with High Sierra. For me this seemed like a `$PATH` issue, and in my case the shims were placed in my `$HOME` directory after installing via Homebrew.

Formatting my `$PATH` variable to have this before the default bin directories solved my issues:

```
export PATH="$HOME/.pyenv/shims:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin" 
```

Hopefully this saves someone some time.

**Comment by haipengz** [comment] 2019-02-27 08:18
> I had a different problem, with the same symptom. For some reason, pyenv was creating `~` (tilde) directories in my home directory, and within the `versions` and `shims` folders. I fixed it by specifying the following in my `~/.bashrc`:
> 
> ```
> # Declaring PYENV_SHELL might be unnecessary
> export PYENV_ROOT="$HOME/.pyenv"
> export PYENV_SHELL="bash"
> 
> # To enable shims and autocompletion
> if which pyenv > /dev/null; then eval "$(pyenv init -)"; fi
> ```
> Notably, don't do this, use `$HOME` instead:
> 
> ```
> export PYENV_ROOT="~/.pyenv"
> ```
> I don't know why, but macOS hates it. I'm using macOS Sierra 10.12.6, and I've run into similar problems with other version managers that required `.bashrc` changes.

Thanks, it works for me on macOS Mojave 10.14.2.

**Comment by JavierFuentes** [comment] 2019-03-09 20:35
Maybe [my comment](https://github.com/pyenv/pyenv/issues/1159#issuecomment-471219603) in this other issue could help somebody.

**Comment by riley2012** [comment] 2019-10-24 22:53
The issue that I had was in .bash_profile: I had originally installed the system Python with 'brew install'. This added a line into .bash_profile that set the PATH to the latest location of the system Python. The line in .bash_profile, which sets the PYTHON path, runs after 'source .bashrc'. 
Later I installed pyenv, and added the eval to .bashrc to set the PATH, as recommended by pyenv.  However, since .bashrc was sourced before the PATH was modified by .bash_profile, the system Python was in the PATH ahead of pyenv's path. The fix for this is to remove the PATH modification in .bash_profile, or move it ahead of 'source .bashrc'.

**Comment by GershonHerczeg** [comment] 2020-01-16 20:25
> I had a different problem, with the same symptom. For some reason, pyenv was creating `~` (tilde) directories in my home directory, and within the `versions` and `shims` folders. I fixed it by specifying the following in my `~/.bashrc`:
> 
> ```
> # Declaring PYENV_SHELL might be unnecessary
> export PYENV_ROOT="$HOME/.pyenv"
> export PYENV_SHELL="bash"
> 
> # To enable shims and autocompletion
> if which pyenv > /dev/null; then eval "$(pyenv init -)"; fi
> ```
> 
> Notably, don't do this, use `$HOME` instead:
> 
> ```
> export PYENV_ROOT="~/.pyenv"
> ```
> 
> I don't know why, but macOS hates it. I'm using macOS Sierra 10.12.6, and I've run into similar problems with other version managers that required `.bashrc` changes.

Thank you! This solved it for me..

**Comment by joshfriend** [comment] 2020-01-16 21:18
This thread has become a mashup of solutions to multiple problems and people posting "thank you" replies so I'm going to close and lock it.

While I appreciate the engagement, if the docs/wiki/readme are wrong, please fix them with PRs or submit a new issue to request that they be changed. This will help people get the setup right the first time and avoid future issues being created when new users don't search the old issues for solutions or can't find it when they do because it's buried in an unrelated thread.

**Closed by joshfriend** 2020-01-16 21:18 UTC
Labels: state: unconfirmed, type: question
