### ISSUE TITLE
Latest version of pyenv on Linux fails to build _ctypes for python 3.7.12

### ISSUE THREAD

**Issue by FelixLonergan** [pyenv/pyenv#2207] opened 2022-01-04 23:12 UTC
The recent release of pyenv 2.2.3 seems to have broken installing python 3.7.12 on linux. This seems to be related to #2190. 

During the installation, pyenv fails to build the  `_ctypes` module. All the packages listed in the [suggested build environment](https://github.com/pyenv/pyenv/wiki#suggested-build-environment) are installed, and using pyenv 2.2.2 in the exact same environment installs 3.7.12 correctly. Unlike #2159 brew is not installed. I have included the logs for both versions of pyenv below.

[pyenv version 2.2.3: pyenv install 3.7.12](https://gist.github.com/FelixLonergan/b2f0b063c92238f162b43fb2850375ec)
[pyenv version 2.2.2: pyenv install 3.7.12](https://gist.github.com/FelixLonergan/5f2e6471c58ef00f37d2419a7b9c03a1)

### Prerequisite
* [x] Make sure your problem is not listed in [the common build problems](https://github.com/pyenv/pyenv/wiki/Common-build-problems).
* [x] Make sure no duplicated issue has already been reported in [the pyenv issues](https://github.com/pyenv/pyenv/issues). You should look for closed issues, too.
* [x] Make sure you are not asking us to help solving your specific issue.
* [x] Make sure your problem is not derived from packaging (e.g. [Homebrew](https://brew.sh)).
  * Please refer to the package documentation for the installation issues, etc.
* [x] Make sure your problem is not derived from plugins.
  * This repository is maintaining `pyenv` and the default `python-build` plugin only. Please refrain from reporting issues of other plugins here.

### Description
- [x] Platform information (e.g. Ubuntu Linux 16.04): Amazon Linux 2
- [x] OS architecture (e.g. amd64): x86_64
- [x] pyenv version: 2.2.3
- [x] Python version: 3.7.12
- [x] C Compiler information (e.g. gcc 7.3):  gcc 7.3.1
- [x] Please attach the debug trace of the failing command as a gist

**Comment by native-api** [comment] 2022-01-05 14:15
This doesn't seem relevant to #2190:

> INFO: Could not locate ffi libs and/or headers

I clearly see that `-lffi` is missing from GCC flags in the faulty case.

The discovery logic is: first, `configure` retrieves include dir from `pkg-config` and stores it to an envvars, then `setup.py` reads that envvar and checks up on some file on relevant paths.

**Comment by tharradine** [comment] 2022-01-06 02:30
@native-api I'm a colleague of @FelixLonergan and am also experiencing this issue.

We only assumed #2190 was related, based on the fact that it's related to `_ctypes` on 3.7.12, and was merged between 2.2.2 and 2.2.3. We aren't sure precisely what the cause is, as we're not 100% sure on pyenv's internal logic.

What extra information do you need from us to help find the root cause?

**Comment by native-api** [comment] 2022-01-06 10:43
* First, check if you have [Python build dependencies](https://github.com/pyenv/pyenv/wiki#suggested-build-environment) installed. 
* If yes, check `config.log` in the bulid tree, there should be a `LIBFFI_INCLUDEDIR` line. See if the path it points to exists.
* If yes, you'll have no choice but to see the relevant `setup.py` logic (`detect_ctypes` function) and find out where exactly it fails (it should execute the `self.use_system_libffi = True` line upon success). There are no trace logs for `setup.py` so I cannot help you here.

**Comment by H0neyBadger** [comment] 2022-01-06 19:55
Hi, 
Same issue here with centos8. thank you a lot @native-api for your help. 
according to the config.log , the `LIBFFI_INCLUDEDIR = ""`. 

as workaround, I removed the file `plugins/python-build/share/python-build/patches/3.7.12/Python-3.7.12/0001-Port-ctypes-and-system-libffi-patches-for-arm64-macO.patch` 

but I do not know yet the root cause.
I hope this helps

**Comment by native-api** [comment] 2022-01-06 20:13
@H0neyBadger 

> according to the config.log , the `LIBFFI_INCLUDEDIR = ""`

That envvar is populated from `pkg-config` (see `configure` or `configure.ac`). If it's empty, this likely means that not all build dependencies are present or some are broken.

**Comment by native-api** [comment] 2022-01-06 20:26
@chipx86 Could you please take a look at this?

Upon closer insepction, `plugins/python-build/share/python-build/patches/3.7.12/Python-3.7.12/0001-Port-ctypes-and-system-libffi-patches-for-arm64-macO.patch` does touch the build logic -- and apprently does so against its design.

`detect_ctypes()` intentionally sets `self.use_system_libffi = False` initially and then flips it to `True` upon successful detection. For MacOS, there are dedicated subsections where the logic you've added should be more at place -- since other logic should succeed first before the attribute is flipped.

**Comment by native-api** [comment] 2022-01-06 20:28
@chipx86 More importantly, since the patch is for MacOS, it should probably not touch the Linux path of the logic at all.

**Comment by H0neyBadger** [comment] 2022-01-06 21:25
For additional information.
the `/usr/include` seems missing from `inc_dirs`

https://github.com/pyenv/pyenv/blob/162fea40f7e157407ffe9e23d3681e06edeafa42/plugins/python-build/share/python-build/patches/3.7.12/Python-3.7.12/0001-Port-ctypes-and-system-libffi-patches-for-arm64-macO.patch#L254

when I compare the two variable I have the following value,
original:
```
['./Include', '.', '/usr/local/include', '/tmp/python-build.20220106211131.7978/Python-3.7.12/Include', '/tmp/python-build.20220106211131.7978/Python-3.7.12', '/usr/include']
```
after patch:
```
 ['./Include', '.', '/usr/local/include', '/tmp/python-build.20220106210058.23239/Python-3.7.12/Include', '/tmp/python-build.20220106210058.23239/Python-3.7.12']
 ```

**Comment by native-api** [comment] 2022-01-06 21:27
As @H0neyBadger mentioned, as a workaround, you can delete `plugins/python-build/share/python-build/patches/3.7.12/Python-3.7.12/0001-Port-ctypes-and-system-libffi-patches-for-arm64-macO.patch` before installing Python 3.7.12.

**Comment by chipx86** [comment] 2022-01-07 00:23
Annoyingly, I'm having no trouble compiling locally on Linux. I might follow up with some questions as I dig in more.

Regarding where the logic is placed, this logic in the patch provided is a backport of the build changes made in Python 3.8+ to address some of the libffi placement issues. I think I see where things went wrong in the backport attempt, though. I'll follow up once I'm able to get a repro build, and I'll be testing my 3.8 patch as well.

**Comment by tharradine** [comment] 2022-01-07 00:25
@chipx86 I can provide you with a fairly minimal amazonlinux2-based Dockerfile which reproduces the issue, if that helps

**Comment by chipx86** [comment] 2022-01-07 00:27
@tharradine That would be perfect, thanks!

**Comment by chipx86** [comment] 2022-01-07 00:32
What I'm seeing from comparing the build logic is the following:

1. Newer versions of `detect_ctypes` made use of instance-level attributes, like `self.compiler.include_dirs` and `self.inc_dirs`, when dealing with search paths, and these had all the correct paths.
2. Older versions (3.7 and earlier) were passed these variables as arguments. The instance-level ones exist, which is why it didn't outright fail to run, but they lacked some computed entries at this stage.

The backported code also backported the usage of the instance-level search paths, rather than using the ones passed to the function. So I think this is going to be a very easy fix. As soon as I can verify the hunch, I'll put up a new pull request.

**Comment by chipx86** [comment] 2022-01-07 00:34
If you want to try a quick test on your end, modify that patch file and just remove line 254:

```
inc_dirs = self.compiler.include_dirs[:]
```

This was overriding the version passed to the function.

Library scanning is also circumvented if the include file can't be found, hence the lack of `-lffi`.

**Comment by tharradine** [comment] 2022-01-07 00:35
Here is the Dockerfile:

```Dockerfile
FROM amazonlinux:2

# Install build tools
RUN set -ex \
    && yum update -q -y \
    && yum groupinstall -q -y "Development tools" \
    && yum install -q -y \
           wget snappy-devel dos2unix cmake which zlib-devel tk-devel openssl-devel \
           bzip2 bzip2-devel sqlite sqlite-devel xz xz-devel libffi-devel findutils \
           readline-devel curl libcurl-devel iptables e2fsprogs xfsprogs

# Install pyenv
RUN curl -ssL https://pyenv.run | bash
ENV PYENV_ROOT="/root/.pyenv"
ENV PATH="$PYENV_ROOT/shims:$PYENV_ROOT/bin:$PATH"

#Python 3.7
RUN set -eux; \
    # Determine latest release of Python 3.7
    PYTHON_37_VERSION=$(pyenv install --list \
                        | grep -P '^\s+3\.7\.\d+$' \
                        | tail -n 1 \
                        | tr -d '[:space:]') \
    ; \
    # Install Python 3.7 with pyenv
    env PYTHON_MAKE_OPTS="-j4" \
        PYENV_DEBUG="1" \
        pyenv install -v $PYTHON_37_VERSION 2>&1 | tee /var/log/pyenv_install_3.7.log \
    ; \
    rm -rf /tmp/*; \
    # Set global version
    pyenv global $PYTHON_37_VERSION

CMD ["python", "-c", "import ctypes"]
```

**Comment by chipx86** [comment] 2022-01-07 00:44
Thanks, that'll greatly help! Giving it a try.

**Comment by chipx86** [comment] 2022-01-07 01:12
Verified the failure with the Dockerfile. Compilation with a revised patch is looking good. Performing another clean build and then I'll launch, verify `ctypes` is working.

**Comment by chipx86** [comment] 2022-01-07 01:18
Success. If you want to verify on your end, I'm attaching the new patch:

[0001-Port-ctypes-and-system-libffi-patches-for-arm64-macO.patch.txt](https://github.com/pyenv/pyenv/files/7825632/0001-Port-ctypes-and-system-libffi-patches-for-arm64-macO.patch.txt)

In the Dockerfile:

```Dockerfile
ADD 0001-Port-ctypes-and-system-libffi-patches-for-arm64-macO.patch /root/.pyenv/plugins/python-build/share/python-build/patches/3.7.12/Python-3.7.12/0001-Port-ctypes-and-system-libffi-patches-for-arm64-macO.patch
```

Running tests on macOS, and I'll also test 3.6.18 on Linux (using the Dockerfile) and macOS for verification.

**Closed** 2022-01-07 02:14 UTC
Labels: need-feedback

**Comment by tharradine** [comment] 2022-01-07 02:48
Thanks so much for the quick debug and fix guys <3

**Comment by chipx86** [comment] 2022-01-07 02:49
Thanks for the report, @tharradine, and for the ping, @native-api! Let me know if anything else comes up.
