### ISSUE TITLE
Cannot pass multipart options to configure

### ISSUE THREAD

**Issue by ezwelty** [pyenv/pyenv#1125] opened 2018-03-21 00:58 UTC
I am trying to override the paths to the Tcl/Tk libraries by setting `PYTHON_CONFIGURE_OPTS`. When building manually, I can do this:

```bash
./configure \
  --with-tcltk-includes="-I/usr/local/opt/tcl-tk/include" \
  --with-tcltk-libs="-L/usr/local/opt/tcl-tk/lib -ltcl8.6 -ltk8.6"
```

But with pyenv, no matter what I try, I get:

```bash
$ env PYTHON_CONFIGURE_OPTS=SOMETHING pyenv install 2.7.14 --verbose
...
configure: error: unrecognized option: `-ltcl8.6'
```

Lines of interest from the stack trace suggest a parsing bug somewhere:

```
+ eval 'PYTHON_CONFIGURE_OPTS_ARRAY=( "${value[@]}" )'
++ PYTHON_CONFIGURE_OPTS_ARRAY=("${value[@]}")
+ [[ '' == *\-\-\e\n\a\b\l\e\-\s\h\a\r\e\d* ]]
+ [[ --with-tcltk-includes='-I/usr/local/opt/tcl-tk/include' --with-tcltk-libs='-L/usr/local/opt/tcl-tk/lib -ltcl8.6 -ltk8.6' == *\-\-\e\n\a\b\l\e\-\s\h\a\r\e\d* ]]
+ [[ '' == *\-\-\s\h\a\r\e\d* ]]
+ [[ --with-tcltk-includes='-I/usr/local/opt/tcl-tk/include' --with-tcltk-libs='-L/usr/local/opt/tcl-tk/lib -ltcl8.6 -ltk8.6' == *\-\-\e\n\a\b\l\e\-\f\r\a\m\e\w\o\r\k* ]]
+ [[ --with-tcltk-includes='-I/usr/local/opt/tcl-tk/include' --with-tcltk-libs='-L/usr/local/opt/tcl-tk/lib -ltcl8.6 -ltk8.6' == *\-\-\e\n\a\b\l\e\-\u\n\i\v\e\r\s\a\l\s\d\k* ]]
+ [[ --with-tcltk-includes='-I/usr/local/opt/tcl-tk/include' --with-tcltk-libs='-L/usr/local/opt/tcl-tk/lib -ltcl8.6 -ltk8.6' != *\-\-\e\n\a\b\l\e\-\u\n\i\c\o\d\e\=* ]]
...
++ for arg in '${CONFIGURE_OPTS}' '${!PACKAGE_CONFIGURE_OPTS}' '"${!PACKAGE_CONFIGURE_OPTS_ARRAY}"'
++ [[ --with-tcltk-includes='-I/usr/local/opt/tcl-tk/include' == \C\P\P\F\L\A\G\S\=* ]]
++ for arg in '${CONFIGURE_OPTS}' '${!PACKAGE_CONFIGURE_OPTS}' '"${!PACKAGE_CONFIGURE_OPTS_ARRAY}"'
++ [[ --with-tcltk-libs='-L/usr/local/opt/tcl-tk/lib == \C\P\P\F\L\A\G\S\=* ]]
++ for arg in '${CONFIGURE_OPTS}' '${!PACKAGE_CONFIGURE_OPTS}' '"${!PACKAGE_CONFIGURE_OPTS_ARRAY}"'
++ [[ -ltcl8.6 == \C\P\P\F\L\A\G\S\=* ]]
++ for arg in '${CONFIGURE_OPTS}' '${!PACKAGE_CONFIGURE_OPTS}' '"${!PACKAGE_CONFIGURE_OPTS_ARRAY}"'
++ [[ -ltk8.6' == \C\P\P\F\L\A\G\S\=* ]]
...
```

Values for `PYTHON_CONFIGURE_OPTS` that I have attempted, to no avail:

- `"--with-tcltk-includes='-I/usr/local/opt/tcl-tk/include' --with-tcltk-libs='-L/usr/local/opt/tcl-tk/lib -ltcl8.6 -ltk8.6'"`
- `'--with-tcltk-includes="-I/usr/local/opt/tcl-tk/include" --with-tcltk-libs="-L/usr/local/opt/tcl-tk/lib -ltcl8.6 -ltk8.6"'`
- `--with-tcltk-includes=-I/usr/local/opt/tcl-tk/include\ --with-tcltk-libs=-L/usr/local/opt/tcl-tk/lib\ -ltcl8.6\ -ltk8.6`
- `"--with-tcltk-includes=\"-I/usr/local/opt/tcl-tk/include\" --with-tcltk-libs=\"-L/usr/local/opt/tcl-tk/lib -ltcl8.6 -ltk8.6\""`
- `'--with-tcltk-includes=\"-I/usr/local/opt/tcl-tk/include\" --with-tcltk-libs=\"-L/usr/local/opt/tcl-tk/lib -ltcl8.6 -ltk8.6\"'`
- `--with-tcltk-includes=\"-I/usr/local/opt/tcl-tk/include\"\ --with-tcltk-libs=\"-L/usr/local/opt/tcl-tk/lib\ -ltcl8.6\ -ltk8.6\"`
- ...

**Comment by ezwelty** [comment] 2018-03-21 18:34
I ended up having to hard code these settings directly in `python-build`. I suspect the only fix would be to pass options with a custom delimeter.

Current code:

```bash
PYTHON_CONFIGURE_OPTS="--with-tcltk-includes=-I/usr/local/opt/tcl-tk/include --with-tcltk-libs='-L/usr/local/opt/tcl-tk/lib -ltcl8.6 -ltk8.6'"
package_var_name=PYTHON
PACKAGE_CONFIGURE_OPTS="${package_var_name}_CONFIGURE_OPTS"
for arg in ${!PACKAGE_CONFIGURE_OPTS}; do
  echo -e $arg
done
```

> --with-tcltk-includes=-I/usr/local/opt/tcl-tk/include
--with-tcltk-libs='-L/usr/local/opt/tcl-tk/lib
-ltcl8.6
-ltk8.6'

Suggested code:

```bash
PYTHON_CONFIGURE_OPTS="--with-tcltk-includes=-I/usr/local/opt/tcl-tk/include|--with-tcltk-libs='-L/usr/local/opt/tcl-tk/lib -ltcl8.6 -ltk8.6'"
package_var_name=PYTHON
PACKAGE_CONFIGURE_OPTS="${package_var_name}_CONFIGURE_OPTS"
IFS='|'; PACKAGE_CONFIGURE_OPTS=(${!PACKAGE_CONFIGURE_OPTS}); unset IFS;
for arg in "${PACKAGE_CONFIGURE_OPTS[@]}"; do
  echo -e $arg
done
```

> --with-tcltk-includes=-I/usr/local/opt/tcl-tk/include
--with-tcltk-libs='-L/usr/local/opt/tcl-tk/lib -ltcl8.6 -ltk8.6'

**Comment by yyuu** [comment] 2018-03-22 01:27
Hmm, I think you're correct. At present, `python-build` cannot handle quoting/whitespace within `PYTHON_CONFIGURE_OPTS` correctly 😞 

As a tentative workaround to deal with the situation, declaring `PYTHON_CONFIGURE_OPTS_ARRAY` within custom build definition might work.

1. Copy [the definition](https://github.com/pyenv/pyenv/blob/v1.2.2/plugins/python-build/share/python-build/2.7.14) to your custom location
    * you can also find it on your local filesystem at `$(pyenv root)/plugins/python-build/share/python-build/2.7.14`
1. Prepend the following line at the top of the build definitino
    * `PYTHON_CONFIGURE_OPTS_ARRAY=("--with-tcltk-includes='-I/usr/local/opt/tcl-tk/include'" "--with-tcltk-libs='-L/usr/local/opt/tcl-tk/lib -ltcl8.6 -ltk8.6'")`
1. Call `pyenv install` with specifying the custom build definition (e.g. `pyenv install -v ./2.7.14`)

**Comment by ezwelty** [comment] 2018-03-22 16:08
@yyuu Interestingly, your suggestion of declaring the array in the build definition works for `configure` but then breaks in `make`:

```
Last 10 log lines:
                        Modules/python.o \
                        libpython2.7.a -ldl  -framework CoreFoundation
./python.exe -E -S -m sysconfig --generate-posix-vars ;\
        if test $? -ne 0 ; then \
                echo "generate-posix-vars failed" ; \
                rm -f ./pybuilddir.txt ; \
                exit 1 ; \
        fi
/bin/sh: -ltcl8.6: command not found
make: *** [sharedmods] Error 127
```

Is `PACKAGE_CONFIGURE_OPTS_ARRAY` being chopped up elsewhere on whitespace for input to `make`?

For anyone passing through needing a dirty fix, I got the build to work by editing `python-build`, line 752, from:

```bash
$CONFIGURE_OPTS ${!PACKAGE_CONFIGURE_OPTS} "${!PACKAGE_CONFIGURE_OPTS_ARRAY}" || return 1
```

to:

```bash
$CONFIGURE_OPTS --with-tcltk-includes='-I/usr/local/opt/tcl-tk/include' --with-tcltk-libs='-L/usr/local/opt/tcl-tk/lib -ltcl8.6 -ltk8.6' ${!PACKAGE_CONFIGURE_OPTS} "${!PACKAGE_CONFIGURE_OPTS_ARRAY}" || return 1
```

**Comment by bdusell** [comment] 2018-07-06 17:17
I'm facing exactly the same issue, but the suggested workaround using a custom build definition worked just fine for me. Even so, I think it would be nice to have a simpler way to include spaces in `./configure` arguments in general.

The biggest inconvenience is that there is no way to export a bash array. How about simply introducing a new variable whose content is evaluated as an array? For example:

```bash
PYTHON_CONFIGURE_OPTS_EVAL="--with-tcltk-includes='-I/usr/local/opt/tcl-tk/include' --with-tcltk-libs='-L/usr/local/opt/tcl-tk/lib -ltcl8.6 -ltk8.6'"
```

```bash
eval -- "local eval_opts=($PACKAGE_CONFIGURE_OPTS_EVAL)"
$CONFIGURE_OPTS ${!PACKAGE_CONFIGURE_OPTS} "${eval_opts[@]}" "${!PACKAGE_CONFIGURE_OPTS_ARRAY}" || return 1
```

**Comment by fritzr** [comment] 2019-02-13 22:28
+1 on this issue.

I agree with @bdusell. Anything short of an eval array assignment will pass the environment variable as a single string, or worse yet white-space separated (ignoring quotes). I'd even lobby for eval'ing PACKAGE_CONFIGURE_OPTS directly rather than introducing a new variable, since it seems to be expected behavior (but I see the utility of introducing a new variable for safety).

**Comment by jidicula** [comment] 2019-07-09 16:33
Hi, I've been running into this issue as well. I'm trying to use PYTHON_CONFIGURE_OPTS to point to a different installation of Tcl-Tk on macOS so tkinter will work with versions of python built with pyenv.

Is there a workaround for this or should I hold off on pyenv and use the Python.org installer until this issue is resolved?

I'm not very familiar with pyenv's codebase so I'm not sure how or where to implement @bdusell's suggestion on my pyenv installation.

**Comment by bdusell** [comment] 2019-07-09 20:49
@jidicula Do give yyuu's workaround a try -- it worked for me.

**Comment by jidicula** [comment] 2019-07-10 01:23
Thanks @bdusell – I just tried that and initially got a `make` error (but scroll down, I tried something else and the build kind of worked):

```
Last 10 log lines:
clang -L/usr/local/opt/readline/lib -L/usr/local/opt/readline/lib -L/Users/johanan/.pyenv/versions/3.7.3/lib -L/usr/local/opt/tcl-tk/lib -L/usr/local/opt/readline/lib -L/usr/local/opt/readline/lib -L/Users/johanan/.pyenv/versions/3.7.3/lib -L/usr/local/opt/tcl-tk/lib   -Wl,-stack_size,1000000  -framework CoreFoundation -o Programs/_testembed Programs/_testembed.o libpython3.7m.a -ldl  -framework CoreFoundation     
./python.exe -E -S -m sysconfig --generate-posix-vars ;\
	if test $? -ne 0 ; then \
		echo "generate-posix-vars failed" ; \
		rm -f ./pybuilddir.txt ; \
		exit 1 ; \
	fi
 CC='clang' LDSHARED='clang -bundle -undefined dynamic_lookup -L/usr/local/opt/readline/lib -L/usr/local/opt/readline/lib -L/Users/johanan/.pyenv/versions/3.7.3/lib -L/usr/local/opt/tcl-tk/lib -L/usr/local/opt/readline/lib -L/usr/local/opt/readline/lib -L/Users/johanan/.pyenv/versions/3.7.3/lib -L/usr/local/opt/tcl-tk/lib  ' OPT='-DNDEBUG -g -fwrapv -O3 -Wall' 	_TCLTK_INCLUDES=''-I/Library/Frameworks/Tcl.framework/Headers -I/Library/Frameworks/Tk.framework/Headers'' _TCLTK_LIBS=''/Library/Frameworks/Tcl.framework/Versions/8.6/Tcl /Library/Frameworks/Tk.framework/Versions/8.6/Tk'' 	./python.exe -E ./setup.py  build
/bin/sh: -I/Library/Frameworks/Tk.framework/Headers: No such file or directory
make: *** [sharedmods] Error 127
```

So then I tried something that seemed to make sense to my caveman brain: I prepended the following to my custom copy of the 3.7.3 build definition:

`PYTHON_CONFIGURE_OPTS_ARRAY=("--with-tcltk-includes=('-I/Library/Frameworks/Tcl.framework/Headers' '-I/Library/Frameworks/Tk.framework/Headers')" "--with-tcltk-libs=('/Library/Frameworks/Tcl.framework/Versions/8.6/Tcl' '/Library/Frameworks/Tk.framework/Versions/8.6/Tk')")`

I gave each configure option its own array of path strings – lo and the build worked:

![image](https://user-images.githubusercontent.com/12765385/60931771-e4d61c80-a288-11e9-9021-7316444f32e3.png)

However, there still seems to be an issue of Tk version mismatch when I try running the test for tkinter:

```
Python 3.7.3 (default, Jul  9 2019, 20:29:53) 
[Clang 10.0.1 (clang-1001.0.46.4)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import _tkinter
>>> import tkinter
>>> tkinter._test()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/johanan/.pyenv/versions/3.7.3/lib/python3.7/tkinter/__init__.py", line 3988, in _test
    root = Tk()
  File "/Users/johanan/.pyenv/versions/3.7.3/lib/python3.7/tkinter/__init__.py", line 2025, in __init__
    self._loadtk()
  File "/Users/johanan/.pyenv/versions/3.7.3/lib/python3.7/tkinter/__init__.py", line 2040, in _loadtk
    % (_tkinter.TK_VERSION, tk_version))
RuntimeError: tk.h version (8.6) doesn't match libtk.a version (8.5)
>>> 
```

I hadn't mentioned this before, but this has been the end goal of being able to pass options to configure in the hopes that it would allow the pyenv-built Python 3.7 to use the correct installation of TclTk, but it seems I'm back where I started. Thanks anyway for your help – I'll probably stick to using the binary installers from Python.org since those work reliably with their included TclTk.

**Comment by grahamannett** [comment] 2019-07-18 19:51
@ezwelty fix seems to work (editing the line to `$CONFIGURE_OPTS --with-tcltk-includes='-I/usr/local/opt/tcl-tk/include' --with-tcltk-libs='-L/usr/local/opt/tcl-tk/lib -ltcl8.6 -ltk8.6' ${!PACKA     GE_CONFIGURE_OPTS} "${!PACKAGE_CONFIGURE_OPTS_ARRAY}" || return 1` but its line 775 in the version I am using.  Editing the build def with `PYTHON_CONFIGURE_OPTS_ARRAY=("--with-tcltk-includes='-I/usr/local/opt/tcl-tk/include'" "--with-tcltk-libs='-L/usr/local/opt/tcl-tk/lib -ltcl8.6 -ltk8.6'")` is the error her reported still.  How hard would this be to just allow some argument for the time being to make it work rather than worrying about the arguments array thing?

**Comment by tcarroll2** [comment] 2019-08-23 11:19
> ```shell
> $CONFIGURE_OPTS --with-tcltk-includes='-I/usr/local/opt/tcl-tk/include' --with-tcltk-libs='-L/usr/local/opt/tcl-tk/lib -ltcl8.6 -ltk8.6' ${!PACKAGE_CONFIGURE_OPTS} "${!PACKAGE_CONFIGURE_OPTS_ARRAY}" || return 1
> ```

@ezwelty Thank you for this!  It worked!

**Comment by grahamannett** [comment] 2019-09-30 21:37
For this, I was using a regex to match in python-build but I've realized it's a bit not obvious to others if trying to install.  Is it worthwhile to try and use homebrew installed first and then regex match?  How does this work with non homebrew installed pyenv?

**Comment by native-api** [comment] 2021-06-10 12:09
I found that `xargs` is the multipart parser we need! With default settings, it respects quotes when splitting the input into arguments:

https://stackoverflow.com/questions/15857027/bash-doesnt-parse-quotes-when-converting-a-string-to-arguments/37382192#37382192

This way, we can convert `PYTHON_CONFIGURE_OPTS` and `FLAGS` variables into arrays early on and work with arrays for the bulk of the process.

**Comment by native-api** [comment] 2021-10-01 15:13
Specifically for tcl/tk, this is fixed in https://github.com/pyenv/pyenv/pull/1646. For the general issue, created a new ticket, https://github.com/pyenv/pyenv/issues/2083, where I summarised the findings.

**Closed** 2021-10-01 15:13 UTC
Labels: type: enhancement, area: build
