### ISSUE TITLE
pyenv uses child dir .python-version to pick version to use

### ISSUE THREAD

**Issue by cdunklau** [pyenv/pyenv#1150] opened 2018-04-25 11:46 UTC
- Platform information (e.g. Ubuntu Linux 16.04): Mac OS 10.13.3
- OS architecture (e.g. amd64): amd64
- pyenv version: 1.2.3
- Python version: 3.6.3, 3.5.3

pyenv appears to be picking the python version based on the directory in which the **argument** to the shim lives. From my understanding of https://github.com/pyenv/pyenv#choosing-the-python-version this is not intended (or at least not documented) behavior. It's also pretty strange IMO.

Steps to reproduce:

1. Set up the directory structure and cd into the first one: `mkdir -p pyenv-test-dirissue/py35-dir && cd pyenv-test-dirissue`
2. Set pyenv version to 3.6.3: `pyenv local 3.6.3`
3. In the child directory, set pyenv version to 3.5.3: `cd py35-dir && pyenv local 3.5.3`
4. Verify `pyenv version` shows 3.5.3
5. Change back to the initial dir: `cd ..`
6. Verify `pyenv version` shows 3.6.3
7. Create printver.py script in both `pyenv-test-dirissue` and `pyenv-test-dirissue/py35-dir`:
    ```
    echo 'import sys; print(sys.version)' > printver.py
    echo 'import sys; print(sys.version)' > py35-dir/printver.py
    ```
8. Run printver.py in the `pyenv-test-dirissue`: `python3 printver.py`
9. See that it's running 3.6.3
10. Run printver.py in `pyenv-test-dirissue/py35-dir` while still inside `pyenv-test-dirissue`: `python3 py35-dir/printver.py`
11. Notice that this time it ran 3.5.3

Here's the output from me doing it:

```
cdunklau@hobbes ~ $ mkdir -p pyenv-test-dirissue/py35-dir && cd pyenv-test-dirissue
cdunklau@hobbes ~/pyenv-test-dirissue $ pyenv local 3.6.3
cdunklau@hobbes ~/pyenv-test-dirissue $ cd py35-dir && pyenv local 3.5.3
cdunklau@hobbes ~/pyenv-test-dirissue/py35-dir $ pyenv local
3.5.3
cdunklau@hobbes ~/pyenv-test-dirissue/py35-dir $ cd ..
cdunklau@hobbes ~/pyenv-test-dirissue $ pyenv local
3.6.3
cdunklau@hobbes ~/pyenv-test-dirissue $ echo 'import sys; print(sys.version)' > printver.py
cdunklau@hobbes ~/pyenv-test-dirissue $ echo 'import sys; print(sys.version)' > py35-dir/printver.py
cdunklau@hobbes ~/pyenv-test-dirissue $ python3 printver.py
3.6.3 (default, Oct  5 2017, 13:43:44) 
[GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.37)]
cdunklau@hobbes ~/pyenv-test-dirissue $ python3 py35-dir/printver.py
3.5.3 (default, Apr 11 2017, 21:55:23) 
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)]
```

This is really strange to me, and since it's not documented behavior, I strongly suggest removing it. It's quite shocking to me that when I run `pyenv local` and see it's set to a particular version, there are situations where I can invoke the python3 shim and get a totally different version.

Do let me know if I've just misunderstood the docs, though. Thanks!

**Comment by tritium21** [comment] 2018-04-25 12:00
Are you sure step 4 is supposed to return 3.6.3?

**Comment by cdunklau** [comment] 2018-04-25 12:01
Fixed, thanks

**Comment by yyuu** [comment] 2018-04-26 03:51
At least I can say it is some expected behavior with current code. pyenv's [shim script is implemented to pick up local version from first file argument if exists](https://github.com/pyenv/pyenv/blob/v1.2.3/libexec/pyenv-rehash#L54-L57). I think picking up `.python-version` from script's installation location would be reasonable at some extent, but might not be intuitive for some cases 🤔 

This behavior was originally derived from [rbenv](https://github.com/rbenv/rbenv/blob/v1.1.1/libexec/rbenv-rehash#L54-L57).

**Comment by cdunklau** [comment] 2018-04-30 22:32
Well, if it's behavior from rbenv, and you want to keep parity, I'm for sure -0 on removing it. It's odd and surprising IMO, but doesn't break stuff.

I'd suggest at minimum documenting the behavior, probably in that "Choosing the Python Version"  section referenced in my original report.

I think the optimal solution would be to:

1. leave it as the default behavior so as to not surprise people who already depend on it, and
2. add a configuration option that allows the user to disable it.

**Comment by native-api** [comment] 2021-05-07 21:35
Duplicate of https://github.com/pyenv/pyenv/issues/1813

**Closed by native-api** 2021-05-07 21:35 UTC
