### ISSUE TITLE
Shims should support ZSH, not only Bash

### ISSUE THREAD

**Issue by chrisduong** [pyenv/pyenv#1089] opened 2018-02-06 03:08 UTC
Hi,

I install `aws-cli` Python package, it included the ZSH completion script `aws_zsh_completer.sh`. So PyEnv create Shim for `aws_zsh_completer.sh`, which will be later run under Bash script `/usr/local/Cellar/pyenv/1.2.1/libexec/pyenv`. This would fail as the Libexec `pyenv` does not compatible with ZSH.

Is it possible that Libexec `pyenv` to support ZSH. Thanks.

**Comment by pecigonzalo** [comment] 2018-04-02 21:38
I would advise to use a `virtualenv` for this, it will get away from the shim issues.

**Comment by lqueryvg** [comment] 2019-04-06 22:37
I see the same problem.
A `virtualenv`  doesn't fix the problem.

The problem is as @chrisduong described.
`.pyenv/libexec/pyenv` is written in bash and assumes target the script to be executed will run under bash.
It would be more correct to run the script under the same shell as executed the original shim.

For example:

In zsh I'm trying to do this:

    source $(which aws_zsh_completer.sh)

I get errors:

    <home-dir>/.pyenv/versions/<virtualenv>/bin/aws_zsh_completer.sh: line 24: autoload: command not found
    <home-dir>/.pyenv/versions/<virtualenv>/bin/aws_zsh_completer.sh: line 25: bashcompinit: command not found

The target script needs to run under zsh to setup the zsh completions, but instead it's running under bash which can't find the zsh functions.

My only workaround is to find the real target script and run it directly, which defeats the point of using the shims to switch between versions.

**Comment by JimFawkes** [comment] 2019-10-02 12:02
I am facing the same Issue as described by @lqueryvg. 

Is there an update regarding this?

**Comment by asemarafa** [comment] 2019-12-06 09:13
i was looking for a solution for this , the workaround i ended up using is 

source $(pyenv prefix)/bin/aws_zsh_completer.sh

**Comment by native-api** [comment] 2021-05-08 20:42
https://github.com/pyenv/pyenv/pull/100

**Comment by native-api** [comment] 2021-05-08 20:43
Duplicate of https://github.com/pyenv/pyenv/pull/100

**Comment by native-api** [comment] 2021-05-08 20:43
https://github.com/pyenv/pyenv/pull/100#issuecomment-785207674

**Closed by native-api** 2021-05-08 20:43 UTC
Labels: area: shims
