### ISSUE TITLE
generate-posix-vars failed when installing 2.7.10 on Ubuntu 18.10

### ISSUE THREAD

**Issue by ekallevig** [pyenv/pyenv#1298] opened 2019-03-07 15:04 UTC
### Description
- [ ] Platform information (e.g. Ubuntu Linux 18.10):
- [ ] OS architecture (Intel® Core™ i5-5200U CPU @ 2.20GHz × 4)
- [ ] pyenv version: pyenv 1.2.9-19-g7d02b246
- [ ] Python version: 2.7.10
- [ ] C Compiler information (gcc 8.2.0): 
- [ ] Please attach verbose build log as gist: https://gist.github.com/ekallevig/66f2136053fb3791bfc76803dcc14bcf

**Comment by ekallevig** [comment] 2019-03-07 20:53
Same issue on latest Manjaro

**Comment by yakky** [comment] 2019-04-14 15:30
Same here: anyhint how to investigate further?

**Comment by chrahunt** [comment] 2019-04-18 16:02
It looks like [this](https://bugs.python.org/issue33374) upstream issue in Python.

This can be fixed by using a newer version of Python (2.7.15) or by applying the patch [here](https://github.com/python/cpython/commit/0b91f8a668201fc58fa732b8acc496caedfdbae0.patch) to Python 2.7.10, following the instructions [here](https://github.com/pyenv/pyenv/tree/master/plugins/python-build#applying-patches-to-python-before-compiling), e.g.:

```
~/.pyenv/bin/pyenv install -p 2.7.10 < 0b91f8a668201fc58fa732b8acc496caedfdbae0.patch
```

I reproduced the issue by running `~/.pyenv/bin/pyenv install 2.7.10` in a container spawned from this Dockerfile:

<details>
<summary>Dockerfile</summary>

```
FROM ubuntu:18.10

# https://stackoverflow.com/a/51881727/1698058
RUN export DEBIAN_FRONTEND=noninteractive; \
    export DEBCONF_NONINTERACTIVE_SEEN=true; \
    echo 'tzdata tzdata/Areas select Etc' | debconf-set-selections; \
    echo 'tzdata tzdata/Zones/Etc select UTC' | debconf-set-selections; \
    apt-get update -qqy \
 && apt-get install -qqy --no-install-recommends \
        build-essential \
        ca-certificates \
        curl \
        gdb \
        git \
        libbz2-dev \
        libffi-dev \
        liblzma-dev \
        libncurses5-dev \
        libncursesw5-dev \
        libreadline-dev \
        libsqlite3-dev \
        libssl-dev \
        llvm \
        make \
        python-openssl \
        tk-dev \
        tzdata \
        vim \
        wget \
        xz-utils \
        zlib1g-dev \
 && apt-get clean \
 && rm -rf /var/lib/apt/lists/*

RUN git clone https://github.com/pyenv/pyenv.git ~/.pyenv
```

</details>

and then tried again after applying the above patch and it seemed to work (at least it failed at a later stage, unable to build the ssl extension).

**Comment by yakky** [comment] 2019-04-19 11:22
By following the instructions above I sort of compiled it: pyenv install fails for no apparent reason because the last ten lines of the log are the last 10 lines of the `make install` command, but the `versions` directory is empty
by running `make install` again in the tmp build directory, python is installed and works correclty
`make install` exit status is `0` thus I don't know why.
This is the build log. One generated with ``--verbose`` will be available soon
```
Downloading Python-2.7.10.tar.xz...
-> https://www.python.org/ftp/python/2.7.10/Python-2.7.10.tar.xz
Installing Python-2.7.10...
patching file Include/objimpl.h
patching file 'Misc/NEWS.d/next/Core and Builtins/2018-04-29-12-07-00.bpo-33374.-xegL6.rst'
ERROR: The Python ssl extension was not compiled. Missing the OpenSSL lib?

Please consult to the Wiki page to fix the problem.
https://github.com/pyenv/pyenv/wiki/Common-build-problems


BUILD FAILED (Ubuntu 18.10 using python-build 1.2.9-4-g6b041822)

Inspect or clean up the working tree at /tmp/python-build.20190419121902.21867
Results logged to /tmp/python-build.20190419121902.21867.log

Last 10 log lines:
rm -f /home/yakky/.pyenv/versions/2.7.10/share/man/man1/python.1
(cd /home/yakky/.pyenv/versions/2.7.10/share/man/man1; ln -s python2.1 python.1)
if test "xno" != "xno"  ; then \
        case no in \
                upgrade) ensurepip="--upgrade" ;; \
                install|*) ensurepip="" ;; \
        esac; \
         ./python -E -m ensurepip \
                $ensurepip --root=/ ; \
fi
```

**Comment by yyuu** [comment] 2019-04-19 12:04
Please read the message. Clearly it is telling that ssl module isn't built. Read the wiki page.

**Comment by yakky** [comment] 2019-04-19 22:31
Sorry, apparently a message got lost here
I was aware that the error was caused by openssl, but it took a while to figure out the solution
Reporting here the solution I applied:
- install `brew` (https://docs.brew.sh/Homebrew-on-Linux)
- install 1.0 version of openssl (`brew install openssl`)
- compile python as reported here https://github.com/pyenv/pyenv/issues/1298#issuecomment-484573923

Probably the wiki might be improved in this, I can come up with a proposal to improve it, if of interest

**Comment by igor47** [comment] 2019-04-25 17:38
if you're running into this issue, here's a one-liner workaround (replace `2.7.10` with your desired version):

```
wget https://github.com/python/cpython/commit/0b91f8a668201fc58fa732b8acc496caedfdbae0.patch -O - | pyenv install -p 2.7.10
```

**Closed** 2021-05-07 17:08 UTC
Labels: area: build, awaiting response, impl: cpython, os: Linux
