### ISSUE TITLE
pyenv: version system not installed

### ISSUE THREAD

**Issue by tommyjcarpenter** [pyenv/pyenv#1301] opened 2019-03-15 13:29 UTC
### Prerequisite
* [x] Make sure your problem is not listed in [the common build problems](https://github.com/pyenv/pyenv/wiki/Common-build-problems).
* [x] Make sure no duplicated issue has already been reported in [the pyenv issues](https://github.com/pyenv/pyenv/issues). You should look for closed issues, too.

There is a closed issue, but it was closed without explanation or resolution: https://github.com/pyenv/pyenv/issues/622

* [x] Make sure you are not asking us to help solving your specific issue.
  * GitHub issues is opened mainly for development purposes. If you want to ask someone to help solving your problem, go to some community site like [Gitter](https://gitter.im/yyuu/pyenv), [StackOverflow](https://stackoverflow.com/questions/tagged/pyenv), etc.
* [x] Make sure your problem is not derived from packaging (e.g. [Homebrew](https://brew.sh)).
  * Please refer to the package documentation for the installation issues, etc.
* [x] Make sure your problem is not derived from plugins.
  * This repository is maintaining `pyenv` and the default `python-build` plugin only. Please refrain from reporting issues of other plugins here.

### Description
- [x] Platform information (e.g. Ubuntu Linux 16.04): Arch Linux
- [x] OS architecture (e.g. amd64): Intel64
- [x] pyenv version: pyenv-1.2.9-1
- [x] Python version: 3.7.2
- [x] C Compiler information (e.g. gcc 7.3): 8.2.1 20181127
- [x] Please attach verbose build log as gist : N/A to this issue

I believe my issue is identical to a closed issue, but the issue was closed without explanation, reason, or resolution: https://github.com/pyenv/pyenv/issues/622

On a fresh install of Arch and Pyenv:

      >python --version
           Python 3.7.2
      > /usr/sbin/python          
          Python 3.7.2 (default, Jan 10 2019, 23:51:51)
          [GCC 8.2.1 20181127] on linux
          Type "help", "copyright", "credits" or "license" for more information.
      >pyenv versions  
           * system (set by /home/tommy/.pyenv/version)
      >pyenv global system   
            pyenv: version `system' not installed 

why?

**Comment by hubitor** [comment] 2019-12-07 23:34
Same here...
Is there a workaround for switching to `system` until the bug is fixed?

**Comment by hubitor** [comment] 2019-12-09 12:58
I've switched to an anaconda version and now I cannot switch back to the system version. I cannot open Calibre and i3 status bar shows an error because of this issue. Please provide a workaround or fix the bug.

**Comment by tcztzy** [comment] 2020-02-06 11:20
Pyenv assume that the parent directory of `python` executable is always named as `bin`.
https://github.com/pyenv/pyenv/blob/7097f8204e26c63a6ae9699255caa75e7c3ef084/libexec/pyenv-prefix#L34

**Comment by Gordin** [comment] 2020-07-12 15:14
I put this in my .zshrc/.bashrc to fix this. It just puts all path entries ending in `sbin` at the end of PATH.
```bash
# move all paths ending in 'sbin' to the back of PATH
# This is needed because pyenv fails to find the system python otherwise
for SB in $(echo "$PATH" | grep ':*/[^:]*sbin' -o)
do
  export PATH="${PATH/$SB}:${SB#:}"
done
```

**Comment by native-api** [comment] 2021-05-18 09:26
Should be fixed after 89d3d0c33d15085493f9e7f10abd7d0798b54f6a

**Closed by native-api** 2021-05-18 09:26 UTC
Labels: type: bug

**Comment by IvanaGyro** [comment] 2023-01-01 14:07
This issue may still affect WSL (Windows Subsystem for Linux) users. The WSL users may have "python" on Windows but only "python3" on WSL (for example, Ubuntu), so the scripts in [libexec/pyenv-prefix](https://github.com/pyenv/pyenv/commit/89d3d0c33d15085493f9e7f10abd7d0798b54f6a#diff-48154b5dfb5a5bead13cf14372bc4150f9181a40bf161bb0db3ebefc17417cdc) will try to verify the python path on Windows instead of the path on WSL.

Here is the script. I added the comments to point out the lines.

```python
    if [ "$version" = "system" ]; then
      if PYTHON_PATH="$(PYENV_VERSION="${version}" pyenv-which python 2>/dev/null)" || \ # get path on Windows here 
          PYTHON_PATH="$(PYENV_VERSION="${version}" pyenv-which python3 2>/dev/null)" || \
          PYTHON_PATH="$(PYENV_VERSION="${version}" pyenv-which python2 2>/dev/null)"; then
        PYENV_PREFIX_PATH="${PYTHON_PATH%/bin/*}"
        PYENV_PREFIX_PATH="${PYENV_PREFIX_PATH:-/}"
      else
        echo "pyenv: system version not found in PATH" >&2
        exit 1
      fi
    else
      PYENV_PREFIX_PATH="${PYENV_ROOT}/versions/${version}"
    fi
    if [ -d "$PYENV_PREFIX_PATH" ]; then
      # check failed
      PYENV_PREFIX_PATHS=("${PYENV_PREFIX_PATHS[@]}" "$PYENV_PREFIX_PATH")
    else
      echo "pyenv: version \`${version}' not installed" >&2
      exit 1
fi
```

I made a workaround. I added these lines into my `.zshrc` or `.bashrc`

```
remove_from_path() {
  local path_to_remove="$1"
  local path_before
  local result=":${PATH//\~/$HOME}:"
  while [ "$path_before" != "$result" ]; do
    path_before="$result"
    result="${result//:$path_to_remove:/:}"
  done
  result="${result%:}"
  echo "${result#:}"
}
HOST_HOME=$(wslpath "$(wslvar USERPROFILE)")
export PATH=$(remove_from_path "$HOST_HOME/.pyenv/pyenv-win/shims")
```

The `remove_from_path` function was copied from [libexec/pyenv-which](https://github.com/pyenv/pyenv/blob/3d83bcdbef27fd86bd57201ecdeb7132a7a24a93/libexec/pyenv-which#L27-L37). Remember to replace `$HOST_HOME/.pyenv/pyenv-win/shims` with your path of Python executable file on Windows.

**Comment by ApolloTang** [comment] 2024-12-27 11:10
This issue is closed, but I have the same problem using `pyenv 2.5.0`. 
After searching, I realized I must first deactivate pyenv and fix the `python` command and then the pyenv system is working.  I have written my findings [here](https://apollotang.bearblog.dev/0050-fixing-pyenv-version-system-not-installed/)

**Comment by native-api** [comment] 2024-12-29 11:20
> This issue is closed, but I have the same problem using `pyenv 2.5.0`. After searching, I realized I must first deactivate pyenv and fix the `python` command and then the pyenv system is working. I have written my findings [here](https://apollotang.bearblog.dev/0050-fixing-pyenv-version-system-not-installed/)

Currently, OSes typically do not provide the `python` command, only `python3` and sometimes `python2`. This is in accordance with https://peps.python.org/pep-0394/#for-python-runtime-distributors .

So if you don't have system-wide `python`, Pyenv would diligently recite "command not found" for you if you invoke it with `system` selected. This is expected and by design.
