### ISSUE TITLE
Making a pip installed app global

### ISSUE THREAD

**Issue by lucianthorr** [pyenv/pyenv#1467] opened 2019-11-22 16:40 UTC
I think this is a similar question to Issue #34.  
This is a very general question but I'm currently dealing with the AWS CLI, which is a pip-installed application.
If I install it in my global environment, even if I'm in a local virtual environment, pyenv will tell me that 'aws' is only available in the virtual environments that have AWS installed.  It seems like overkill to have to reinstall aws in each environment especially because it is usually not necessary for that environment's application, I just need to use it.

In the past, pyenv let me use 'aws' anywhere but its behavior has changed since I got a new computer.  I'm guessing I was using an older pyenv before.
Does anyone have advice for how to make 'aws' available not matter what the current virtualenv is?
Thanks!

**Comment by mayanksuman** [comment] 2019-12-10 12:11
Similar to #1204

**Comment by native-api** [comment] 2021-05-09 16:40
Duplicate of #1204

**Closed by native-api** 2021-05-09 16:40 UTC
