### ISSUE TITLE
Not able to install python 3.8.13 on M1 OSX 12.15.1 amd64.

### ISSUE THREAD

**Issue by rynslmns** [pyenv/pyenv#2446] opened 2022-09-01 04:35 UTC
Not able to install python 3.8.13 on M1 OSX 12.15.1 amd64. I have attached my trace.log.

### Description
- [x] Platform information (e.g. Ubuntu Linux 16.04): OSX Monterrey 12.5.1
- [x] OS architecture (e.g. amd64): amd64
- [x] pyenv version: 2.3.3
- [x] Python version: 3.8.13
- [x] C Compiler information (e.g. gcc 7.3): 
- [x] Please attach the debug trace of the failing command as a gist: https://gist.github.com/rynslmns/63648a9f9661f987ef5516b99e59087a

**Comment by native-api** [comment] 2022-09-01 16:46
Duplicate of https://github.com/pyenv/pyenv/issues/2441

**Closed by native-api** 2022-09-01 16:46 UTC
