### ISSUE TITLE
cd: <symlink target file>: Not a directory

### ISSUE THREAD

**Issue by HQJaTu** [pyenv/pyenv#1118] opened 2018-03-14 11:48 UTC
File `pyenv` assumes, that it can follow symlinks in `abs_dirname()`:
```bash
  abs_dirname() {
    local path="$1"

    # Use a subshell to avoid changing the current path
    (
    while [ -n "$path" ]; do
      cd "${path%/*}"
      local name="${path##*/}"
      path="$(resolve_link "$name" || true)"
    done

    pwd
    )
  }
```

However, the target file can be a symlink, and it cannot be followed.

Example from Ansible. Listing of `ansible/bin/`:
```
    ansible
    ansible-playbook -> ansible
```

Executing `~/ansible/bin/ansible-playbook` will work, but during it a `~/.pyenv/libexec/pyenv: line 44: cd: ansible: Not a directory` is emitted.

A suggested fix would be:
```bash
      path="$(test -d "$name" && resolve_link "$name" || true)"
```
... to test if the destination is a directory that can be `cd`d into.
If yes, follow that. If not, stop iterating without emitting errors.

**Comment by webknjaz** [comment] 2018-03-15 14:17
Haha :rofl: 
I've just spotted this yesterday, did debugging today and also with `ansible-test` script and going to prepare somewhat similar patch :)

**Comment by webknjaz** [comment] 2018-03-15 14:38
Looks like there's a test for it and it's broken https://travis-ci.org/pyenv/pyenv/jobs/353851590#L523-L529

**Comment by webknjaz** [comment] 2018-03-15 14:41
ref: #379, #404

**Comment by webknjaz** [comment] 2018-03-15 14:51
Okay.. test is not broken, but the fix is imperfect

**Comment by webknjaz** [comment] 2018-03-15 15:16
Got a solution: resolve `pwd` with `--follow` when returning

**Comment by webknjaz** [comment] 2018-03-15 15:21
Pipeline succeeds, dunno how to catch this with a test though.

**Comment by blueyed** [comment] 2018-09-19 08:16
Closing as duplicate of #580.

**Closed by blueyed** 2018-09-19 08:16 UTC
