### ISSUE TITLE
`sys.path` looking up inside `.local` before `.pyenv`??

### ISSUE THREAD

**Issue by ego-thales** [pyenv/pyenv#2722] opened 2023-06-13 12:01 UTC
*Using `pyenv 2.3.18` on `Ubuntu 22.04.2 LTS`.*

I don't understand why inside a `pyenv` virtual environment, python's `sys.path` contains `[...]/.local/lib/pythonX.Y/site-packages`.
I though the whole point of using `pyenv` was to avoid depending on the local installation as much as possible.
What's even werider to me, is that this path is **before** `[...]/.pyenv/versions/X.Y.Z/lib/pythonX.Y/site-packages`. The implication is that even if I use `pip install <package>`, if the package was installed locally prior to me running that command, then python will never see the one it just installed in the virtual environment. Of course, if the locally installed version is not compatible with project, then you run into multiple issues...

I thus have several questions:

- Can you find any documented reference to this behaviour?
- Is it considered bad practise to manually remove `.local` directories from the `sys.path` (I certainly think so)?
- Is there a natural way of dealing with this that I don't know of?

Thank you in advance :pray:

**Comment by native-api** [comment] 2023-06-13 16:14
This is CPython's default for per-user site-packages.

The discussion if and how to change this is ongoing in https://github.com/pyenv/pyenv/issues/2417

**Comment by native-api** [comment] 2023-06-13 16:36
Duplicate of https://github.com/pyenv/pyenv/issues/2417

**Closed by native-api** 2023-06-13 16:36 UTC
