### ISSUE TITLE
pyenv switch to the python files's local python version unexpectedly.

### ISSUE THREAD

**Issue by iclementine** [pyenv/pyenv#1565] opened 2020-03-21 11:21 UTC
Too many issues will kill our team's development velocity, drastically.
Make sure you have checked all steps below.

### Description
- [x] Platform information (Ubuntu Linux 16.04):
- [x] OS architecture (amd64):
- [x] pyenv version:(1.2.15)
- [x] Python version:(3.7.4)
- [x] C Compiler information (e.g. gcc 5.4): 

pyenv switch to the python files's local python version unexpectedly.

When I am in `folder_a`, which has  a `.python-version` that specifies its local python version as `env_a`, so the prompt shows that the current python in use is `env_a`.

Then, I run `python /path/to/folder_b/script.py`, while `folder_b` also has a `.python-version` that specifies its local python version as `env_b`.

The python executable really used in `python /path/to/folder_b/script.py` is `env_b` instead of `env_a`. (First I did not find it util I print the `sys.executable` in the script.)

So is it the expected behavior? Thank you!

**Comment by JMMarchant** [comment] 2020-10-19 10:59
I've similarly just encountered this and must admit I was surprised at this behaviour; I was expecting it to use the `.python-version` from the directory you're running from, not the one where the script was located.

It can be overridden using `pyenv shell` but it would be good to know if this is expected behaviour or a bug.

**Comment by native-api** [comment] 2021-05-19 04:22
Duplicate of https://github.com/pyenv/pyenv/issues/1807

**Closed by native-api** 2021-05-19 04:22 UTC
