### ISSUE TITLE
pyenv install with .python-version and .python-virtualen fails

### ISSUE THREAD

**Issue by Christos-Hadjinikolis** [pyenv/pyenv#1739] opened 2020-11-22 22:54 UTC
This is only partly related to https://github.com/pyenv/pyenv/issues/1737

I have just upgraded to the new MAC OS BigSur. 

I have installed XCode Beta 12.3 and configured it with Command Line Tools 12.3 beta. 

If I do: 
```
$ CFLAGS="-I$(brew --prefix openssl)/include -I$(brew --prefix bzip2)/include -I$(brew --prefix readline)/include -I$(xcrun --show-sdk-path)/usr/include" LDFLAGS="-L$(brew --prefix openssl)/lib -L$(brew --prefix readline)/lib -L$(brew --prefix zlib)/lib -L$(brew --prefix bzip2)/lib" pyenv install --patch 3.8.0 < <(curl -sSL https://github.com/python/cpython/commit/8ea6353.patch\?full_index\=1)
```
as per the instructions of this blog: https://dev.to/kojikanao/install-python-3-8-0-via-pyenv-on-bigsur-4oee It works. 

However, I started using pyenv after finding a very attractive way of managing many python envs through automatic activation as described in this blog: https://glhuilli.github.io/virtual-environments.html

Since I upgraded, I have not been able to get this to work. 

**Questions**:

1. When I cd into a directory with .`python-version` and `.python-virtualenv`, the script prompts me to create a new env with `pyenv install`. This fails with the `./Modules/pwdmodule.c` error. How can I alter the above script in order to create an environment using `.python-version` and `.python-virtualenv`? I can obviously provide a different python version in the script, but what about the name of the virtual environment? How can I include that?
2. I want the new virtual environment contents to be located in the directory where `pyenv` is called and not `/Users/username/.pyenv`. How can this be done? 

i am sure others are facing similar issues. Will these be fixed eventually? Ideally, I would like to be able to just do `pyenv install` and be done... 

Thanks in advance.

**Comment by Christos-Hadjinikolis** [comment] 2020-12-01 20:39
HI all... any updates on this one?

**Comment by native-api** [comment] 2021-03-09 23:25
1. Duplicate of https://github.com/pyenv/pyenv/issues/1737
2. You are confusing Python installations and virtual environments, so this question makes no sense.

**Closed** 2021-05-07 00:30 UTC

**Comment by Christos-Hadjinikolis** [comment] 2021-05-10 20:57
You are right, though it does make sense. It is about automatically switching python-envs. Nothing to do with installation. 

Regardless, the question here is indeed irrelevant. Apologies.
