### ISSUE TITLE
Is it possible to install a Python 3.7.2 shim (using pyenv) on MacOS Monterey?

### ISSUE THREAD

**Issue by paulmattheww** [pyenv/pyenv#2250] opened 2022-02-16 00:33 UTC
I am using pyenv to manage different versions of Python across various projects.

```bash
$ pyenv --version
pyenv 2.2.4
```

I have been able to install the following versions.

```bash
$ pyenv versions
pyenv: version `3.7.2' is not installed (set by /Path/to/project/.python-version)
  system
  3.10.0
  3.7.10
  3.7.9
  3.8.6
  3.8.9
  3.9.1
  3.9.4
```

My system (Macbook Pro) information is as follows:

```bash
$ sw_vers
ProductName:    macOS
ProductVersion: 12.1
BuildVersion:   21C52
```

Global python is set to `Python 3.10.0`.

`gcc` is as follows

```bash
$ gcc --version
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/4.2.1
Apple clang version 13.0.0 (clang-1300.0.29.30)
Target: arm64-apple-darwin21.2.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

It appears the new Macbooks (Monterey) are not compatible with some of the pyenv shims, potentially including 3.7.2, and information on this specific version appears scarce.

There is a lot I do not understand about the new chip architecture.

Running it naively returns:

```bash
$ pyenv install 3.7.2
python-build: use openssl@1.1 from homebrew
python-build: use readline from homebrew
Downloading Python-3.7.2.tar.xz...
-> https://www.python.org/ftp/python/3.7.2/Python-3.7.2.tar.xz
Installing Python-3.7.2...
python-build: use readline from homebrew
python-build: use zlib from xcode sdk

BUILD FAILED (OS X 12.1 using python-build 20180424)

Inspect or clean up the working tree at /var/folders/yx/pmzzwcx527j8gpkq7b7rwyg80000gp/T/python-build.20220215173021.81405
Results logged to /var/folders/yx/pmzzwcx527j8gpkq7b7rwyg80000gp/T/python-build.20220215173021.81405.log

Last 10 log lines:
checking size of _Bool... 1
checking size of off_t... 8
checking whether to enable large file support... no
checking size of time_t... 8
checking for pthread_t... yes
checking size of pthread_t... 8
checking size of pthread_key_t... 8
checking whether pthread_key_t is compatible with int... no
configure: error: Unexpected output of 'arch' on OSX
make: *** No targets specified and no makefile found.  Stop.
```

The following also fails. 

```bash
$ arch -arm64 pyenv install -v 3.7.2
$ arch -x86_64 pyenv install -v 3.7.2
to no avail.
```

Is it possible to use `3.7.2` on these new Macs?

Thank you for your guys' contribution to the Python ecosystem.

**Comment by native-api** [comment] 2022-02-16 00:35
Duplicate of https://github.com/pyenv/pyenv/issues/1737

**Closed by native-api** 2022-02-16 00:35 UTC

**Comment by genewliu** [comment] 2022-02-19 12:40
I have the same issue, #1737 does not resolve this.
