### ISSUE TITLE
BUILD FAILED (OS X 12.7.3 using python-build 20180424)

### ISSUE THREAD

**Issue by cccc9612** [pyenv/pyenv#2912] opened 2024-02-28 00:26 UTC
Tried to install Python 3.9.4 but got the errors below:
![WeChatb1c2626804c8ad084e140f38eaec8d18](https://github.com/pyenv/pyenv/assets/138830429/b38172db-046c-4cc5-a98d-986d690748f7)

I'm using **macOS Monterey Version 12.7.3 (21H1015)** with Processor 2.9 GHz Dual-Core Intel Core i5

**Comment by native-api** [comment] 2024-02-28 00:29
GNU Make doesn't support paths with spaces so we don't support them, either.

**Comment by native-api** [comment] 2024-02-28 00:29
Duplicate of https://github.com/pyenv/pyenv/issues/2738

**Closed by native-api** 2024-02-28 00:29 UTC
