### ISSUE TITLE
"python-build: command not found" when trying to install

### ISSUE THREAD

**Issue by marboledacci** [pyenv/pyenv#3094] opened 2024-10-17 20:59 UTC
Too many issues will kill our team's development velocity, drastically.
Make sure you have checked all steps below.

### Prerequisite
* [x] Make sure your problem is not listed in [the common build problems](https://github.com/pyenv/pyenv/wiki/Common-build-problems).
* [x] Make sure no duplicated issue has already been reported in [the pyenv issues](https://github.com/pyenv/pyenv/issues). You should look for closed issues, too.
* [x] Make sure you are not asking us to help solving your specific issue.
  * GitHub issues is opened mainly for development purposes. If you want to ask someone to help solving your problem, go to some community site like [Gitter](https://gitter.im/yyuu/pyenv), [StackOverflow](https://stackoverflow.com/questions/tagged/pyenv), etc.
* [x] Make sure your problem is not derived from packaging (e.g. [Homebrew](https://brew.sh)).
  * Please refer to the package documentation for the installation issues, etc.
* [x] Make sure your problem is not derived from plugins.
  * This repository is maintaining `pyenv` and the default `python-build` plugin only. Please refrain from reporting issues of other plugins here.

### Description
Platform: Any Docker image running on CircleCI as executor
Pyenv version: 2.4.16
Python versioin: Any
C Compiler: gcc (Debian 8.3.0-6) 8.3.0
Trace.log: https://gist.github.com/marboledacci/0f14c3f34017821201907559da94160c

I'm trying to install python with pyenv in a CircleCI workflow.  The steps I'm doing are:
```bash
export PYENV_ROOT=$HOME/.pyenv
export PATH=$HOME/.pyenv/shims:$HOME/.pyenv/bin:$PATH
export PYTHON_VERSION=3.11.10
export PIPENV_DEFAULT_PYTHON_VERSION=3.11.10

curl https://pyenv.run | bash
pyenv install 3.11.10
```

And I get the following errors:
```
/home/circleci/.pyenv/plugins/python-build/bin/pyenv-install: line 53: python-build: command not found
/home/circleci/.pyenv/plugins/python-build/bin/pyenv-install: line 78: parse_options: command not found
```

Then I tried running `eval "$(pyenv init -)"` but I get the error:
```
/home/circleci/.pyenv/libexec/pyenv-init: line 260: pyenv-commands: command not found
```

I verified the environment variables and they exist and have the right value. 
At least the python-build plugin is there, the parse_options I don't know where should it be.

I suppose the error is related to CircleCI and Docker together, because running Docker locally works, and running non-docker executors in CircleCI works. But all the requirements are met and the environment seems well setup, so this shouldn't be failing.

**Comment by native-api** [comment] 2024-10-18 15:24
There's likely an antivirus in place that falsely detects `python-build`.

We had the same issue reported before: https://github.com/pyenv/pyenv/issues/2603

**Comment by native-api** [comment] 2024-10-18 15:25
Duplicate of https://github.com/pyenv/pyenv/issues/2603

**Closed by native-api** 2024-10-18 15:25 UTC

**Comment by marboledacci** [comment] 2024-10-18 15:52
This is not the same as the antivirus problem, this is not MacOS and there aren't antivirus in the instances and as I mentioned the files are there, nothing is deleted.

**Comment by native-api** [comment] 2024-10-18 15:59
Even though it's not MacOS, it still might have an antivirus of some kind. Maybe rather than deleting files, it prevents their execution.

Anyway, we do add the directory where `python-build` resides to PATH:
```
+(/home/circleci/.pyenv/bin/pyenv:90): export PATH=/home/circleci/.pyenv/libexec:/home/circleci/.pyenv/plugins/python-build/bin:/home/circleci/.pyenv/plugins/pyenv-virtualenv/bin:/home/circleci/.pyenv/plugins/pyenv-update/bin:/home/circleci/.pyenv/plugins/pyenv-doctor/bin:/home/circleci/.pyenv/shims:/home/circleci/.pyenv/bin:/home/circleci/.local/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games
```

so the problem is not on Pyenv's side.
You should contact CircleCI support.
