### ISSUE TITLE
Fix for coexistence with `uv`

### ISSUE THREAD

**Issue by marhoy** [pyenv/pyenv#3128] opened 2024-12-12 13:12 UTC
Our team has been successfully using `pyenv` + `poetry` for a long time to manage our Python-installs and our project dependencies. Recently, we have also started to use `uv` in some projects.

When using `uv`, the content of the `.python-version` file could for instance be `3.13`, and there will not (in general) exist a pyenv virtualenv with that name. This creates problems for the shims in `pyenv`, because it is trying to look for a binary in the specified virtual environment:

<img width="571" alt="image" src="https://github.com/user-attachments/assets/bbcba681-880f-49ce-9dd0-a78e3c1ee5d2" />

If I remove the code from `pyenv-version-name` that raises the exit 1, the problem is solved:

<img width="686" alt="image" src="https://github.com/user-attachments/assets/7c6275bc-f06b-4b7f-b19b-e1e88026cbee" />

Would this have a negative impact on anything else, or would you accept such a patch (or maybe there is a more elegant solution?).

**Comment by native-api** [comment] 2024-12-12 18:11
What does happen inside `pre-commit`? Why does it try to run a nonexistent executable? That looks like the real problem to me.

**Comment by marhoy** [comment] 2024-12-12 20:11
No, there is nothings interesting happening within `pre-commit`, and btw it's not even executed.

What happens is:
1) The pyenv shims is trying to look for the `pre-commit` binary in the virtual environment specified in the `.python-version` file.
2) If it finds it, the bin-directory of that virtualenv is prepended til the PATH, and `pre-commit` is executed from within the virtualenv.
3) If it does not find it in the virtualenv, the PATH is not altered, and `pre-commit` is (potentially) executed from another location (if it exists).

In this case, `pre-commit` is installed in `~/.local/bin`.

The problem is that:
- When `.python-version` contains something that is not a valid pyenv virtualenv (which it will when/if you are using `uv`), the 1) above fails with `exit 1`, because pyenv doesn't find the virtualenv.

What I am proposing is that 1) could just silently ignore that the virtualenv doesn't exist, and continue to look for the binary other places in the PATH.

Is anyone dependant on `pyenv` failing with `exit 1` if `.python-version` contains something that isn't a pyenv virtualenv?

**Comment by native-api** [comment] 2024-12-13 20:18
Okay, that makes sense. There was a similar request before and we even fleshed out some implementation details. Now if only I can find it...

**Comment by marhoy** [comment] 2024-12-14 07:04
Thanks, that would be great if you could fix this! 
From my testing, it seems that deleting 6 lines in `pyenv-version-name` is sufficient to solve the problem.

[pyenv+uv.patch](https://github.com/user-attachments/files/18134789/pyenv%2Buv.patch)

**Comment by native-api** [comment] 2024-12-14 07:21
Okay, here it is: https://github.com/pyenv/pyenv/issues/2680

**Comment by native-api** [comment] 2024-12-14 07:21
Duplicate of https://github.com/pyenv/pyenv/issues/2680

**Closed by native-api** 2024-12-14 07:21 UTC

**Comment by native-api** [comment] 2024-12-14 07:24
Please check the discussion in the linked ticket regarding if you have any more input on the intended behavior.
