### ISSUE TITLE
pyenv install 3.8.13 not work in ubuntu 18.04.5 

### ISSUE THREAD

**Issue by knoude** [pyenv/pyenv#2383] opened 2022-06-02 15:08 UTC
Too many issues will kill our team's development velocity, drastically.
Make sure you have checked all steps below.

### Prerequisite
* [x] Make sure your problem is not listed in [the common build problems](https://github.com/pyenv/pyenv/wiki/Common-build-problems).
* [x] Make sure no duplicated issue has already been reported in [the pyenv issues](https://github.com/pyenv/pyenv/issues). You should look for closed issues, too.
* [x] Make sure you are not asking us to help solving your specific issue.
  * GitHub issues is opened mainly for development purposes. If you want to ask someone to help solving your problem, go to some community site like [Gitter](https://gitter.im/yyuu/pyenv), [StackOverflow](https://stackoverflow.com/questions/tagged/pyenv), etc.
* [x] Make sure your problem is not derived from packaging (e.g. [Homebrew](https://brew.sh)).
  * Please refer to the package documentation for the installation issues, etc.
* [x] Make sure your problem is not derived from plugins.
  * This repository is maintaining `pyenv` and the default `python-build` plugin only. Please refrain from reporting issues of other plugins here.

### Description
- [x] Platform information (e.g. Ubuntu Linux 16.04): Ubunt Linux 18.04.5 
- [x] OS architecture (e.g. amd64): windows10
- [x] pyenv version: 2.2.5, 2.3.1
- [x] Python version: 3.8.13
- [ ] C Compiler information (e.g. gcc 7.3):
- [x] Please attach the debug trace of the failing command as a gist:
  * Run `env PYENV_DEBUG=1 <faulty command> 2>&1 | tee trace.log` and attach `trace.log`. E.g. if you have a problem with installing Python, run `env PYENV_DEBUG=1 pyenv install -v <version> 2>&1 | tee trace.log` (note the `-v` option to `pyenv install`).

[trace.log](https://github.com/pyenv/pyenv/files/8825130/trace.log)

**Comment by native-api** [comment] 2022-06-02 19:19
The attached log is for MacOS rather than Ubuntu.

**Comment by native-api** [comment] 2022-06-02 19:19
Duplicate of https://github.com/pyenv/pyenv/issues/2340

**Closed by native-api** 2022-06-02 19:19 UTC
