### ISSUE TITLE
/usr/bin/env: ‘bash\r’: Permission denied

### ISSUE THREAD

**Issue by mzhadigerov** [pyenv/pyenv#2949] opened 2024-04-26 13:33 UTC
I was working with pyenv since 2021 and I don't really remember how I installed it back then.
Today (for some reason) I decided to update it.

So I removed the existing `\home\user\.pyenv` directory and did:

```
git clone https://github.com/pyenv/pyenv.git ~/.pyenv
```
After whenever I open my Ubuntu terminal, I'm seeing:

```
/usr/bin/env: ‘bash\r’: Permission denied
```

When I type:

```
pyenv
```

I also get:

```
/usr/bin/env: ‘bash\r’: Permission denied
```

Maybe this issue is not directly related to `pyenv`, but I could not find any helpful solution in the Internet.

I'm using Ubuntu 20.4 under WSL2, Windows 11

**Comment by native-api** [comment] 2024-04-26 18:41
Duplicate of https://github.com/pyenv/pyenv/issues/1725

**Comment by native-api** [comment] 2024-04-26 18:41
See https://github.com/pyenv/pyenv/issues/1725#issuecomment-724689291

**Closed by native-api** 2024-04-26 18:41 UTC

**Comment by Etrama** [comment] 2024-10-18 17:27
FWIW, if someone runs into this in the future, the source of the issue may also be in your ~/.bashrc file. 
In my case, I was using an alias called `git`. 
I am / I was running git on WSL .
The reason for the alias for git was that git would rebuild index on every invocation on WSL, which is annoying. To get rid, of it, I used `git` as an alias for `git.exe`. Worked for while, till it didn't. When it didn't I had the issue mentioned here.
Removing this alias solved the issue.
