### ISSUE TITLE
Do not change PATH unnecessarily / multiple times

### ISSUE THREAD

**Issue by silenc3r** [pyenv/pyenv#969] opened 2017-08-18 21:53 UTC
```eval "$(pyenv init -)"``` prepends PATH variable with ```${PYENV_ROOT}/shims``` every time it is executed.

If you have ```eval "$(pyenv init -)"``` in your ```~/.bashrc``` and run tmux then you have ```${PYENV_ROOT}/shims``` appear twice in your PATH.  

It's a minor nitpick but it's easily solvable with adding something like:

    if [[ ! "$PATH" == "*${PYENV_ROOT}/shims*" ]]; then
        ...code modifying PATH...
    fi

to scripts modifying PATH

**Comment by blueyed** [comment] 2017-08-19 00:38
PR welcome.

But in general it is recommended to call it in your shell's profile, and not rc file.

**Comment by blueyed** [comment] 2017-08-19 00:40
btw: as for Zsh: $PATH/$path is typically setup to have unique entries.
There it is a matter of not prepending it before other entries then.

**Comment by blueyed** [comment] 2017-08-19 00:46
The PR should probably get done against rbenv then also, so that it can be merged from there.

**Comment by silenc3r** [comment] 2017-08-19 11:08
Tmux for some reason spawns login shell by default so putting pyenv init in shell's profile doesn't change anything in that case.

**Comment by blueyed** [comment] 2017-08-19 12:11
True.

I am using this in my tmux.conf: `set -g default-command "exec $SHELL"`

**Comment by darkfishy** [comment] 2017-08-22 04:56
**Assumption**: Using BASH for $SHELL

I would suggest against calling `$(pyenv init -)` in either *.bash_profile* or *.profile* because, by design, BASH doesn't call *.\*profile* unless it is a login shell. However, if chained properly, `.bashrc` can get called for both login and interactive shells. See below for examples.

    ~/ $ bash
    Activating .bashrc
    ~/ $ bash -l
    Activating .bash_profile
    Activating .profile
    Activating .bashrc
    ~/ $

@silenc3r: Does your way work without uglifying `$PATH`?

**Comment by jack-pace** [comment] 2019-08-06 14:45
For what it's worth, if you are using `pyenv-virtualenv` you don't have a choice here. You need to run `eval $(pyenv init -)` in your `.bashrc`, else the `pyenv` _function_ is not defined in the tmux shell and you cannot run `pyenv activate ...`.

> Failed to activate virtualenv.
> 
> Perhaps pyenv-virtualenv has not been loaded into your shell properly.
> Please restart current shell and try again.

**Comment by native-api** [comment] 2021-05-08 05:04
Duplicate of https://github.com/pyenv/pyenv/issues/1649

**Closed by native-api** 2021-05-08 05:04 UTC
Labels: type: enhancement
