### ISSUE TITLE
Wiki update request: Python requirements on void linux

### ISSUE THREAD

**Issue by llimllib** [pyenv/pyenv#1653] opened 2020-07-04 15:38 UTC
I had to figure out the build requirements for python on void linux, and I wanted to add to the wiki but I'm not able to update it. Can somebody add Void Linux to the Suggested Build Environments page for me? https://github.com/pyenv/pyenv/wiki#suggested-build-environment

Here's what's required on Void:

`sudo xbps-install bzip2-devel libffi-devel libressl-devel libxml2-devel readline readline-devel sqlite-devel zlib-devel`

**Comment by native-api** [comment] 2021-05-17 08:08
Duplicate of https://github.com/pyenv/pyenv/issues/1923

**Closed by native-api** 2021-05-17 08:08 UTC
