### ISSUE TITLE
Can't install any version on M1 Mac - error: internal configure error for the platform triplet, please file a bug report

### ISSUE THREAD

**Issue by phalladar** [pyenv/pyenv#2317] opened 2022-04-07 01:52 UTC
- [x] Platform information: Monterey 12.3.1
- [x] OS architecture: arm64
- [x] pyenv version: pyenv 2.2.5-11-gf0f2cdd1
- [x] C Compiler information (e.g. gcc 7.3):  Apple clang version 13.1.6 (clang-1316.0.21.2) / Target: arm64-apple-darwin21.4.0
- [x] Please attach the debug trace of the failing command as a gist: [trace.log
](https://gist.github.com/phalladar/548818802b6602ae095afb22f7bed076)

I've tried to follow some similar issues like #2171 && #2317 with no luck.

```
-> https://www.python.org/ftp/python/3.10.0/Python-3.10.0.tar.xz
Installing Python-3.10.0...
patching file aclocal.m4
patching file configure
Hunk #5 succeeded at 10537 (offset -15 lines).
python-build: use readline from homebrew
python-build: use zlib from xcode sdk

BUILD FAILED (OS X 12.3.1 using python-build 2.2.5-11-gf0f2cdd1)

Inspect or clean up the working tree at /var/folders/bn/mg28qrzs4x16vtzldg13518sfpjw92/T/python-build.20220406214712.10629
Results logged to /var/folders/bn/mg28qrzs4x16vtzldg13518sfpjw92/T/python-build.20220406214712.10629.log

Last 10 log lines:
checking for --with-cxx-main=<compiler>... no
checking for clang++... no
configure:

  By default, distutils will build C++ extension modules with "clang++".
  If this is not intended, then set CXX on the configure command line.

checking for the platform triplet based on compiler characteristics... darwin
configure: error: internal configure error for the platform triplet, please file a bug report
make: *** No targets specified and no makefile found.  Stop.
```

[Full config.log here](https://gist.github.com/phalladar/6299e389c5d76e993437cdfbeb235017). 

Thanks!

**Comment by PipeKnight** [comment] 2022-04-12 10:40
Recently I had the same problem, I couldn't install any python version with Pyenv on my M1 Pro. I tried lots of hacks mentioned in issues: patches, flags, reinstalling zlib, bzip and so on, resetting xcode-command-line-tools. Nothing worked. But then my friend told me I should install the Xcode itself from App Store. And lol, that worked!

Just install Xcode and run ```pyenv install 3.7.13```
(works with all latest revisions supported by pyenv such as 3.7.13, 3.8.13, 3.9.11, 3.10.3, etc.)

**Comment by phalladar** [comment] 2022-04-13 13:40
@PipeKnight no dice for me unfortunately. I'm actually an iOS engineer so Xcode is good to go already, heh.

**Comment by native-api** [comment] 2022-04-14 11:15
Duplicate of https://github.com/pyenv/pyenv/issues/2143

**Closed by native-api** 2022-04-14 11:15 UTC

**Comment by Jokky6** [comment] 2022-08-25 03:16
> Recently I had the same problem, I couldn't install any python version with Pyenv on my M1 Pro. I tried lots of hacks mentioned in issues: patches, flags, reinstalling zlib, bzip and so on, resetting xcode-command-line-tools. Nothing worked. But then my friend told me I should install the Xcode itself from App Store. And lol, that worked!
> 
> Just install Xcode and run `pyenv install 3.7.13` (works with all latest revisions supported by pyenv such as 3.7.13, 3.8.13, 3.9.11, 3.10.3, etc.)

can you show me your python arch? x86 or arm64

use the command:
```shell
file -L $(python -c 'import sys; print(sys.executable)')
```

I use pyenv install python x86 successful,but python arm64 failed

**Comment by PipeKnight** [comment] 2022-08-26 17:28
> can you show me your python arch? x86 or arm64

`~/.pyenv/versions/3.8.13/bin/python: Mach-O 64-bit executable arm64`
