### ISSUE TITLE
Install Python 3.7.12 Failed on macOS 12.3.1

### ISSUE THREAD

**Issue by MarkVLK** [pyenv/pyenv#2306] opened 2022-04-01 04:27 UTC
Too many issues will kill our team's development velocity, drastically.
Make sure you have checked all steps below.

### Prerequisite
* [X] Make sure your problem is not listed in [the common build problems](https://github.com/pyenv/pyenv/wiki/Common-build-problems).
* [X] Make sure no duplicated issue has already been reported in [the pyenv issues](https://github.com/pyenv/pyenv/issues). You should look for closed issues, too.
* [X] Make sure you are not asking us to help solving your specific issue.
  * GitHub issues is opened mainly for development purposes. If you want to ask someone to help solving your problem, go to some community site like [Gitter](https://gitter.im/yyuu/pyenv), [StackOverflow](https://stackoverflow.com/questions/tagged/pyenv), etc.
* [X] Make sure your problem is not derived from packaging (e.g. [Homebrew](https://brew.sh)).
  * Please refer to the package documentation for the installation issues, etc.
* [X] Make sure your problem is not derived from plugins.
  * This repository is maintaining `pyenv` and the default `python-build` plugin only. Please refrain from reporting issues of other plugins here.

### Description
- [X] Platform information (e.g. Ubuntu Linux 16.04): **macOS 12.3.1**
- [X] OS architecture (e.g. amd64): **x86_64**
- [X] pyenv version: **pyenv 2.2.5**
- [X] Python version: **Python 3.7.12**
- [X] C Compiler information (e.g. gcc 7.3): **Apple clang version 13.1.6 (clang-1316.0.21.2)**
- [X] Please attach the debug trace of the failing command as a gist: [gist](https://gist.github.com/MarkVLK/3852460aa553740f68d42e38cc5d296c)
  * Run `env PYENV_DEBUG=1 <faulty command> 2>&1 | tee trace.log` and attach `trace.log`. E.g. if you have a problem with installing Python, run `env PYENV_DEBUG=1 pyenv install -v <version> 2>&1 | tee trace.log` (note the `-v` option to `pyenv install`).

**Comment by native-api** [comment] 2022-04-01 07:19
Duplicate of https://github.com/pyenv/pyenv/issues/2143

**Comment by native-api** [comment] 2022-04-01 07:20
Either upgrade to 3.7.13 or update Pyenv to the head version which has a backported patch for 3.7.12 to support XCode 13.3.

**Closed by native-api** 2022-04-01 07:20 UTC
