### ISSUE TITLE
Consider adding install <version> commands to the initial README block

### ISSUE THREAD

**Issue by benjaminapetersen** [pyenv/pyenv#1171] opened 2018-06-15 19:10 UTC
This is entirely a UX issue & a suggestion for a minor improvement to the docs via the README.

It would be helpful to lead out the [terminal output](https://github.com/pyenv/pyenv/blob/master/terminal_output.png) screenshot with examples of installing a few versions of Python, as a brand new user would want to do when they initially `brew install pyenv` (or whatever method chosen to install), followed by the existing toggles.  This would help clarify immediately what the tool is actually doing.  Seeing examples of version toggling w/o seeing how you install the versions first is slightly un-intuitive.

Thanks for considering!

**Comment by native-api** [comment] 2021-05-08 02:44
Duplicate of https://github.com/pyenv/pyenv/issues/1677

**Closed by native-api** 2021-05-08 02:44 UTC
Labels: type: documentation
