### ISSUE TITLE
Test setup refactoring

### ISSUE THREAD

**Issue by ChristianFredrikJohnsen** [pyenv/pyenv#3131] opened 2024-12-15 04:29 UTC
Too many issues will kill our team's development velocity, drastically.
Make sure you have checked all steps below.

### Prerequisite
* [x] Make sure your problem is not listed in [the common build problems](https://github.com/pyenv/pyenv/wiki/Common-build-problems).
* [x] Make sure no duplicated issue has already been reported in [the pyenv issues](https://github.com/pyenv/pyenv/issues). You should look for closed issues, too.
* [x] Make sure you are not asking us to help solving your specific issue.
  * GitHub issues is opened mainly for development purposes. If you want to ask someone to help solving your problem, go to some community site like [Gitter](https://gitter.im/yyuu/pyenv), [StackOverflow](https://stackoverflow.com/questions/tagged/pyenv), etc.
* [x] Make sure your problem is not derived from packaging (e.g. [Homebrew](https://brew.sh)).
  * Please refer to the package documentation for the installation issues, etc.
* [x] Make sure your problem is not derived from plugins.
  * This repository is maintaining `pyenv` and the default `python-build` plugin only. Please refrain from reporting issues of other plugins here.

### Description
- [x] Platform information (e.g. Ubuntu Linux 16.04): Ubuntu Linux 24.10
- [x] OS architecture (e.g. amd64): amd64
- [x] pyenv version: 2.4.22
- [x] Python version: 3.13.1
- [x] C Compiler information (e.g. gcc 7.3): gcc 14.2
- [x] Please attach the debug trace of the failing command as a gist:
  * Run `env PYENV_DEBUG=1 <faulty command> 2>&1 | tee trace.log` and attach `trace.log`. E.g. if you have a problem with installing Python, run `env PYENV_DEBUG=1 pyenv install -v <version> 2>&1 | tee trace.log` (note the `-v` option to `pyenv install`).
- [x] If you have a problem with installing Python, please also attach `config.log` from the build directory
  * The build directory is reported after the "BUILD FAILED" message and is usually under `/tmp`.
- [x] If the build succeeds but the problem is still with the build process (e.g. the resulting Python is missing a feature), please attach
  * the debug trace from reinstalling the faulty version with `env PYENV_DEBUG=1 pyenv install -f -k -v <version> 2>&1 | tee trace.log`
  * `config.log` from the build directory. When using `pyenv install` with `-k` as per above, the build directory will be under `$PYENV_ROOT/sources`.

I have tried making performance improvements on pyenv-init in my own fork, referring to #3037.
But what I end up doing is spending a few hours writing code, but an excessive amount of time trying to understand the tests.

From what I can see, the majority of tests seem to simply be imported from 11 years ago, and haven't been changed since. Take this test for example in `commands.bats`

```bash
### This is too stupid. The guy who wrote the tests clearly did
# not understand how the test setup works.
# The path with spaces has no effect on the test.
# The only reason why the test passes at all is because the
# user running the script already has pyenv installed
# and added to the path.
@test "commands in path with spaces" {
  path="${PYENV_TEST_DIR}/my commands"
  cmd="${path}/pyenv-sh-hello"
  mkdir -p "$path"
  touch "$cmd"
  chmod +x "$cmd"

  PATH="${path}:$PATH"
  echo "This is my path: $PATH"
  run pyenv-commands --sh
  assert_success
  assert_line "hello"
}
```

Clearly, the idea is to create a path folder which has spaces in it, but from what I can understand, this path they are creating is not being used at all, instead the test passes because pyenv is already installed on my computer, and the test defaults to using this path variable:   `PATH="${BATS_TEST_DIRNAME}/../libexec:$PATH"`
And at the same time you have a supposed `test folder` in /tmp/pyenv.XXX (e. g. /tmp/pyenv.zVT)

End result is that you are using ~/.pyenv/libexec/pyenv-commands
to find /tmp/pyenv.zVT/my commands/pyenv-sh-hello

which is such an unrealistic case. I am trying to make optimizations by only scanning `PYENV_ROOT` (e. g. ~/.pyenv)
but this is impossible to do when the testing system is detached from any reasonable setup:

```
✗ commands in path with spaces
   (from function `flunk' in file test/test_helper.bash, line 46,
    from function `assert_line' in file test/test_helper.bash, line 91,
    in test file test/commands.bats, line 40)
     `assert_line "hello"' failed
   This is my path: /tmp/pyenv.Lta/my commands:/tmp/pyenv.Lta/root/shims:/home/christian/.pyenv/test/libexec:/home/christian/.pyenv/test/../libexec:/tmp/pyenv.Lta/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin
   expected line `hello'
    output:
```

In this case, the test fails because PYENV_ROOT is set to /tmp/pyenv.zVT/root (a folder which doesn't even exist).

Even worse, you have this test:

```
@test "commands --sh" {
  run pyenv-commands --sh
  echo "This is my path: $PATH"
  assert_success
  refute_line "init"
  assert_line "shell"
}
```

With following output with my optimizations:

```
✗ commands --sh
   (from function `flunk' in file test/test_helper.bash, line 46,
    from function `assert_line' in file test/test_helper.bash, line 91,
    in test file test/commands.bats, line 20)
     `assert_line "shell"' failed
   This is my path: /tmp/pyenv.Lta/root/shims:/home/christian/.pyenv/test/libexec:/home/christian/.pyenv/test/../libexec:/tmp/pyenv.Lta/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin
   expected line `shell'
    output:
 ```

And this of course fails because all we have is a folder `/tmp/pyenv.zVT`, which just exists. And we have set the non-existent `/tmp/pyenv.zVT/root` as root folder, ...

The setup makes my brain hurt. From my point of view, we should do something like `git clone` the pyenv project into the temporary folder which is made by `test_helper.bash`:

```

# guard against executing this block twice due to bats internals
if [ -z "$PYENV_TEST_DIR" ]; then
  PYENV_TEST_DIR="${BATS_TMPDIR}/pyenv"
  export PYENV_TEST_DIR="$(mktemp -d "${PYENV_TEST_DIR}.XXX" 2>/dev/null || echo "$PYENV_TEST_DIR")"

  if enable -f "${BATS_TEST_DIRNAME}"/../libexec/pyenv-realpath.dylib realpath 2>/dev/null; then
    export PYENV_TEST_DIR="$(realpath "$PYENV_TEST_DIR")"
  else
    if [ -n "$PYENV_NATIVE_EXT" ]; then
      echo "pyenv: failed to load \`realpath' builtin" >&2
      exit 1
    fi
  fi

  ### Clearly this must be redone, get pyenv
  # into standard directory path
  # and then clone the repo into the
  # standard path
  export PYENV_ROOT="${PYENV_TEST_DIR}/root"
  export HOME="${PYENV_TEST_DIR}/home"
  export PYENV_HOOK_PATH="${PYENV_ROOT}/pyenv.d"

  PATH=/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin
  PATH="${PYENV_TEST_DIR}/bin:$PATH"
  PATH="${BATS_TEST_DIRNAME}/../libexec:$PATH"
  PATH="${BATS_TEST_DIRNAME}/libexec:$PATH"
  PATH="${PYENV_ROOT}/shims:$PATH"
  export PATH

  for xdg_var in `env 2>/dev/null | grep ^XDG_ | cut -d= -f1`; do unset "$xdg_var"; done
  unset xdg_var
fi
```

EDIT: We don't even need `git clone`, we simply do a `sudo cp BATS_DIRNAME/.. PYENV_TEST_DIR`. I think that would solve a bunch of problems. Of course, then we would need to make the new setup compatible with all the other tests (there are 204 of them), but this needs to be done. Not the most flashy thing, but this needs to be done to avoid spending 2 hours on code and 15 hours on tests 🥲💀

I don't know how that would be done, but I am sure I could make it work. But of course, this will be a rather major change, and I won't do it unless there is support for this. In my opinion though, it's impossible to make any good code because the tests don't really reflect real-world scenarios, and it's questionable to me whether many people actually understand how they work? They haven't been touched in 11 years, and they don't seem to work as intended at all.

And by the way, I don't know how many assumptions I can make about user setups and so forth. Is it reasonable to assume that all relevant pyenv-binaries are in PYENV_ROOT (e. g. ~/.pyenv)? Of course, you don't want to break something which already works, but here we have a situation where it takes 100ms+ to do `pyenv init -` , partly because we do things like *scan the whole $PATH` variable for `pyenv-` commands*, when clearly, it's much faster to just look in standard folders.

**Comment by ChristianFredrikJohnsen** [comment] 2024-12-15 04:53
You can get some decent speedup (and haven't looked at all yet), if you use reasonable options like `--no-rehash` and `--no-push-path` (but remember to add PYENV_ROOT/shims to path manually in ~/.zshrc).

The first two runs are with optimizations and the last two are without. Most speedup comes from choosing the right options in init:

![Bildschirmfoto vom 2024-12-15 05-50-57](https://github.com/user-attachments/assets/ac8ef697-c80b-42b6-8a3c-11ef9da395be)

**Comment by native-api** [comment] 2024-12-15 09:50
> the test passes because pyenv is already installed on my computer

Yes, the tests assume that Pyenv is installed. They can be isolated, we just never saw a need to.

Most if not all current tests are integration and system tests, and that facilitates running code in real-world conditions. We do want to see the effects of diffierent supported environments when testing locally and in CI -- because they constantly change in unknown ways with each update, and we'd rather not manually track and mock all the changes. We do mock OS detection logic, but only to be able to run all tests in all environments -- that makes testing a change locally much faster and e.g. we do not have FreeBSD in CI.

Even more importantly, that allows us to reproduce and diagnose a problem in real-world conditions (a lack of that opton in most environments is a bane of sysadmins everywhere, including myself), fix it and test the fix all in the same codebase (thanks to Bash being an interpreted language).

If you do wish to test Pyenv in an isolated environment, all you have to do is start a clean shell and/or remove current Pyenv-related stuff from the shell, and run stock shell setup code. Then you can run `make <whatever>`.

> an excessive amount of time trying to understand the tests.

You are not the only one. I spent it too when I took up the maintenance. Bats (at least the version we use) doesn't seem to provide an easy way to trace/diagnose tests. I manually add `export PYENV_DEBUG=1` and/or `export PS4=<...>; set -x; <...> set +x` to the test's code and/or the code of helper scripts and look at `assert_output`'s error message for the trace whenever I don't understand what's happening. When I first studied Bats' workings, I ran Bats itself with tracing.

**Comment by native-api** [comment] 2024-12-15 12:56
> From my point of view, we should do something like git clone the pyenv project into the temporary folder which is made by `test_helper.bash`

There's no need because the Pyenv codebase doesn't change durung tests.
What does change is the work data under `$PYENV_ROOT` (which coincides with the installation prefix in the default per-user installation -- but internally, it's a distinct thing, Pyenv searches for its executable parts via `$BASH_SOURCE` rather than `$PYENV_ROOT`).
So tests rather reassign `$PYENV_ROOT` to under the per-test temporary directory.

**Comment by ChristianFredrikJohnsen** [comment] 2024-12-15 13:35
I'll take a deeper look at this in a couple of days. It might very well be that I have missed some of your points, but what I am currently thinking is that I will do:

```
root="$(cd $BATS_TEST_DIRNAME/.. && pwd)"
export PYENV_ROOT=$root
```

In the tests which are currently failing.

I am writing code which relies on PYENV_ROOT to find executables, but when PYENV_ROOT is set to the non-existent folder `export PYENV_ROOT="${PYENV_TEST_DIR}/root"`, the code doesn't find any executables.

Alternatively, I can copy all the libexec shell-scripts to the temporary folder, but that might just be unnecessarily complex. I guess I am just a bit frustrated by the fact that we are setting up a *clean environment* which we can test in, but don't use it. It does feel wrong to set up a test-dir, but then just override it altogether by setting `PYENV_ROOT="$(cd $BATS_TEST_DIRNAME/.. && pwd)"`

**Comment by native-api** [comment] 2024-12-15 13:43
Not sure what you're trying to do, where the "code that you're writing" is supposed to work.

Normally, you should not search for executables at all. Inside a test's code, they are supposed to already be on PATH, and you're supposed to invoke e.g. `pyenv-prefix` rather than `pyenv prefix`.

**Comment by native-api** [comment] 2024-12-15 13:47
If you provide the diagnostic details as per the issue template of how you're trying to run tests, I should be able to say what you're doing wrong.

**Comment by ChristianFredrikJohnsen** [comment] 2024-12-15 14:04
```
#!/usr/bin/env bash
# Summary: List all available pyenv commands
# Usage: pyenv commands [--sh|--no-sh]

set -e
[ -n "$PYENV_DEBUG" ] && set -x

# Provide pyenv completions
if [ "$1" = "--complete" ]; then
  echo --sh
  echo --no-sh
  exit
fi

if [ "$1" = "--sh" ]; then
  sh=1
  shift
elif [ "$1" = "--no-sh" ]; then
  nosh=1
  shift
fi

IFS=: paths=($PATH)
shopt -s nullglob

pyenv_sh_commands() { # Speedy variant for pyenv-init
  for path in "${paths[@]}"; do
    if [[ "$path" == "${PYENV_ROOT}"* && "$path" != */shims ]]; then
      for command in "${path}/pyenv-sh-"*; do
        echo "${command##*pyenv-sh-}"
      done
    fi
  done
}

if [ -n "$sh" ]; then
  pyenv_sh_commands
else
{ for path in "${paths[@]}"; do
    for command in "${path}/pyenv-"*; do
      command="${command##*pyenv-}"
      if [ -n "$nosh" ]; then
        if [ "${command:0:3}" != "sh-" ]; then
          echo "${command##sh-}"
        fi
      else
        echo "${command##sh-}"
      fi
    done
  done
} | sort -u
fi
```


Sorry, should probably attach the code I am working. Can probably link to my fork as well (?) https://github.com/ChristianFredrikJohnsen/pyenv
Haven't done any PRs or Issues on public repos on github before 😅

Essentially, I find it reasonable to assume that the shell-scripts which the user can run are located inside their `pyenv` folder. So when searching for pyenv-executables, you don't need to search through stuff like `/usr/bin` for pyenv- scripts.

I therefore check if the folder is a sub-dir of `PYENV_ROOT` before going through the files and checking if they are `pyenv-` commands. But when the `PYENV_ROOT` is set to /tmp/pyenv.zVT/root` (a folder which doesn't exist), the `pyenv-commands` script doesn't find any commmands.

Then again, I don't know how much I am allowed to alter the tests. For all I know, it might be that some people have decided to put their shell-scripts in folders other than the ~/.pyenv/ folder somehow? I am trying to squeeze out every ms of optimization.

You can even do a better optimization than this, and just hard-code `sh-`commands into pyenv-init, as is proposed in the fork from varikin:

```
case "\$command" in
  ${commands[*]:-/})
  activate|deactivate|rehash|shell)
    eval "\$(pyenv "sh-\$command" "\$@")"
    ;;
  *)
  ```
  
Here the sh- commands are simply set to `activate`, `deactivate`, `rehash`, `shell`. But what if some user has some custom `sh-` function (etc).
 
When optimizing, I am seeing that there is a clash between speed and modularity/flexibility, and it's slightly hard to know what optimizations are OK and which are not.

**Comment by native-api** [comment] 2024-12-15 17:07
> Essentially, I find it reasonable to assume that the shell-scripts which the user can run are located inside their pyenv folder. So when searching for pyenv-executables, you don't need to search through stuff like /usr/bin for pyenv- scripts.

This may not always be true. E.g. in the `pyenv-virtualenv` Homebrew package, "`pyenv-virtualenv`" is added to `$(brew --prefix)/bin` which is outside of its `pyenv` package installation. That may be a questionable decision since running it directly is not officially supported, but that's how it currently is.

> I therefore check if the folder is a sub-dir of `PYENV_ROOT` before going through the files and checking if they are `pyenv-` commands. But when the `PYENV_ROOT` is set to /tmp/pyenv.zVT/root`(a folder which doesn't exist), the`pyenv-commands` script doesn't find any commmands.

Check `pyenv` launcher's code on which directories it adds to PATH. Those are the real places where subcommands are supposed to reside.

Rather than trying to reduce the number of loop interations (and due to the above), it's probably more productive to do away with the loop altogether and glob all the PATH entries for `pyenv-sh-*` at the same time! This will likely save time by moving the looping out of slow Bash code and into fast C code of a Bash builtin implementation.

**Comment by native-api** [comment] 2024-12-15 17:32
> glob all the PATH entries for `pyenv-sh-*` at the same time!

E.g. `find -path` is _specifically designed_ for this task!

**Comment by native-api** [comment] 2024-12-15 18:23
> Here the sh- commands are simply set to `activate`, `deactivate`, `rehash`, `shell`. But what if some user has some custom `sh-` function (etc).

Moreover, `activate` and `deactivate` will be absent if the Pyenv-Virtualenv plugin is not installed. And there might emerge `pyenv-sh-rehash` some time in the future in order to fix https://github.com/pyenv/pyenv/issues/2732

**Comment by ChristianFredrikJohnsen** [comment] 2024-12-16 02:22
```
Check pyenv launcher's code on which directories it adds to PATH. Those are the real places where subcommands are supposed to reside.

Rather than trying to reduce the number of loop iterations (and due to the above), it's probably more productive to do away with the loop altogether and glob all the PATH entries for pyenv-sh-* at the same time! This will likely save time by moving the looping out of slow Bash code and into fast C code of Bash (or something else's) implementation.
```

Sounds like a good idea. I am seeing that the custom binary paths are added here in `./libexec/pyenv`

```

bin_path="$(abs_dirname "$0")"
for plugin_bin in "${bin_path%/*}"/plugins/*/bin; do
  PATH="${plugin_bin}:${PATH}"
done
# PYENV_ROOT can be set to anything, so it may happen to be equal to the base path above,
# resulting in duplicate PATH entries
if [ "${bin_path%/*}" != "$PYENV_ROOT" ]; then
  for plugin_bin in "${PYENV_ROOT}"/plugins/*/bin; do
    PATH="${plugin_bin}:${PATH}"
  done
fi
export PATH="${bin_path}:${PATH}"
```

But to me it already looks like it assumes pyenv-virtualenv and other plugins are inside `PYENV_ROOT/plugins/ ...`
I will take a deeper look at this from around thursday. Gut feeling is that it would be nice to have a standardized folder structure, similar to the one you get by doing `pyenv.run`:

```
#!/bin/bash # # Usage: curl https://pyenv.run | bash # # For more info, visit: https://github.com/pyenv/pyenv-installer # index_main() { set -e curl -s -S -L https://raw.githubusercontent.com/pyenv/pyenv-installer/master/bin/pyenv-installer | bash } index_main
```

Introduce some breaking change which will probably hurt at the moment, but which will be very beneficial for future development. The only breaking change though being that people will need to move their plugins to the `PYENV_ROOT/plugins` folder, (and then fix the homebrew pyenv-virtualenv installation). 

I can find the time to work on this if this is desired.

**Closed** 2024-12-18 05:26 UTC
