### ISSUE TITLE
pyenv install fails on OS X 14.0 (Sonoma) for multiple inputs

### ISSUE THREAD

**Issue by eikopf** [pyenv/pyenv#2809] opened 2023-10-03 09:59 UTC
I tried installing both 3.12 and 3.7.14 (on the assumption that an older version wouldn't fail), but it looks like the issue is with OS compatibility.

### Description
- OS X 14.0 (Sonoma)
- M1 (aarch64)
- pyenv 2.3.28
[trace.log](https://github.com/pyenv/pyenv/files/12791241/trace.log)
[python-build.20231003104551.12811.log](https://github.com/pyenv/pyenv/files/12791248/python-build.20231003104551.12811.log)
[python-build.20231003105618.18063.log](https://github.com/pyenv/pyenv/files/12791279/python-build.20231003105618.18063.log)

```fish
❯ pyenv install 3.7.14
python-build: use openssl@1.1 from homebrew
python-build: use readline from homebrew
Downloading Python-3.7.14.tar.xz...
-> https://www.python.org/ftp/python/3.7.14/Python-3.7.14.tar.xz
error: failed to download Python-3.7.14.tar.xz

BUILD FAILED (OS X 14.0 using python-build 2.3.28)

Results logged to /var/folders/r9/xzr438h50js1hb82xtj5p1q00000gn/T/python-build.20231003105618.18063.log

Last 10 log lines:
	29  dyld                                0x000000018443bb14 _ZNK5dyld416JustInTimeLoader15runInitializersERNS_12RuntimeStateE + 36
	30  dyld                                0x0000000184435b4c _ZNK5dyld46Loader23runInitializersBottomUpERNS_12RuntimeStateERN5dyld35ArrayIPKS0_EE + 220
	31  dyld                                0x0000000184439654 _ZZNK5dyld46Loader38runInitializersBottomUpPlusUpwardLinksERNS_12RuntimeStateEENK3$_1clEv + 112
	32  dyld                                0x0000000184435ccc _ZNK5dyld46Loader38runInitializersBottomUpPlusUpwardLinksERNS_12RuntimeStateE + 304
	33  dyld                                0x000000018445aad4 _ZN5dyld44APIs25runAllInitializersForMainEv + 464
	34  dyld                                0x000000018441df34 _ZN5dyld4L7prepareERNS_4APIsEPKN5dyld313MachOAnalyzerE + 3192
	35  dyld                                0x000000018441cf44 start + 1948
)
libc++abi: terminating due to uncaught exception of type NSException
/Users/oliver/.pyenv/plugins/python-build/bin/python-build: line 365: 18132 Abort trap: 6           aria2c --allow-overwrite=true --no-conf=true -d "${dir_out}" -o "${out}" ${ARIA2_OPTS} "$1" 1>&4
```

**Comment by anton-petrov** [comment] 2023-10-03 10:53
Duplicate of #2805

**Closed by anton-petrov** 2023-10-03 10:53 UTC
