### ISSUE TITLE
pyenv prepends /usr/bin to PATH, breaks custom PATH

### ISSUE THREAD

**Issue by CyberShadow** [pyenv/pyenv#1158] opened 2018-05-08 01:31 UTC
This problem can be reproduced on Travis CI (Docker image travisci/ci-garnet:packer-1512502276-986baf0).

There, `which python` resolves to `/opt/pyenv/shims/python`, so, a script that has a `#!/usr/bin/env python` shebang will use pyenv.

The problem occurs when I need the program to use a toolchain in a custom prefix instead of `PATH`, i.e.:

```shell
$ PATH=/path/to/my/toolchain/bin:$PATH path/to/python/script.py
```

This isn't working, because pyenv is prepending `/usr/bin` to PATH, thus canceling the effect of the PATH assignment on the command line.

Looking at the code, the problem seems to occur in `pyenv-exec`: `PYENV_COMMAND_PATH` gets resolved to `/usr/bin/python`, and `PYENV_BIN_PATH` thus to `/usr/bin`, which is then prepended to the PATH a bit lower in the same script.

**Comment by blueyed** [comment] 2018-06-04 20:54
See https://github.com/pyenv/pyenv/pull/1169.

**Comment by CyberShadow** [comment] 2018-06-04 21:05
Thanks, good to know there is work to improve the situation.

I ran into this while debugging things three levels deep, so I don't have a use case any more, but it's nice if others could avoid falling into this pit in the future.

**Comment by BenWhetton** [comment] 2019-06-07 10:54
This just bit me as well. Is any progress being made to prevent `/usr/bin` being added to the front of the path?

**Comment by blueyed** [comment] 2019-06-07 15:57
@BenWhetton 

See #1169.
You could test it / provide feedback there I guess?!

**Comment by blueyed** [comment] 2019-09-23 17:27
Duplicate of https://github.com/pyenv/pyenv/issues/789.

**Closed by blueyed** 2019-09-23 17:27 UTC
Labels: area: shims
