### ISSUE TITLE
python shim switches versions depending on python's command line argument

### ISSUE THREAD

**Issue by jagmoreira** [pyenv/pyenv#479] opened 2015-11-12 19:23 UTC
There's something weird happening with the `python` shim as of pyenv 20151105.

Let's say I have this folder structure:

```
35/
    .python-version                   sets a local python 3.5.0
    test.py
    27/
        .python-version               sets a local python 2.7.10
        dummy.txt                       just an empty file
```

All `test.py` does is print the current python version:

```
import sys

print(sys.version)
```

Here's what happens if I call test.py by itself:

```
~/35$ python test.py 
3.5.0 (default, Nov 10 2015, 13:26:40) 
[GCC 4.8.4]
```

As expected, since that's the local version I set with `~/35/.python-version`.

But if I just add the dummy file on the command line, pyenv switches to a different version!

```
~/35$ python test.py 27/dummy.txt 
2.7.10 (default, Nov 10 2015, 15:29:47) 
[GCC 4.8.4]
```

I found this while working in a virtual environment and had to read in a file that was outside the environment. My script failed because it tried to import a package that did not exist in my global python.
##

**Comment by blueyed** [comment] 2015-11-12 19:50
That seems to be triggered by the shim for `python` (https://github.com/yyuu/pyenv/blob/9ca7de5b6c0f5b467c9a5a22471d6dc334684c52/libexec/pyenv-rehash#L48-L61).

It will not consider `test.py` for the file (because it has no slash), but then uses `27/dummy.txt`.

@yyuu 
Should the `*/*` pattern get changed to `*` maybe?

@jagmoreira 
You can try if that fixes your issue by manually editing `~/.pyenv/shims/python`:
```diff
--- /home/user/.pyenv/shims/python	2015-10-30 21:57:45.220035993 +0100
+++ /home/user/.pyenv/shims/python.new	2015-11-12 20:49:37.299762686 +0100
@@ -7,7 +7,7 @@
   for arg; do
     case "$arg" in
     -c* | -- ) break ;;
-    */* )
+    * )
       if [ -f "$arg" ]; then
         export PYENV_FILE_ARG="$arg"
         break
```

**Comment by blueyed** [comment] 2015-11-12 19:53
In general it is meant to be a feature, although I am not really sure / convinced about it, but then should only consider the first argument, and not any others.

Even with `python doesnotexist.py 27/test.py`, it should not use the version from `27`, which means that it probably should break for any non-option already?!

**Comment by jagmoreira** [comment] 2015-11-12 22:16
You're right @blueyed , the shim is ignoring my `test.py` because it has no slash.

After I change `*/* )` to `* )` I get:

```
~/35$ python test.py 
pyenv: cannot change working directory to `test.py'
~/35$ python test.py 27/dummy.txt 
pyenv: cannot change working directory to `test.py'
```
However if I call my script as `./test.py` I get the right result:
```
~/35$ python ./test.py
3.5.0 (default, Nov 10 2015, 13:26:40) 
[GCC 4.8.4]
~/35$ python ./test.py 27/dummy.txt 
3.5.0 (default, Nov 10 2015, 13:26:40) 
[GCC 4.8.4]
```

**Comment by blueyed** [comment] 2015-11-12 22:54
> pyenv: cannot change working directory to `test.py'

Looks like PYENV_FILE_ARG is handled incorrectly then somewhere later.

Let's see what @yyuu thinks about this altogether.

**Comment by yyuu** [comment] 2015-11-21 02:05
I confirmed same reproduced with rbenv 0.4.0-183-gc18a3f9. It'd be better to fix this in rbenv as well....

```sh
% find . -type f -ls
535447    4 -rw-r--r--   1 yyuu     yyuu           14 Nov 21 01:59 ./j9/.ruby-version
535448    0 -rw-r--r--   1 yyuu     yyuu            0 Nov 21 01:59 ./j9/dummy.txt
535446    4 -rw-r--r--   1 yyuu     yyuu            6 Nov 21 01:59 ./.ruby-version
535443    4 -rwxr-xr-x   1 yyuu     yyuu           43 Nov 21 02:02 ./test.rb
% cat test.rb
#!/usr/bin/env ruby
puts(RUBY_DESCRIPTION)
% cat .ruby-version
2.2.3
% cat j9/.ruby-version
jruby-9.0.0.0
% ruby test.rb
ruby 2.2.3p173 (2015-08-18 revision 51636) [x86_64-linux]
% ruby test.rb j9/dummy.txt
jruby 9.0.0.0 (2.2.2) 2015-07-21 e10ec96 OpenJDK 64-Bit Server VM 25.72-b05 on 1.8.0_72-internal-b05 +jit [linux-amd64]
```

**Comment by llehtahw** [comment] 2018-11-20 07:43
and what's going on?????

**Comment by native-api** [comment] 2021-02-24 17:24
Duplicate of https://github.com/pyenv/pyenv/issues/1807 and https://github.com/pyenv/pyenv/issues/1813 .

**Closed** 2021-02-25 05:21 UTC
Labels: type: bug, type: question
