### ISSUE TITLE
pyenv executes IMHO wrong python version when executing a python script with in directory tree with a .python-version

### ISSUE THREAD

**Issue by diefans** [pyenv/pyenv#1163] opened 2018-05-31 07:12 UTC
```bash
(
mkdir -p /tmp/env{1,2}
pyenv virtualenv 3.6.5 env1 -f
pyenv virtualenv 2.7.12 env2 -f
echo "env1" > /tmp/env1/.python-version
echo "env2" > /tmp/env2/.python-version
cat > /tmp/env2/sysinfo.py << EOF
from __future__ import print_function
import sys
print('executable:', sys.executable)
print('version:', sys.version)
EOF
cd /tmp/env1
echo "env1 python:" $(python -V)
echo "executed python:" $(python /tmp/env2/sysinfo.py)
)
```
which results in:
```
env1 python: Python 3.6.5
executed python: executable: /home/olli/.pyenv/versions/env2/bin/python version: 2.7.12 (default, Dec 4 2017, 14:50:18) [GCC 5.4.0 20160609]
```

From my point of view the python version in env1 should be used. If indeed this is intended you can close this issue.

### Description
- [ ] Platform information (e.g. Ubuntu Linux 16.04): 16.04
- [ ] OS architecture (e.g. amd64): amd64
- [ ] pyenv version: 1.2.4
- [ ] Python version: 2.7.14 and 3.6.5
- [ ] C Compiler information (e.g. gcc 7.3): does not matter
- [ ] Please attach verbose build log as gist
  * You can turn on verbose debug logging using by setting `PYENV_DEBUG=1`, e.g. `env PYENV_DEBUG=1 pyenv install -v 3.6.4`

**Comment by yyuu** [comment] 2018-05-31 13:11
At moment it's some expected behaviour that pyenv to pick up python version from the script file directory. It might not be intuitive for some cases, though. There are several similar issues e.g. https://github.com/pyenv/pyenv/issues/1150

**Comment by blueyed** [comment] 2018-05-31 15:28
I think it is confusing, too - and not a good default behavior at least.
I guess we should bring this up in the rbenv tracker (i.e. "upstream").
pyenv's code: https://github.com/pyenv/pyenv/blob/8eeddaebc1153313010724f81917a96d62dc4e2a/libexec/pyenv#L61-L71

At least pyenv allows for overriding this behavior because of this indirection:
You could `export PYENV_DIR=$PWD` after `cd /tmp/env1`.
And for Neomake: try setting it there using `let $PYENV_DIR = getcwd()`.

**Comment by ChuckFoo** [comment] 2020-08-17 22:34
I hit this recently too, and was going to write a new issue but after much searching through the existing issues ran across this (surprisingly old) one.

The way I hit it most recently was I had a testcase in one project directory with its own `pyenv virtualenv` environment defined appropriate for testing that project (and set with `pyenv local`), but I hit a problem in another module that project used, so I went to the project directory for that module, created a new clean `pyenv virtualenv` to work in from the same base pyenv python version, set it as `pyenv local` for that directory, made a fix, then tried to run the testcase out of the other directory but using the python that this local virtualenv referenced and was rather surprised to see it not fixed at all still...because it was running in the other local virtualenv which had the broken code pip installed.

It didn't take a super long time to figure out what was going on any of the times I've hit it, but each time it was a little extra frustration that I could have done without. :smiley:

IMHO not only is this behavior non-intuitive (it definitely violates the [principle of least surprise](https://en.wikipedia.org/wiki/Principle_of_least_astonishment)), it also doesn't match the description provided in the pyenv README of how [the python version to be run is located](https://github.com/pyenv/pyenv#choosing-the-python-version) which talks about locating .python-version in the current directory and parents of the current directory.

So, I'd like to add my voice to this plea for considering changing this behavior.

And to not seem like I'm just being negative here, I think pyenv is a wonderfully useful tool and I thank you for its existence. :smiley:

**Comment by native-api** [comment] 2021-05-19 01:36
Duplicate of https://github.com/pyenv/pyenv/issues/1807

**Closed by native-api** 2021-05-19 01:36 UTC
