### ISSUE TITLE
ld: file not found: libpython3.8.a

### ISSUE THREAD

**Issue by alvarezlsq** [pyenv/pyenv#2345] opened 2022-04-29 15:36 UTC
Too many issues will kill our team's development velocity, drastically.
Make sure you have checked all steps below.

### Prerequisite
* [ ] Make sure your problem is not listed in [the common build problems](https://github.com/pyenv/pyenv/wiki/Common-build-problems).
* [ ] Make sure no duplicated issue has already been reported in [the pyenv issues](https://github.com/pyenv/pyenv/issues). You should look for closed issues, too.
* [ ] Make sure you are not asking us to help solving your specific issue.
  * GitHub issues is opened mainly for development purposes. If you want to ask someone to help solving your problem, go to some community site like [Gitter](https://gitter.im/yyuu/pyenv), [StackOverflow](https://stackoverflow.com/questions/tagged/pyenv), etc.
* [ ] Make sure your problem is not derived from packaging (e.g. [Homebrew](https://brew.sh)).
  * Please refer to the package documentation for the installation issues, etc.
* [ ] Make sure your problem is not derived from plugins.
  * This repository is maintaining `pyenv` and the default `python-build` plugin only. Please refrain from reporting issues of other plugins here.

### Description
- [ ] Platform information (e.g. Ubuntu Linux 16.04): Mac OS X Monterey 12.3.1
- [ ] OS architecture (e.g. amd64): Intel
- [ ] pyenv version: 2.2.5
- [ ] Python version: 3.8.12
- [ ] C Compiler information (e.g. gcc 7.3): 11.3.0
- [ ] Please attach the debug trace of the failing command as a gist:
  * Run `env PYENV_DEBUG=1 <faulty command> 2>&1 | tee trace.log` and attach `trace.log`. E.g. if you have a problem with installing Python, run `env PYENV_DEBUG=1 pyenv install -v <version> 2>&1 | tee trace.log` (note the `-v` option to `pyenv install`).

Command:
`CC=$(brew --prefix gcc)/bin/gcc-11 pyenv install -v 3.8.12`

[trace.log](https://github.com/pyenv/pyenv/files/8591980/trace.log)

**Comment by native-api** [comment] 2022-04-29 17:15
Duplicate of https://github.com/pyenv/pyenv/issues/2340

**Comment by alvarezlsq** [comment] 2022-04-29 17:19
I didn't find any solution in #2340 or #2143

**Comment by native-api** [comment] 2022-05-04 01:02
There are a number of possible causes and fixes given in the tickets given. If you have already ruled them all out, there's no indication of that in this report.

**Comment by native-api** [comment] 2022-05-04 01:04
For the record, building Python in MacOS with GCC instead of Apple CLang makes in incompatible with stock PyPI wheels -- so it's not a good idea in the general case to begin with.

**Closed** 2022-06-03 01:44 UTC
Labels: need-feedback
