### ISSUE TITLE
macOS 10.13.3 High Sierra install 3.6.4 ModuleNotFoundError: No module named '_scproxy'

### ISSUE THREAD

**Issue by ningxia** [pyenv/pyenv#1107] opened 2018-02-28 20:52 UTC
pyenv install 3.6.4
python-build: use openssl from homebrew
python-build: use readline from homebrew
Downloading Python-3.6.4.tar.xz...
-> https://www.python.org/ftp/python/3.6.4/Python-3.6.4.tar.xz
Installing Python-3.6.4...
python-build: use readline from homebrew

BUILD FAILED (OS X 10.13.3 using python-build 20160602)

Inspect or clean up the working tree at /var/folders/wq/yjmrv8b107sb1_y838s46phm0000gn/T/python-build.20180228154458.65634
Results logged to /var/folders/wq/yjmrv8b107sb1_y838s46phm0000gn/T/python-build.20180228154458.65634.log

Last 10 log lines:
  File "/private/var/folders/wq/yjmrv8b107sb1_y838s46phm0000gn/T/python-build.20180228154458.65634/Python-3.6.4/Lib/ensurepip/__init__.py", line 27, in _run_pip
    import pip
  File "/var/folders/wq/yjmrv8b107sb1_y838s46phm0000gn/T/tmpi4_d4qx4/pip-9.0.1-py2.py3-none-any.whl/pip/__init__.py", line 21, in <module>
  File "/var/folders/wq/yjmrv8b107sb1_y838s46phm0000gn/T/tmpi4_d4qx4/pip-9.0.1-py2.py3-none-any.whl/pip/_vendor/requests/__init__.py", line 65, in <module>
  File "/var/folders/wq/yjmrv8b107sb1_y838s46phm0000gn/T/tmpi4_d4qx4/pip-9.0.1-py2.py3-none-any.whl/pip/_vendor/requests/utils.py", line 23, in <module>
  File "/var/folders/wq/yjmrv8b107sb1_y838s46phm0000gn/T/tmpi4_d4qx4/pip-9.0.1-py2.py3-none-any.whl/pip/_vendor/requests/compat.py", line 58, in <module>
  File "/private/var/folders/wq/yjmrv8b107sb1_y838s46phm0000gn/T/python-build.20180228154458.65634/Python-3.6.4/Lib/urllib/request.py", line 2585, in <module>
    from _scproxy import _get_proxy_settings, _get_proxies
ModuleNotFoundError: No module named '_scproxy'
make: *** [install] Error 1

**Comment by joshfriend** [comment] 2018-02-28 21:21
Duplicate of #521

Try running `xcode-select --install`, using google seems to indicate that it could be a problem with your build environment

**Closed by joshfriend** 2018-02-28 21:21 UTC

**Comment by jalevin** [comment] 2018-04-19 22:02
Besides pyenv I also could not install ruby versions via rbenv. At this point I started looking at the system. I'd recently upgraded and used the migration assistant to move to a new machine.

1. go to Applications and run Xcode. I had additional packages install
2. run brew doctor. if any files in /usr/local/include show up you have 2 options. Either rename the directory to something else like include_old or remove the offending entries. I chose the first.

``` sudo mv /usr/local/include /usr/local/include_old ```
``` sudo mkdir /usr/local/include ```
``` sudo chown $YOU_USERNAME:admin /usr/local/include ```

afterward, I was able to install ruby and python versions

**Comment by NIC619** [comment] 2018-10-22 04:42
Same here. Recently used migration assistant too.

Replacing the old `/usr/local/include` directory solved the problem. And `brew doctor` did gave warning about the headers in `/usr/local/include`. Wish I had knew...

**Comment by liguobao** [comment] 2020-02-12 14:30
SDKROOT=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk MACOSX_DEPLOYMENT_TARGET=10.14 pyenv install 3.8.0

work for me .

**Comment by toioski** [comment] 2021-03-16 13:19
@jalevin you saved my day! Thanks a lot, that was my issue on Big Sur.
