### ISSUE TITLE
.pyenv/libexec/pyenv line 43: cd: xxx.py: Not a directory

### ISSUE THREAD

**Issue by changsijay** [pyenv/pyenv#807] opened 2017-01-13 19:02 UTC
$ cat test1.py
```
#!/usr/bin/env python
print("hello")
```

$ chmod +x test1.py
$ ln -s test1.py test2
$ ./test2

```
/home/csj/.pyenv/libexec/pyenv: line 43: cd: test1.py: Not a directory
hello
```

**Comment by jonganc** [comment] 2017-09-19 05:30
Note: this is addressed (though not fixed/merge in #689 ). 
There, they point to a workaround: run `./configure && make` in pyenv's src dir, which will generate libexec/pyenv-realpath.dylib and work around the issue.

**Comment by blueyed** [comment] 2018-09-19 08:15
Closing as duplicate of #580.

**Closed by blueyed** 2018-09-19 08:15 UTC
