### ISSUE TITLE
Unable able to install 3.7.5 in Mac OS 12.4

### ISSUE THREAD

**Issue by Hafiz408** [pyenv/pyenv#2388] opened 2022-06-08 15:46 UTC
### Error

<img width="708" alt="Screenshot 2022-06-08 at 8 58 46 PM" src="https://user-images.githubusercontent.com/65387738/172656590-bf287600-4369-4411-9398-6f631ae22b52.png">

### Trace file
[trace.log](https://github.com/pyenv/pyenv/files/8863167/trace.log)

### Prerequisite
* [x] Make sure your problem is not listed in [the common build problems](https://github.com/pyenv/pyenv/wiki/Common-build-problems).
* [x] Make sure no duplicated issue has already been reported in [the pyenv issues](https://github.com/pyenv/pyenv/issues). You should look for closed issues, too.
* [x] Make sure you are not asking us to help solving your specific issue.
  * GitHub issues is opened mainly for development purposes. If you want to ask someone to help solving your problem, go to some community site like [Gitter](https://gitter.im/yyuu/pyenv), [StackOverflow](https://stackoverflow.com/questions/tagged/pyenv), etc.
* [x] Make sure your problem is not derived from packaging (e.g. [Homebrew](https://brew.sh)).
  * Please refer to the package documentation for the installation issues, etc.
* [x] Make sure your problem is not derived from plugins.
  * This repository is maintaining `pyenv` and the default `python-build` plugin only. Please refrain from reporting issues of other plugins here.

### Description
- [x] Platform information (e.g. Mac OS 12.4):
- [x] OS architecture (e.g. amd64 m1 ):
- [x] pyenv version: 2.3.1
- [x] Python version: 3.7.5
- [x] C Compiler information (e.g. gcc 11): 
- [x] Please attach the debug trace of the failing command as a gist:
  * Run `env PYENV_DEBUG=1 <faulty command> 2>&1 | tee trace.log` and attach `trace.log`. E.g. if you have a problem with installing Python, run `env PYENV_DEBUG=1 pyenv install -v <version> 2>&1 | tee trace.log` (note the `-v` option to `pyenv install`).

**Comment by native-api** [comment] 2022-06-08 19:26
[CPython <3.7.8 doesn't support MacOS 11.](https://github.com/pyenv/pyenv/issues/1737#issuecomment-833177844)

**Comment by native-api** [comment] 2022-06-08 19:27
Duplicate of https://github.com/pyenv/pyenv/issues/1737

**Closed by native-api** 2022-06-08 19:27 UTC
