### ISSUE TITLE
Cannot install Python < 3.8 on Debian

### ISSUE THREAD

**Issue by ohlookemus** [pyenv/pyenv#1791] opened 2021-01-25 19:19 UTC
Too many issues will kill our team's development velocity, drastically.
Make sure you have checked all steps below.

### Prerequisite
* [x] Make sure your problem is not listed in [the common build problems](https://github.com/pyenv/pyenv/wiki/Common-build-problems).
* [x] Make sure no duplicated issue has already been reported in [the pyenv issues](https://github.com/pyenv/pyenv/issues). You should look for closed issues, too.
* [x] Make sure you are not asking us to help solving your specific issue.
  * GitHub issues is opened mainly for development purposes. If you want to ask someone to help solving your problem, go to some community site like [Gitter](https://gitter.im/yyuu/pyenv), [StackOverflow](https://stackoverflow.com/questions/tagged/pyenv), etc.
* [x] Make sure your problem is not derived from packaging (e.g. [Homebrew](https://brew.sh)).
  * Please refer to the package documentation for the installation issues, etc.
* [x] Make sure your problem is not derived from plugins.
  * This repository is maintaining `pyenv` and the default `python-build` plugin only. Please refrain from reporting issues of other plugins here.

### Description
- [ ] Platform information (e.g. Ubuntu Linux 16.04): Ubuntu 20.10
- [ ] OS architecture (e.g. amd64): AMD64
- [ ] pyenv version: 1.2.22
- [ ] Python version: 3.7.9
- [ ] C Compiler information (e.g. gcc 7.3): gcc (Ubuntu 10.2.0-13ubuntu1) 10.2.0
- [ ] Please attach verbose build log as gist: https://gist.github.com/ohlookemus/f0b83d3b8dfc90bbef6695c7563d82fc
  * You can turn on verbose debug logging using by setting `PYENV_DEBUG=1`, e.g. `env PYENV_DEBUG=1 pyenv install -v 3.6.4`

I was able to install Python 3.8.x and 3.9.x just fine but anything below 3.8 gives me this error that I cannot seem to figure out what the root cause is. I tried install each version of 3.7 and a few versions of 3.6 before I gave up.

**Comment by anton-petrov** [comment] 2021-02-21 08:50
Please, show your log file

**Comment by ohlookemus** [comment] 2021-02-21 10:13
> Please, show your log file

Hi Anton, I attached it in as a gist if that’s what you meant. 

https://gist.github.com/ohlookemus/f0b83d3b8dfc90bbef6695c7563d82fc

**Comment by ohlookemus** [comment] 2021-05-05 15:28
I've unfortunately not had any luck in getting 3.7.x installed.

**Comment by native-api** [comment] 2021-05-06 22:09
No diagnostic output provided as required by the issue template -- so impossible to say what's wrong.

**Comment by native-api** [comment] 2021-05-06 22:14
The diagnostic output must be of `pyenv install -v <version>` as required by the issue template.

Duplicate of https://github.com/pyenv/pyenv/issues/665

**Closed by native-api** 2021-05-06 22:14 UTC

**Comment by ohlookemus** [comment] 2021-05-10 16:01
I'm not sure why this was closed for not having the output as I attached it as a gist file as required by the template as required???
