### ISSUE TITLE
macOS build in python 3.7.3 not listed with pyenv versions

### ISSUE THREAD

**Issue by Acidham** [pyenv/pyenv#1585] opened 2020-04-12 08:16 UTC
macOS comes with build in python 2.7.16 and python 3.7.3. 

* `python -V` shows 2.7.16
* `python3 -V` shows 3.7.3

`pyenv versions` shows:
* system (set by...) 

I assume 3.7.3 should also be listed there, correct? Is it technically not possible due to macOS build in python and not changeable (system integrity) or is there a way to add this to pyenv for completeness?

### Description
- Platform information (e.g. Ubuntu Linux 16.04): macOS 10.15.4
- OS architecture (e.g. amd64): 8-Core Intel Core i9
- pyenv version: pyenv 1.2.18
- Python version: 3.7.3 (build in macOS), 2.7.16 (build in macOS)

**Comment by native-api** [comment] 2021-05-17 23:09
Duplicate of https://github.com/pyenv/pyenv/issues/1436

**Closed by native-api** 2021-05-17 23:09 UTC
