### ISSUE TITLE
install 3.6.3 fails with final output line of "configure: error: internal configure error for the platform triplet, please file a bug report"

### ISSUE THREAD

**Issue by hejackson2** [pyenv/pyenv#2488] opened 2022-10-17 17:01 UTC
Too many issues will kill our team's development velocity, drastically.
Make sure you have checked all steps below.

### Prerequisite
* [x ] Make sure your problem is not listed in [the common build problems](https://github.com/pyenv/pyenv/wiki/Common-build-problems).
* [x ] Make sure no duplicated issue has already been reported in [the pyenv issues](https://github.com/pyenv/pyenv/issues). You should look for closed issues, too.
* [x ] Make sure you are not asking us to help solving your specific issue.
  * GitHub issues is opened mainly for development purposes. If you want to ask someone to help solving your problem, go to some community site like [Gitter](https://gitter.im/yyuu/pyenv), [StackOverflow](https://stackoverflow.com/questions/tagged/pyenv), etc.
* [ x] Make sure your problem is not derived from packaging (e.g. [Homebrew](https://brew.sh)).
  * Please refer to the package documentation for the installation issues, etc.
* [x ] Make sure your problem is not derived from plugins.
  * This repository is maintaining `pyenv` and the default `python-build` plugin only. Please refrain from reporting issues of other plugins here.

### Description
- [ x] Platform information (e.g. Ubuntu Linux 16.04):
MacOS 12.6 (16-inch MBP 2019)
bash: 5.2.2(1)
pyenv: 2.3.4

- [x ] OS architecture (e.g. amd64):
intel core i7

- [x ] pyenv version: 2.3.4
- [ x] Python version: attempting to install 3.6.3

- [ x] C Compiler information (e.g. gcc 7.3): 
$ gcc --version
Apple clang version 14.0.0 (clang-1400.0.29.102)
Target: x86_64-apple-darwin21.6.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin

- [x ] Please attach the debug trace of the failing command as a gist:
  * Run `env PYENV_DEBUG=1 <faulty command> 2>&1 | tee trace.log` and attach `trace.log`. E.g. if you have a problem with installing Python, run `env PYENV_DEBUG=1 pyenv install -v <version> 2>&1 | tee trace.log` (note the `-v` option to `pyenv install`).
[trace.log](https://github.com/pyenv/pyenv/files/9802936/trace.log)

**Comment by native-api** [comment] 2022-10-18 17:47
Python <3.7.8, 3.8.4 and 3.9.0 do not support MacOS 11+.

**Comment by native-api** [comment] 2022-10-18 17:48
Duplicate of https://github.com/pyenv/pyenv/issues/1737

**Closed by native-api** 2022-10-18 17:48 UTC
