### ISSUE TITLE
Enhance documentation for new users

### ISSUE THREAD

**Issue by Jasata** [pyenv/pyenv#1470] opened 2019-11-28 19:05 UTC
Too many issues will kill our team's development velocity, drastically.
Make sure you have checked all steps below.

### Prerequisite
* [x] Make sure your problem is not listed in [the common build problems](https://github.com/pyenv/pyenv/wiki/Common-build-problems).
* [x] Make sure no duplicated issue has already been reported in [the pyenv issues](https://github.com/pyenv/pyenv/issues). You should look for closed issues, too.
* [x] Make sure you are not asking us to help solving your specific issue.
  * GitHub issues is opened mainly for development purposes. If you want to ask someone to help solving your problem, go to some community site like [Gitter](https://gitter.im/yyuu/pyenv), [StackOverflow](https://stackoverflow.com/questions/tagged/pyenv), etc.
* [x] Make sure your problem is not derived from packaging (e.g. [Homebrew](https://brew.sh)).
  * Please refer to the package documentation for the installation issues, etc.
* [x] Make sure your problem is not derived from plugins.
  * This repository is maintaining `pyenv` and the default `python-build` plugin only. Please refrain from reporting issues of other plugins here.

### Description
- [x] Platform information (e.g. Ubuntu Linux 16.04): N/A
- [x] OS architecture (e.g. amd64): N/A
- [x] pyenv version: N/A
- [x] Python version: N/A
- [x] C Compiler information (e.g. gcc 7.3): N/A
- [x] Please attach verbose build log as gist: nope
  * You can turn on verbose debug logging using by setting `PYENV_DEBUG=1`, e.g. `env PYENV_DEBUG=1 pyenv install -v 3.6.4`

I wanted to become a user. I read the README, I read Wiki and I even Googled around (a little), but I did not find a single word about how to handle multiple Python versions in terms of installing them and how does that relate to pyenv and its needs/configurations, so I chose instead to just write this issue (and not get into this for now).

Perhaps it is a non-issue. Maybe whatever package managers like apt, yum etc. do is just fine - I wouldn't know. Whatever it is, even if it is something that one does not need to worry one bit, should you not at least mention this in the documentation? Perhaps a simple additional page in the wiki "Installing and Handling Python Versions" or such, even if it tells us that "just install them with your package manager. No additional actions needed, pyenv got your back."

I hope this bit of information is relatively simple to add and that it encourages potential users to give this a try.

**Comment by native-api** [comment] 2021-05-08 15:14
Duplicate of https://github.com/pyenv/pyenv/issues/1677

**Closed by native-api** 2021-05-08 15:14 UTC
