### ISSUE TITLE
wrong version selected if command-line arguments contained a filename

### ISSUE THREAD

**Issue by Aikhjarto** [pyenv/pyenv#1478] opened 2019-12-10 14:02 UTC
A wrong python version is selected if a command-line argument references a file in a folder that also contains a .python-version file.

## Minimal Example
**Having the following four files**
./main.py
```python
import sys
print(sys.version)
```
./.python_version
```
3.7.5
```
./folder/.python_version
```
3.6.5
```
./folder/config.txt
```
any content
```
**Executing python main.py w/o arguments**
```bash
> python main.py
3.7.5 (default, Nov 27 2019, 12:39:01)
[GCC 7.4.1 20190424 [gcc-7-branch revision 270538]]
```
**Executing python main.py with any arguments**
```bash
> python main.py some argument
3.7.5 (default, Nov 27 2019, 12:39:01)
[GCC 7.4.1 20190424 [gcc-7-branch revision 270538]]
```

**Executing python main.py with any arguments where one is a file in a different folder containing a separate file named .python-version**
```bash
> python main.py foo folder/config.txt bar
3.6.5 (default, Jul 30 2019, 10:50:49)
[GCC 7.4.0]
```
```bash
> python main.py folder/config.txt
3.6.5 (default, Jul 30 2019, 10:50:49)
[GCC 7.4.0]
```

I expect, that all 4 calls to `python main.py` to use python 3.7.5 regardless of arguments to 'main.py'

### Description
- [ ] Platform information: openSUSE Leap 15.1
- [ ] OS architecture amd64:
- [ ] pyenv version: 1.2.14-15-g089b828b
- [ ] Python version: 3.6.5 and 3.7.5
- [ ] C Compiler information: 7.4

**Comment by dstoe** [comment] 2020-10-17 11:37
Can confirm:
* OS: Ubuntu 20.04.1
* Pyenv: 1.2.18

This is very confusing behavior, since my expectation as a user is, to use the python-interpreter that's specified for the current working directory and shouldn't be modified by any cli-arguments later in the command.

**Comment by nsw42** [comment] 2020-12-05 13:02
I tripped over this issue yesterday, and have spent a while investigating. It looks like the shim does not recognise a local file (`main.py` in the OP's example). I've experimented with a workaround/fix and it looks like this change to the shim works.

```
*** python.orig	2020-10-26 14:59:02.000000000 +0000
--- python	2020-12-05 12:51:48.000000000 +0000
***************
*** 8,21 ****
--- 8,27 ----
      case "$arg" in
      -c* | -- ) break ;;
      */* )
        if [ -f "$arg" ]; then
          export PYENV_FILE_ARG="$arg"
          break
        fi
        ;;
+     *)
+       if [ -f "$arg" ]; then
+         export PYENV_FILE_ARG="./$arg"
+         break
+       fi
+       ;;
      esac
    done
  fi
  
  export PYENV_ROOT="/Users/neil/.pyenv"
  exec "/usr/local/Cellar/pyenv/1.2.21/libexec/pyenv" exec "$program" "$@"
```

So, that would suggest that adding the same *) clause to create_prototype_shims() in pyenv/libexec/pyenv-rehash (with appropriate backslash escaping for the $ signs) should fix it more globally. However, I've not yet tested this more than seeing that the change fixes the problem I encountered, and there might be side effects that I haven't thought about.

(For the record: macOS Catalina, with pyenv 1.2.21 and pyenv-virtualenv installed)

**Comment by native-api** [comment] 2021-05-20 04:40
Duplicate of https://github.com/pyenv/pyenv/issues/1807

**Closed by native-api** 2021-05-20 04:40 UTC
