### ISSUE TITLE
Can't switch the python version normally

### ISSUE THREAD

**Issue by ekko-zhao** [pyenv/pyenv#2196] opened 2021-12-21 09:34 UTC
os:
MacOS Catalina
version 10.15.7 (19H2)
MacBook Pro (16-inch, 2019)

bug:
after update to version 2.2.2
![image](https://user-images.githubusercontent.com/26781518/146906072-a302bb2b-0838-43c9-9daa-a7b9858030fe.png)
I can't switch the python version normally。
![image](https://user-images.githubusercontent.com/26781518/146905977-944c05f2-0249-4aab-842b-595a485fabb1.png)

**Comment by ekko-zhao** [comment] 2021-12-21 09:37
installing with Homebrew

**Comment by native-api** [comment] 2021-12-21 17:22
Duplicate of https://github.com/pyenv/pyenv/issues/2135

**Closed by native-api** 2021-12-21 17:22 UTC
