### ISSUE TITLE
Command exists in these Python versions... 

### ISSUE THREAD

**Issue by narun4sk** [pyenv/pyenv#1475] opened 2019-12-07 19:28 UTC
### Description
- [x] Platform information (e.g. Ubuntu Linux 16.04):
```
> uname -a
Linux archlinux 5.4.1-arch1-1 #1 SMP PREEMPT Fri, 29 Nov 2019 13:37:24 +0000 x86_64 GNU/Linux
```
- [x] OS architecture (e.g. amd64): `x86_64`

- [x] pyenv version:
```
> pyenv --version
pyenv 1.2.15
```
- [x] Python version:
```
> python --version
Python 3.8.0
```
---

Here I have a situation:
```
> pyenv global 
system
> pyenv version
system (set by PYENV_VERSION environment variable)
> pip list | awk '/aws-mfa/'
aws-mfa                       0.0.12
> pyenv shell virtualenv-2
> pyenv version
virtualenv-2 (set by PYENV_VERSION environment variable)
> pip list | awk '/aws-mfa/'
> aws-mfa
pyenv: aws-mfa: command not found

The `aws-mfa' command exists in these Python versions:
  virtualenv-1
```

That's correct, `aws-mfa` package is installed in the `pyenv` managed  `virtualenv-1`, but it is also installed in the `system`'s Python!

I had expected that the PATH will be resolved as follows:
1. if pkg exists in the active env - then use it, otherwise check the system's packages
2. if pkg exists in the system's env - then use it, otherwise error, but check the other virtualenvs
3. if pkg exists in the other envs - be helpful and list the envs in the error message

However it seems to me that the step `2` has not been implemented or is malfunctioning. Or is it by design? :roll_eyes: 

It's very confusing, as the standard `virtualenv` doesn't have these issues... eg.:

```
nrz@archlinux ~/pyenv-tst> pyenv version
system (set by /home/nrz/.pyenv/version)
nrz@archlinux ~/pyenv-tst> virtualenv test
Using base prefix '/usr'
New python executable in /home/nrz/pyenv-tst/test/bin/python
Installing setuptools, pip, wheel...
done.
nrz@archlinux ~/pyenv-tst> . test/bin/activate.fish 
(test) nrz@archlinux ~/pyenv-tst> pip list | awk '/aws-mfa/'
(test) nrz@archlinux ~/pyenv-tst> aws-mfa
INFO - Validating credentials for profile: default 
INFO - Your credentials are still valid for 39712.970826 seconds they will expire at 2019-12-08 06:22:54
```

**Comment by mayanksuman** [comment] 2019-12-10 12:10
Similar to #1204

**Comment by narun4sk** [comment] 2019-12-12 22:53
Not sure if that will be helpful, but on my `MacOS` workstation I have `pyenv 1.2.11`, which works correctly, thus if the pkg is installed system wide then it will not matter if it is not installed in the `pyenv version`, as the system one will be used instead. On my Linux workstation I have `pyenv 1.2.15`.

After a little bit more digging I've discovered that on `MacOS` I have *aws-mfa* `shim`, which explains why it works on that particular system:
```
> command -v aws-mfa
/Users/narun4sk/.pyenv/shims/aws-mfa
> cat /Users/narun4sk/.pyenv/shims/aws-mfa
#!/usr/bin/env bash
set -e
[ -n "$PYENV_DEBUG" ] && set -x
program="${0##*/}"
if [[ "$program" = "python"* ]]; then
  for arg; do
    case "$arg" in
    -c* | -- ) break ;;
    */* )
      if [ -f "$arg" ]; then
        export PYENV_FILE_ARG="$arg"
        break
      fi
      ;;
    esac
  done
fi
export PYENV_ROOT="/Users/narun4sk/.pyenv"
exec "/Users/narun4sk/.pyenv/libexec/pyenv" exec "$program" "$@"
```

Any idea how I might have got it? It must be a part of some `pyenv` addons package on `MacOS`, as I don't remember installing *aws-mfa* `shim` explicitly.

**Comment by native-api** [comment] 2021-05-09 17:54
Duplicate of https://github.com/pyenv/pyenv/issues/1204

**Closed by native-api** 2021-05-09 17:54 UTC
