### ISSUE TITLE
3.6.1 Fails to install correctly on FreeBSD 11: invalid Python executable

### ISSUE THREAD

**Issue by xaque208** [pyenv/pyenv#886] opened 2017-04-01 19:19 UTC
```
$ CFLAGS="-DOPENSSL_NO_SSL2" /home/zach/.pyenv/bin/pyenv install 3.6.1
Downloading Python-3.6.1.tgz...                                       
-> https://www.python.org/ftp/python/3.6.1/Python-3.6.1.tgz
Installing Python-3.6.1...
ERROR: invalid Python executable: /home/zach/.pyenv/versions/3.6.1/bin/python3.6

The python-build could not find proper executable of Python after successful build.
Please open an issue for future improvements.
https://github.com/pyenv/pyenv/issues

BUILD FAILED (FreeBSD 11.0-RELEASE-p8 using python-build 1.0.10-2-geef042a)

Inspect or clean up the working tree at /tmp/python-build.20170401121039.4503
Results logged to /tmp/python-build.20170401121039.4503.log

Last 10 log lines:
rm -f /home/zach/.pyenv/versions/3.6.1/bin/pyvenv
(cd /home/zach/.pyenv/versions/3.6.1/bin; ln -s pyvenv-3.6 pyvenv)
if test "x" != "x" ; then  rm -f /home/zach/.pyenv/versions/3.6.1/bin/python3-32;  (cd /home/zach/.pyenv/versions/3.6.1/bin; ln -s python3.6-32 python3-32)  fi
rm -f /home/zach/.pyenv/versions/3.6.1/share/man/man1/python3.1
(cd /home/zach/.pyenv/versions/3.6.1/share/man/man1; ln -s python3.6.1 python3.1)
if test "xupgrade" != "xno"  ; then  case upgrade in  upgrade) ensurepip="--upgrade" ;;  install|*) ensurepip="" ;;  esac;   ./python -E -m ensurepip  $ensurepip --root=/ ;  fi
Collecting setuptools
Collecting pip
Installing collected packages: setuptools, pip
Successfully installed pip-9.0.1 setuptools-28.8.0
```

The CFLAGS were added after looking for other freebsd related issues on this project, and I've been building other versions of python using pyenv with that method for some time now.

**Comment by blueyed** [comment] 2017-06-16 06:50
Any update on this?

**Comment by xaque208** [comment] 2017-09-18 20:14
This remains to be an issue on 3.6.2.

**Comment by xaque208** [comment] 2018-02-21 02:23
This remains an issue on 3.6.4.
```
Creating directory /home/zach/.pyenv/versions/3.6.4/share/man
Creating directory /home/zach/.pyenv/versions/3.6.4/share/man/man1
/usr/bin/install -c -m 644 ./Misc/python.man  /home/zach/.pyenv/versions/3.6.4/share/man/man1/python3.6.1
if test ! -d /home/zach/.pyenv/versions/3.6.4/lib/pkgconfig; then  echo "Creating directory /home/zach/.pyenv/versions/3.6.4/lib/pkgconfig";  /usr/bin/install -c -d
 -m 755 /home/zach/.pyenv/versions/3.6.4/lib/pkgconfig;  fi
if test -f /home/zach/.pyenv/versions/3.6.4/bin/python3 -o -h /home/zach/.pyenv/versions/3.6.4/bin/python3;  then rm -f /home/zach/.pyenv/versions/3.6.4/bin/python3
;  else true;  fi
(cd /home/zach/.pyenv/versions/3.6.4/bin; ln -s python3.6 python3)
if test "3.6" != "3.6m"; then  rm -f /home/zach/.pyenv/versions/3.6.4/bin/python3.6-config;  (cd /home/zach/.pyenv/versions/3.6.4/bin; ln -s python3.6m-config pytho
n3.6-config);  rm -f /home/zach/.pyenv/versions/3.6.4/lib/pkgconfig/python-3.6m.pc;  (cd /home/zach/.pyenv/versions/3.6.4/lib/pkgconfig; ln -s python-3.6.pc python-
3.6m.pc);  fi
rm -f /home/zach/.pyenv/versions/3.6.4/bin/python3-config
(cd /home/zach/.pyenv/versions/3.6.4/bin; ln -s python3.6-config python3-config)
rm -f /home/zach/.pyenv/versions/3.6.4/lib/pkgconfig/python3.pc
(cd /home/zach/.pyenv/versions/3.6.4/lib/pkgconfig; ln -s python-3.6.pc python3.pc)
rm -f /home/zach/.pyenv/versions/3.6.4/bin/idle3
(cd /home/zach/.pyenv/versions/3.6.4/bin; ln -s idle3.6 idle3)
rm -f /home/zach/.pyenv/versions/3.6.4/bin/pydoc3
(cd /home/zach/.pyenv/versions/3.6.4/bin; ln -s pydoc3.6 pydoc3)
rm -f /home/zach/.pyenv/versions/3.6.4/bin/2to3
(cd /home/zach/.pyenv/versions/3.6.4/bin; ln -s 2to3-3.6 2to3)
rm -f /home/zach/.pyenv/versions/3.6.4/bin/pyvenv
(cd /home/zach/.pyenv/versions/3.6.4/bin; ln -s pyvenv-3.6 pyvenv)
if test "x" != "x" ; then  rm -f /home/zach/.pyenv/versions/3.6.4/bin/python3-32;  (cd /home/zach/.pyenv/versions/3.6.4/bin; ln -s python3.6-32 python3-32)  fi
rm -f /home/zach/.pyenv/versions/3.6.4/share/man/man1/python3.1
(cd /home/zach/.pyenv/versions/3.6.4/share/man/man1; ln -s python3.6.1 python3.1)
if test "xupgrade" != "xno"  ; then  case upgrade in  upgrade) ensurepip="--upgrade" ;;  install|*) ensurepip="" ;;  esac;   ./python -E -m ensurepip  $ensurepip --
root=/ ;  fi
Collecting setuptools
Collecting pip
Installing collected packages: setuptools, pip
Successfully installed pip-9.0.1 setuptools-28.8.0
```
This looks to be the issue to me `if test "3.6" != "3.6m";`, but I don't know where that is coming from.  Looks like the version built doesn't match the version we expect, even though the build is successful.

**Comment by xaque208** [comment] 2018-08-03 05:52
Seems like the build script might be doing something funny.

Leaving the sources in place, I can run the following.
```
cd ~/.pyenv/sources/3.6.6/Python-3.6.6
./configure --prefix ~/.pyenv/versions/3.6.6
make install
```

The above works, which allows me to `pyenv global 3.6.6` and have a functional pyenv.

**Comment by xaque208** [comment] 2018-08-03 06:02
I also needed to manually update my shims and ensure that the correct versions were linked in the bin directory.  It seems the trailing `m` is coming from the python build.

**Comment by native-api** [comment] 2021-05-07 23:02
Duplicate of #1196

**Comment by native-api** [comment] 2021-05-21 15:18
@xaque208 Could you provide a debug trace as required by the issue template?

Looks like you have something set in the environment that affects the build -- CPython builds don't normally produce executables with the `m` suffix.

**Comment by native-api** [comment] 2021-05-21 15:19
@xaque208 Could you provide a debug trace and other information as required by the issue template?

Looks like you have something set in the environment that affects the build -- CPython builds don't normally produce executables with the `m` suffix.

**Comment by native-api** [comment] 2021-06-09 23:02
https://github.com/pyenv/pyenv/pull/1196#issuecomment-858156061

**Closed by native-api** 2021-06-09 23:02 UTC
Labels: need-feedback, type: bug
