### ISSUE TITLE
Install failed, 'X11/Xlib.h' file not found on macOS Mojave

### ISSUE THREAD

**Issue by naiduklr936** [pyenv/pyenv#1573] opened 2020-03-25 22:54 UTC
When installing the `2.7.11` python version using `pyenv` I'm getting the following error

`python-build.20200325184905.80044/Python-2.7.11/Modules/_tkinter.o -framework Tk`

`clang: warning: -framework Tk: 'linker' input unused [-Wunused-command-line-argument]`

`In file included from /private/var/folders/k5/2ybr_hdd7w7d5814__47vykw0000gq/T/python-build.20200325184905.80044/Python-2.7.11/Modules/_tkinter.c:71:`

`/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/include/tk.h:78:11: fatal error: 'X11/Xlib.h' file not found`

`#       include <X11/Xlib.h>`
              
`1 error generated.`

But successfully installed the `3.7.7`

Environment:

`pyenv 1.2.17`

**Comment by joshfriend** [comment] 2020-03-27 15:38
seems to be a dupe of #1392

**Closed by joshfriend** 2020-03-27 15:38 UTC
